### ISSUE TITLE
Also support optional HAL Link fields

### ISSUE THREAD

**Issue by edrik** [spring-projects/spring-hateoas#100]
The HAL support so far is great but for it to be really usable the optional link fields defined by the HAL specification should also be available.

There is a pull request #79 about adding a type and title but there are allot more optional fields defined by [HAL](http://tools.ietf.org/html/draft-kelly-json-hal). Not sure if adding all the fields to the Link class is the best solution but that would be a quick fix.

So far I've used a extended version of the Link class that adds the fields (and a fix for the issue with selecting the appropriate JsonSerializer, also noticed by #88). But that is far from ideal and makes allot of the convenience method unusable.

Any thoughts on how this could be implemented in a reasonably unobtrusive manner?

**Comment by olivergierke** [comment]
Fixed with #567.
