### ISSUE TITLE
Documentation for HAL-FORMS resource bundles for _templates is wrong

### ISSUE THREAD

**Issue by toedter** [spring-projects/spring-hateoas#1012]
In the docs, all resource bundle content related to HAL-FORMS _templates that contain `_template.` has to be changed to `_templates.` (plural s).

E.G. in the section "4.2.1. Internationalization of form attributes":
`_template.$affordanceName.title` => `_templates.$affordanceName.title`

This has to be corrected also in the section 'Example 34. Defining HAL-FORMS template titles'

**Comment by odrotbohm** [comment]
That had been fixed with the [polishing commit](2bc511a021555755c6c23d37100e7a0fa2e3ecbe) but not deployed until a few minutes ago. It's live now [here](https://docs.spring.io/spring-hateoas/docs/current-SNAPSHOT/reference/html/#mediatypes.hal-forms.i18n).
