### ISSUE TITLE
ControllerLinkBuilder can not handle alwaysUseFullPath=true

### ISSUE THREAD

**Issue by Laures** [spring-projects/spring-hateoas#102]
- the servlet mapping is "players/*"
- the PlayerController has the request mapping "/players/" 
- the HandlerMapping is configured with alwaysUseFullPath=true

Then a links to the PlayerController will look like:

http://localhost:8080/players/players/1

the easiest solution would be if i could (globaly?) configure the ControllerLinkBuilder to ignore the servlet-mapping when creating the builder initially. then the call path(mapping) would not add the servlet-mapping a second time.

**Comment by gregturn** [comment]
Current solution leverages the servlet request combined with the @RequestMapping annotation's link, making this issue out of date.
