### ISSUE TITLE
Migration for BasicLinkBuilder in 1.0.0.M3

### ISSUE THREAD

**Issue by marcuslange** [spring-projects/spring-hateoas#1020]
We are doing a test migration to v1. I don't see BasicLinkBuilder in the new structure and the documents do not have the upgrade path for this use case.

Is there a replacement or work around?

Can this be added to the migration documentation?

**Comment by odrotbohm** [comment]
Looks like this was removed accidentally. I just added the type back, now residing in `server.mvc` and adapted the migration script accordingly. Let me know whether this is fine for you.
