### ISSUE TITLE
Properly deprecate UriTemplate's constructors

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#1044]
In https://github.com/spring-projects/spring-hateoas/commit/39404ea2d9ef462c08c6c47722e49585890b6492, `UriTemplate` had both of its constructors reduced in visibility (replaced by a static method), breaking the Spring Initializr.

They need to be made public again with proper deprecation warnings. We can still reduce their visibility before GA. We simply need to follow proper deprecation procedures.

**Comment by snicoll** [comment]
Thanks for reconsidering

> We can still reduce their visibility before GA. We simply need to follow proper deprecation procedures.

IMO, reducing visibility before GA is the same as the current situation. If we want to properly deprecate, we should have at least one feature release where users have a chance to notice.

**Comment by gregturn** [comment]
1.0.0.RC2 will go out with this deprecation in place, before we reach GA.

**Comment by snicoll** [comment]
Thanks but I think it might be wise to include the deprecation in at least one release. I know the previous version was a `0.x` release, but it was still a managed Spring Boot dependency and we have quite a few users that don’t try the milestones or release candidates. It looks like leaving the deprecated constructors in place won’t cause any real problems, they’re just not as performant as the static factory method.

**Comment by gregturn** [comment]
Are you saying deprecated warnings need to live in at least one GA release? If so, noted. I'll let @odrotbohm make the final call on that.
