### ISSUE TITLE
@EnableHypermediaSupport does not provide a ContollerEntityLinks bean when using WebFlux

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-hateoas#1062]
The documentation currently states that `ControllerEntityLinks` will be included in the default setup but that does not appear to be the case when using WebFlux.

**Comment by gregturn** [comment]
I have dug in a little, and discovered that to implement this, we need a `WebFluxLinkBuilderFactory`. The contract underlying this (`WebFluxLinkBuilder`) is very different than `WebMvcLinkBuilder`, as in, Reactor-based types, functional concepts, and different inputs (`ServerWebExchange`).

I'm not convinced the abstraction in place that supports plugging in a `ControllerEntityLinks` bean is a drop in for WebFlux. It appears heavily driven by Spring MVC.

The implication is that we need something more akin to a `WebMvcControllerEntityLinks` bean and a `WebFluxControllerEntityLinks` bean.

Thoughts @odrotbohm?

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/36baafe764ea278ab5ece69e7bfb061cdd8c54c5.

**Comment by gregturn** [comment]
Follow #1071 to track adding a WebFlux-specific EntityLinks variant.
