### ISSUE TITLE
Using spring-hateoas behind a HTTPS proxy

### ISSUE THREAD

**Issue by lorethan** [spring-projects/spring-hateoas#107]
Hi.

I am using the ControllerLinkBuilder to generate links for my responses, but I am not able to override the protocol in any way. The proxy (Hiawatha) uses https, but forwards to my tomcat server with http.

Is there anything I have missed that should make this possible, or is the some hook that could make this possible in any way?

**Comment by andreasevers** [comment]
I'm wondering how you would forward a prefix to the URI.

Considering @Laures mentioning "https://wherever/your/service/is", would it be possible to get the following scenario to work:

The gateway is located on:
`https://www.test.com/TESTPREFIX/customer/123`
While the actual endpoint is located on:
`http://blabla.internal/customer/123`

The actual endpoint has a link to:
`http://blabla.internal/customer/123/products`

And that link should be returned to the gateway as:
`https://www.test.com/TESTPREFIX/customer/123/products`

In this scenario I can use "X-Forwarded-Proto" and "X-Forwarded-Host", but how would I forward the prefix?

**Comment by andreasevers** [comment]
Seems like "X-Forwarded-Prefix" did the trick for me, but I don't understand completely why.

**Comment by dominicfarr** [comment]
@lorethan See, https://jira.spring.io/browse/SPR-12500 why this works.

**Comment by jhusson** [comment]
With Apache in front of tomcat, you can resolve the problem by specifing the header as part of your virtual host configuration

    <VirtualHost *:443>
    RequestHeader set X-Forwarded-Proto "https"
    ProxyPreserveHost On
    ServerName www.example.com

    SSLEngine On
    SSLCertificateFile /etc/apache2/ssl/server.crt
    SSLCertificateKeyFile /etc/apache2/ssl/server.key

    <Location/>
        SSLRequireSSL
    </Location>

    ProxyPass / http://127.0.0.1:9000/
    ProxyPassReverse / http://127.0.0.1:9000/
    </VirtualHost>

**Comment by seansms** [comment]
I don't have control over the header.  Our networking team has chosen a proprietary header because the "standard" header has unpredictable results.  It would be useful if we could specify our own header.

**Comment by seansms** [comment]
I just wrote a shim to transform the link based on the request header to resolve it for now.

**Comment by rbuer** [comment]
For those having this issue with Spring > 5.1: It handles the forward-headers properly, but you have to enable it by setting the property `server.use-forward-headers=true`

**Comment by gregturn** [comment]
You can read it in detail => https://docs.spring.io/spring-hateoas/docs/1.0.0.RC2/reference/html/#server.link-builder.forwarded-headers

**Comment by pcornelissen** [comment]
Requiring my clients to provice the header is bad and error prone. To have to fake the forwarded header doesn't seem a too good idea either (obfuscates the fact that you just want to set the hostname for generated links and may have side effects that are non obvious)
Why not provide a property or a way to set the hostname programmatically for the HATEOAS link-generation?
The spring way would be to have some kind of hostname provider bean that you override if you need special handling. That feels much more "spring-ish" to me.

**Comment by gregturn** [comment]
What is the configuration of yours servers? Because this is textbook cloud configuration. Having an app behind a load balancer KNOW what the load balancer knows sort of de-inverts things.

**Comment by pcornelissen** [comment]
It's not a real loadbalancer, when you use Eureka or consul to make client side loadbalancing using service-IDs, then you don't have forwarded headers.

**Comment by gregturn** [comment]
Since we aren’t talking about an HTTP proxy, would you be willing to open a new ticket?
