### ISSUE TITLE
Resource.class not producing xml for content.

### ISSUE THREAD

**Issue by rkaltreider** [spring-projects/spring-hateoas#108]
When marshalling Resource.class, the content is not marshalled.  All i get is an xml package like this

<resource xmlns:atom="http://www.w3.org/2005/Atom">
<atom:link rel="self" href="http://localhost:8080/api/users/51cd99840a766d40c3a2b7bd"/>
</resource>

However, if I wrap the Resource.class with my own class and override getContent() and annotate with @XmlElement, it works.  Would you be able to add that annotation to getContent() or am i doing somethign wrong.  Resources.class works just fine, its just Resource.class that I have to wrap. Thanks!

**Comment by gregturn** [comment]
As of #695, Spring HATEOAS no longer supports XML.
