### ISSUE TITLE
Entity mappings serialisation with Spring Data Rest

### ISSUE THREAD

**Issue by genglefr** [spring-projects/spring-hateoas#1092]
Since I migrated to Spring boot 2.2 RC1, when I'm querying my rest data repositories, every `@OneToMany` or `@ManyToOne` annotated fields are automatically added into a `content` array property, with specific `rel` for every sub properties.

Example (`http://localhost:8080/<my_collection>`):

```
{
  "links": [
    {
      "rel": "self",
      "href": "http://localhost:8080/<my_collection>?page=0&size=20"
    }
  ],
  "content": [
      "id": "e977696a-f0b4-46ee-ae08-25bfe885e866",
      ...
      "content": [
        {
          "rel": "dealer",
          ...
        },
        {
          "rel": "customer",
          ...
        }
  ],
  "page": {
    "size": 20,
    "totalElements": 5,
    "totalPages": 1,
    "number": 0
  }
}
```

This causes important performance impact, since every mapping serialization costs database access.

Note that:
- When using Spring Boot 2.2M4, everything works fine;
- When I specify a `projection`, the additional `content` property with mappings is not serialised.

**Comment by gregturn** [comment]
Something’s not right. Because that ain’t HAL.

**Comment by gregturn** [comment]
What does your build file look like?

**Comment by genglefr** [comment]
It's a spring data bug when checking excerpt.
I created a ticket and proposed a fix:
https://jira.spring.io/browse/DATAREST-1435

**Comment by odrotbohm** [comment]
The issue is in Spring Data REST, i.e. there's nothing to do right here.
