### ISSUE TITLE
WebMvcHateoasConfiguration not applied for plain client application

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-hateoas#1098]
This is for hateoas 1.0.0. As a simple client wanting to consume hateoas content via traverson we need to have a specific HAL module loaded for `RestClient`.

Issue seem to be in a `WebStackImportSelector` which uses `WebStack` to see if, well, stack is available. As those will check classpath if `org.springframework.web.servlet.DispatcherServlet` or `org.springframework.web.reactive.DispatcherHandler`, conditions are never true in a client app having no server side classes.

Thus `@EnableHypermediaSupport(type = EnableHypermediaSupport.HypermediaType.HAL)` on a client side don't enable needed jackson configs.

**Comment by gregturn** [comment]
@odrotbohm I've coded a solution that splits apart client-side beans from server-side beans, so in a client-only setup (only having `spring-web` on the classpath), Spring HATEOAS still operates as expected and properly wires `RestTemplate` beans.

However, this makes the Java enum `WebStack` not sound right. It was aimed at being either **Spring MVC** or **Spring WebFlux**. That has been widened to really mean **server side Spring MVC**, **server side Spring WebFlux**, **client side Spring MVC**, or **client side Spring WebFlux**. And those are NOT web stacks.

So we need something different to name it. And we probably need to thus deprecate `WebStack`.

**Comment by gregturn** [comment]
Resolved via 03ac8021.

**Comment by gregturn** [comment]
@odrotbohm Is this fix a candidate for backporting to `1.0.x`? If the classes are package private, then this shouldn't break existing code, right?

**Comment by odrotbohm** [comment]
Surely is, yes!
