### ISSUE TITLE
Has the usage of Link been changed?

### ISSUE THREAD

**Issue by chadmalla-ff** [spring-projects/spring-hateoas#1105]
I get a series of error: 

`org.jeasy.random.ObjectCreationException: Unable to create a random instance of type class org.springframework.hateoas.Link` 

`Unable to create type: org.springframework.hateoas.LinkRelation for field: rel of class: org.springframework.hateoas.Link`

`org.jeasy.random.ObjectCreationException: Unable to create a random instance of type interface org.springframework.hateoas.LinkRelation`

I have ran the migration script and have checked that these classes exist in the `Hateoas 1.0.0.RELEASE.jar`. Is there anything more I have to do when using `Link` and `LinkRelation` due to API changes?

Thanks!

**Comment by gregturn** [comment]
Can you show some of the code where these errors are getting reported?

**Comment by chadmalla-ff** [comment]
@gregturn Hey actually I realized it could be the `jeasy` giving me the problem. But basically I am trying to create a random instance of `Link.class`. 

`random.nextObject(Link.class)`

The `nextObject` method is as follows:

`
private final EasyRandom easyRandom;
`
`
public <T> T nextObject(final Class<T> type) {
        return easyRandom.nextObject(type);
    }
`

**Comment by gregturn** [comment]
I can't predict `Link` playing nicely with that utility. Do its APIs let you steer things a certain way?

**Comment by gregturn** [comment]
Essentially, `new Link("http://example.com/api/foo/bar")` would create a `self` link. The URI has to be valid or it will blow up. You can supply a `LinkRelation.of("custom-rel")`. 

I don't know how this toolkit is supposed to know stuff like this.

**Comment by chadmalla-ff** [comment]
This is an [issue](https://github.com/j-easy/easy-random/issues/371) that has been posted recently on their Github recently. Has there been any changes to the class implementation related to `Enum`. 

Before the migration of `spring boot 2.2` and `Hateoas 1.0.0` the implementation worked without me supplying a URL

**Comment by gregturn** [comment]
For a short amount of time, `IanaLinkRelations` was a Java `enum` that implemented an interface.

But I believe @odrotbohm is the one that recoded it as a utility class filled with static final constants, like this:

```java
public static final LinkRelation ABOUT = LinkRelation.of("about");
```

**Comment by chadmalla-ff** [comment]
Which method are you asking me to use?

**Comment by chadmalla-ff** [comment]
This is my current `Random` class:

`public class Random {
    private final EasyRandom easyRandom;
    private static Random randomInstance;

    private Random() {
        val now = Instant.now().toEpochMilli();
        log.info("Seed for EasyRandomParameters: {}", now);
        val parameters = new EasyRandomParameters();
        parameters.seed(now);
        easyRandom = new EasyRandom(parameters);
    }

    public static Random getRandomInstance() {
        if (randomInstance == null) {
            randomInstance = new Random();
        }
        return randomInstance;
    }

    public <T> T nextObject(final Class<T> type) {
        return easyRandom.nextObject(type);
    }
}`

**Comment by chadmalla-ff** [comment]
Are you saying I should modify this class to make it be able to create `Link` objects using `nextObject` method ?

**Comment by chadmalla-ff** [comment]
I was able to resolve by creating another class for returning a `Link` class with a random string for `href`. That seems to solve it. Thanks @gregturn !
