### ISSUE TITLE
LinkDiscovers @Bean Configuration

### ISSUE THREAD

**Issue by chadmalla-ff** [spring-projects/spring-hateoas#1106]
So the workaround with `Springfox` using older `spring-core-plugin version` than `Hateoas` was to have the `Springfox` dependency before `Hateoas` and having to defines beans for `LinkDiscovers` and `LinkRelationProvider`. This works as the application starts. The problem is the response objects are now different then what I got when I didn't have any bean configurations. 

Before: 

```json
{
  "_embedded": {
    "entityModels": [
      {
        "_links": {
          "link1": {
            "href": "http://localhost/api/"
          },
          "self": {
            "href": "http://localhost/api/endpoint"
          },
          "link2": {
            "href": "http://localhost/api/endpoint/hello"
          }
        },
        "bm_id": "foo",
        "pt_id": "bar",
        "r_id": "foobar"
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost/api/endpoint/tests"
    }
  },
  "page": {
    "number": 0,
    "size": 0,
    "total_elements": 1,
    "total_pages": 1
  }
}
```

and now: 

```json
{
  "content": [
    {
      "bm_id": "foo",
      "links": [],
      "pt_id": "bar",
      "r_id": "foobar"
    }
  ],
  "links": [
    {
      "href": "http://localhost/api/endpoint/tests",
      "rel": "self"
    }
  ],
  "page": {
    "number": 0,
    "size": 0,
    "total_elements": 1,
    "total_pages": 1
  }
}
```

This is my bean configuration: 

 ```java
   @Bean
    public LinkDiscoverers discoverers() {
        List<LinkDiscoverer> plugins = new ArrayList<>();
        plugins.add(new CollectionJsonLinkDiscoverer());
        return new LinkDiscoverers(SimplePluginRegistry.create(plugins));
    }
```

```java
@Bean
    public LinkRelationProvider provider() {
        return new DelegatingLinkRelationProvider();
    }
```

Is there a default bean configuration for `LinkDiscovers` that I can have that will give response objects like I had before with `_embedded` ?

**Comment by gregturn** [comment]
Frankly I haven’t a clue where to begin debugging this. Making the system work with a prior version of Spring Plugin is probably breaking something irrevocably. 

And I’m not sure how much I want to. 

How hard is it to work on a PR to springfox?

**Comment by chadmalla-ff** [comment]
It is a little harder than it seems. I have a colleague working on changing the  `spring plugin` for `springfox` but comes with a lot of other changes with the codebase that take time to change. 

I will close this ticket if there isn't any configuration that comes to your mind on the `Hateoas` side to get the response objects to be returned as before.

**Comment by chadmalla-ff** [comment]
But just wondering is there a way to configure how the response objects should be in general within `Hateoas`? Say for example, instead of getting `entityModels` I want my response to `snake cased` so `entity_models`?

**Comment by gregturn** [comment]
Thats a different question.  

In the docs (https://docs.spring.io/spring-hateoas/docs/1.0.0.RELEASE/reference/html/#server.rel-provider) you can easily customize link relations using different tactics.  

Not sure anyone has built a snake case LinkRelationProvider yet.

**Comment by odrotbohm** [comment]
Let's please not drag out changes that need to happen in Springfox here. There's a [ticket](https://github.com/springfox/springfox/issues/2932) over in their bug tracker, that clearly identified, that they need to upgrade to Spring Plugin 2.0 and Spring HATEOAS 1.0 to support Spring Boot 2.2. That's a pretty straightforward requirement.

Creating more places of discussion for the same topic doesn't add any value but only increases the noise.
