### ISSUE TITLE
Refine factory methods and nullability checks for RepresentationModel types

### ISSUE THREAD

**Issue by SBylemans** [spring-projects/spring-hateoas#1116]
Sonar issued us a curious warning which made us look into the code why this warning was issued.  Sonar reported a resource's content should be checked against null because the third constructor in EntityModel has a `@Nullable` annotation for content. However, directly below that, there's an `Assert.notNull` for content. Also, the documentation says that content should not be nullable...

**Constructor**
```
	/**
	 * Creates a new {@link EntityModel} with the given content and {@link Link}s.
	 *
	 * @param content must not be {@literal null}.
	 * @param links the links to add to the {@link EntityModel}.
	 */
	public EntityModel(@Nullable T content, Iterable<Link> links) {

		Assert.notNull(content, "Content must not be null!");
		Assert.isTrue(!(content instanceof Collection), "Content must not be a collection! Use Resources instead!");
		this.content = content;
		this.add(links);
	}
```

**Comment by odrotbohm** [comment]
Good catch. I just had a brief look and think I need to consult @gregturn as the only places the constructor gets a potentially nullable value handed in are ones coming from the media type support for Uber and CollectionJson. They don't seem to ever produce `null` values so we might even be able to tighten the constraints even further.

**Comment by gregturn** [comment]
`EntityModel` is a public API, so users can feed `content` with a `null` value. If I understand, the whole point of `@Nullable` is so that we no longer need `Assert.notNull()` calls, right?

**Comment by odrotbohm** [comment]
The opposite. Due to the assertion, handing in `null` was never in fact possible. If we remove the annotation, we end up with a few places of our own code handing in a potentially `null` value. We should rather create a plain `RepresentationModel` in those cases.

I have a bit of polishing code here already. Let's see if we can discuss this in the upcoming days.

**Comment by odrotbohm** [comment]
This should be fixed now. See the newly introduced `….of(…)` factory methods in all `RepresentationModel` types as well as in `Link`.
