### ISSUE TITLE
NullPointerException building link to method that returns RedirectView

### ISSUE THREAD

**Issue by mkhl** [spring-projects/spring-hateoas#1117]
Alternate title: NullPointerException reading the properties of a class with a property without a read method

The easiest way to trigger this is by invoking:

```
PropertyUtils.getExposedProperties(org.springframework.web.servlet.view.RedirectView.class)
```

which unfortunately happens automatically when using `linkTo(methodOn(Controller.class).redirect())` for any method that returns a RedirectView.

The cause seems to be that RedirectView hat a `setAttributes` method (inherited from AbstractView) that `BeanUtils#getPropertyDescriptors` recognises as a property, but neither `PropertyUtils#getPropertyDescriptors` nor `PropertyUtils#readerIsNotToBeIgnoredByJackson` check that the property has a read method before calling `MergedAnnotations.from(descriptor.getReadMethod())`, which does not accept the null argument.

**Comment by odrotbohm** [comment]
Looks like #1121 / #1124.
