### ISSUE TITLE
MemoryLeak caused by UriTemplate cache

### ISSUE THREAD

**Issue by chringwer** [spring-projects/spring-hateoas#1118]
I noticed that `UriTemplate.CACHE` is never evicted. With recent changes it seems that any `Link` instance holds a template whether the href is templated or not. So, if an API exposes a lot of links with concrete URLs that will create a lot of cache entries when parsed into `Link`s and underlying `UriTemplate`s .

This led to `OutOfMemoryError`s eventually in our application.

**Comment by justintgregory** [comment]
+1 for encountering this same error. this is definitely a hindrance to using spring HATEOAS in production.

**Comment by alexander-riss** [comment]
@odrotbohm looks like a high severity item? will this be addressed in the next release?

**Comment by odrotbohm** [comment]
Will definitely part of the next service release and thus included in the Boot one downstream.

**Comment by odrotbohm** [comment]
Should be available in 1.0.2.BUILD-SNAPSHOT in a few minutes. Feel free to give them a try!

**Comment by gregturn** [comment]
@odrotbohm That commit is on `master`, which is `1.1`. Still needs to be backported to `1.0.x`.
