### ISSUE TITLE
Configuring RestTemplate breaks in a pure Spring WebFlux application

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#1119]
While `RestTemplate` and `HttpMessageConverter` are in `spring-web`, `WebMvcConfigurer` is in `spring-webmvc`.

Spring HATEOAS leverages `WebMvcConfigurer` to help configure `RestTemplate` beans and thus breaks in a pure Spring WebFlux application since this class is unavailable.

**Comment by gregturn** [comment]
NOTE: This should backported to `1.0.x` as well.

**Comment by gregturn** [comment]
I just verified this patch works in my pure Spring WebFlux application against Spring Boot 2.2.1.RELEASE.

**Comment by odrotbohm** [comment]
I've slightly reworked the changes and merged them. Revisiting the changes I wondered though why the class to be fixed (`RestTemplateHateoasConfiguration`) would actually be included in a bootstrap in a pure WebFlux arrangement in the first place? `WebStack` checks for the presence of `DispatcherServlet` which *is* part of `spring-webmvc` and only includes the configuration class if that's present. If it is, using `WebMvcConfigurer` should be safe in the first place, shouldn't it?

**Comment by odrotbohm** [comment]
Nevermind, I got it. The previously offending configuration is included in case `RestTemplate` is on the classpath, which lives in `spring-web`. All good.

**Comment by gregturn** [comment]
Problem still exists despite this patch (albeit smaller scope).

Because `org.springframework.web.client.RestTemplate` is in `spring-web`, and visible in WebFlux application, activates `RestTemplateHateoasConfiguration`.

Hence, your pure WebFlux application will invoke this:

```
@Bean
static HypermediaRestTemplateBeanPostProcessor hypermediaRestTemplateBeanPostProcessor(
		WebMvcConverters converters) {
	return new HypermediaRestTemplateBeanPostProcessor(converters);
}
```
...which fails because `WebMvcConverters` was from `WebMvcHateoasConfiguration` (as expected).

It looks like if I add:

```
	@Bean
	WebMvcConverters hypermediaWebMvcConverters(ObjectProvider<ObjectMapper> mapper,
			List<HypermediaMappingInformation> information) {
		return WebMvcConverters.of(mapper.getIfUnique(ObjectMapper::new), information);
	}
```
...to `WebFluxHateoasConfiguration`, then everything passes.

Installed in my local maven repo, my pure WebFlux app works.

Of course, this requires that I signal Boot's autoconfigure to switch off their MVC-specific stuff with:

```
spring.hateoas.use-hal-as-default-json-media-type=false
```
, but that's a separate issue.

**Comment by gregturn** [comment]
My patch is here => https://github.com/spring-projects/spring-hateoas/commit/e9977637d7529ec70ad75c608f7c515fd17f9bdc

Whether or not we need `WebMvcConverters` in `WebFluxHateoasConfiguration` is questionable, but we may just have to bite it. RestTemplate, while Spring MVC oriented (using HttpMessageConverters), is stuck with us in `spring-web`.

**Comment by odrotbohm** [comment]
As previously known `WebMvcConverters` does *not* depend on `spring-webmvc` in the first place, I moved the bean declaration into the shared `HateoasConfiguration` and added a couple of test cases. Backports into 1.0.x done, too.
