### ISSUE TITLE
HAL hypertext cache pattern

### ISSUE THREAD

**Issue by reda-alaoui** [spring-projects/spring-hateoas#1125]
Hi,

I am using Spring MVC with Spring HATEOAS and would like to use hypertext cache pattern as defined in HAL specification.

> 8.3.  Hypertext Cache Pattern
> 
>    The "hypertext cache pattern" allows servers to use embedded
>    resources to dynamically reduce the number of requests a client
>    makes, improving the efficiency and performance of the application.
> 
>    Clients MAY be automated for this purpose so that, for any given link
>    relation, they will read from an embedded resource (if present) in
>    preference to traversing a link.
> 
>    To activate this client behaviour for a given link, servers SHOULD
>    add an embedded resource into the representation with the same
>    relation.
> 
>    Servers SHOULD NOT entirely "swap out" a link for an embedded
>    resource (or vice versa) because client support for this technique is
>    OPTIONAL.
> 
>    The following examples shows the hypertext cache pattern applied to
>    an "author" link:
> 
>    Before:
> 
>    {
>      "_links": {
>        "self": { "href": "/books/the-way-of-zen" },
>        "author": { "href": "/people/alan-watts" }
>      }
>    }
> 
> 
>    After:
> 
>    {
>      "_links": {
>        "self": { "href": "/blog-post" },
>        "author": { "href": "/people/alan-watts" }
>      },
>      "_embedded": {
>        "author": {
>          "_links": { "self": { "href": "/people/alan-watts" } },
>          "name": "Alan Watts",
>          "born": "January 6, 1915",
>          "died": "November 16, 1973"
>        }
>      }
>    }
> 

Are you planning to ease hypertext cache pattern usage?

I envisioned an optional flag per link that could be set during the construction of the list of links. When enabled, during serialization (?), the flag would trigger the Spring MVC controller method described by the link, allowing to complete the embedded content with the object returned by the method.

**Comment by gregturn** [comment]
We offer this in [Spring Data REST](https://docs.spring.io/spring-data/rest/docs/3.2.2.RELEASE/reference/html/#projections-excerpts.excerpting-commonly-accessed-data). 

However, when YOU are baking the content with a pure Spring HATEOAS application, it's up to you. Which circles back to the desire to directly do "embedding" for HAL documents. Which is why I created #864 

If you read the history of that one, you'll see that it offers a vendor neutral way to define such custom resources where both the URI and the data could be in one document, offering such a cached approach.

**Comment by gregturn** [comment]
As of 1.1.0.RELEASE, you can now do this.

See https://docs.spring.io/spring-hateoas/docs/1.1.0.RELEASE/reference/html/#mediatypes.hal.models for details.

In the meantime, feel free to open a new ticket if you run into issues.

Resolved via #864
