### ISSUE TITLE
Spring hateoas show title ="" even the property title of Link is null

### ISSUE THREAD

**Issue by kingtran2112** [spring-projects/spring-hateoas#1129]
Hi,

I am using spring-hateoas 1.0.1.RELEASE and spring boot 2.2.1.RELEASE.

I have a simple Person class:
```@AllArgsConstructor
 @Getter
 public class Person {
	private String id;
	private String name;
}
```

Assembler:
```
 @Component
 public class PersonAssembler implements SimpleRepresentationModelAssembler<Person> {
	private final Class<?> controller;

	public PersonAssembler() {
		this.controller = PersonController.class;
	}


	@Override
	public void addLinks(EntityModel<Person> resource) {
		resource.add(WebMvcLinkBuilder.linkTo(controller).slash(resource.getContent().getId()).withSelfRel());
	}

	@Override
	public void addLinks(CollectionModel<EntityModel<Person>> resources) {

	}
 }
```
and Controller:
```
 @RestController
 @RequestMapping("/people")
 @Tag(name = "People Rest API", description = "People Rest API")
 public class PersonController {

	private final PersonAssembler personAssembler;

	public PersonController(PersonAssembler personAssembler) {
		this.personAssembler = personAssembler;
	}

	@GetMapping(value = "/{personId}")
	@Operation(summary = "get person")
	public EntityModel<Person> getPerson(@PathVariable String personId) {
		Person person = new Person(personId, "test");
		return personAssembler.toModel(person);
	}
 }
```
When I send request to get a person, the response body show:
```
 {
  "id": "1",
  "name": "test",
  "_links": {
    "self": {
      "href": "http://localhost:8374/people/1",
      "title": ""
    }
  }
 }
```
I have no clue where is title part comes from. I tried to debug and check the Link object and also see the property title of Link is null. Please take a look. Thank you

**Comment by odrotbohm** [comment]
Are you overriding the Jackson inclusion settings. On Spring HATEOAS side everything is configured to only render non-empty, non-`null` Strings.

**Comment by kingtran2112** [comment]
In the Link object, only rel and href field has a value and the others are null but the title is the only field showed in the response body. So I don't think so. But is there any way can I check for that configuration for Spring HATEOAS?

**Comment by odrotbohm** [comment]
That’s helpful information and I think I have a clue where this is coming from. Do you from which version to which version this has changed? It might have to do with changes in Jackson and I’d like to get a grasp on why we’re not seeing this innSpring HATEOAS‘ tests in the first place.

**Comment by kingtran2112** [comment]
I haven't used it before and just add Spring HATEOAS 1.0.1 as the first implementation

**Comment by odrotbohm** [comment]
Thanks, I’ll have a look.

**Comment by odrotbohm** [comment]
I just copied the code you've shown into a fresh project created via start.spring.io (with HATEOAS and Lombok dependencies). Requesting `/people/4711` I get:

```
HTTP/1.1 200 
Content-Type: application/hal+json
Date: Tue, 03 Dec 2019 18:14:06 GMT
Transfer-Encoding: chunked

{
    "_links": {
        "self": {
            "href": "http://localhost:8080/people/4711"
        }
    }, 
    "id": "4711", 
    "name": "test"
}
```

Would you mind verifying any kind of tweaks you do to the Jackson setup you have? Even better, share an example project that shows the erroneous behavior?

**Comment by kingtran2112** [comment]
Hi, I debugged in my project so I think the problem comes from the message resolver in `HalLinkListSerializer`. Since my project gets `DefaultOnlyMessageResolver` and a fresh project have `MessageSourceResolver` with `ReloadableResourceBundleMessageSource` inside. The result is that `resolver.resolve(rel)` will return "" in my project but null in the fresh project. Is there any way I can change this configuration?

**Comment by odrotbohm** [comment]
I am not sure I follow. My fresh project uses a `DefaultOnlyMessageResolver`, which also results in an empty String being returned from the resolving in `toHalLink(…)`. However, `HalLink`'s `getTitle()` is annotated with `@JsonInclude(Include.NON_EMPTY`, which is evaluated by Jacksons `BeanPropertySerializer` that in turn looks up `StringSerializer` and invokes `….isEmpty()` on it. That returns `true` for Strings of length zero and thus `BeanPropertySerializer` skips writing that property.

I've debugged this by putting a breakpoint into `HalLink.getTitle()` following the handling of the returned value. Would you mind trying that as well and reporting where you see a different path?

**Comment by kingtran2112** [comment]
Oops. My project extends `JsonSerializer<String>`  and `....isEmpty()` is called from `JsonSerializer` which is only check return `true` when value is `null`. Thanks for the hint. But is there any way I can change to `ReloadableResourceBundleMessageSource`? My fresh project didn't config anything, the plain spring-boot project but the class is used so I hope there is some way to do it?

**Comment by odrotbohm** [comment]
The message source is auto-configured based on the presence of a `rest-messages.properties` in `HateoasConfiguration.lookupMessageSource()`.

**Comment by kingtran2112** [comment]
thanks a lot. Have a nice day 👍

**Comment by odrotbohm** [comment]
You as well! Happy coding! 🙃
