### ISSUE TITLE
WebClientConfigurer "drops" ObjectMapper customizations from WebClients

### ISSUE THREAD

**Issue by totof3110** [spring-projects/spring-hateoas#1134]
This is related to https://github.com/spring-projects/spring-framework/issues/23961#issuecomment-552225047.

`WebClientConfigurer` configures the `WebClient`s with the following line:
```java
webClient.mutate().exchangeStrategies(hypermediaExchangeStrategies()).build()
```
which ends up overriding the `WebClient` custom configuration (in my case, the configuration of several Jackson `Module`s as well as my `maxInMemorySize` setting).

@bclozel added some logic in https://github.com/spring-projects/spring-framework/commit/43e047c523fefa1fc876208efd6946ceb2e472a3 that should make it easier for HATEOAS to configure the `WebClient`s without overriding existing config.

**Comment by odrotbohm** [comment]
Looks like there's a few rough edges around the fix for spring-projects/spring-framework#24106 which means it doesn't make it into the next immediate Spring Framework release.

**Comment by odrotbohm** [comment]
Update: looks like Spring Framework team is revisiting. I'll keep this on the radar for 1.0.2 as well.

**Comment by bclozel** [comment]
Note that the `maxInMemorySize` codec preference is configured only on the default codecs, and Spring HATEOAS is registering a custom codec. Spring Framework does not enforce that cofiguration on custom codecs as they may have different opinions.

We've provided still a way for custom codecs to know about such preferences, see spring-projects/spring-framework#24118. @odrotbohm , maybe additional changes need to be made to this configuration?
