### ISSUE TITLE
Apply HATEOAS configuration to WebClient.Builder

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-hateoas#1141]
Currently the `WebClientConfigurer` applies the HATEOAS infrastructure to all `WebClient` beans.

In Spring Boot, we've moved away from a model where the application has `RestTemplate` or `WebClient` beans by default. We're seeing that many applications want several, specialized clients for different needs. We're trying instead to provide an easy way to create a client from a common starting point, with all the preferences expressed by the application itself. Developer can then apply local customizations and get the client for the task at hand.

This is why Spring Boot is now providing `RestTemplateBuilder` and `WebClient.Builder` beans.

I think Spring HATEOAS could apply instead its customizations to those builders, if they are specialized enough to not break existing use cases, or provide a mechanism to let users plug those preferences with builders easily.

**Comment by odrotbohm** [comment]
I like the idea but keep in mind that we cannot reference anything from Spring Boot as it depends on us not the other way round. That said, we can of course expose beans or API to potentially let Boot's auto-configuration tweak the abstractions they introduce to automatically pick up hypermedia configuration for those.

In general, the modifications we apply to the abstractions mentioned work in a way that only get used *if* the user actively uses Spring HATEOAS types, i.e. they're non invasive to any other setup made to the components. From a user's point of view it might feel odd to have to do multiple things to express "I want to use hypermedia".

**Comment by gregturn** [comment]
Superseded by #1224.
