### ISSUE TITLE
Automatically generated endpoints no longer supported?

### ISSUE THREAD

**Issue by RyamBaCo** [spring-projects/spring-hateoas#1143]
Hey there,

I'm currently upgrading my Spring Boot Project to 2.2 (including the 1.x release for Hateoas). In the past for all Resources with a Repository functionality and endpoints for creating, updating and deleting a object has been provided automatically.

So for instance when creating an Entity Picture along with the JPA-Repository I was able to 
- create new pictures with POST on /pictures
- partially update existing pictures with PATCH on /pictures/{id}
- delete existing pictures with DELETE on /pictures/{id}

Now I receive for these endpoints a 405. In the docs I read about affordances but what I see from the example I'd have to create all this endpoints by myself, which would be way too cumbersome within the scope of the project I'm migrating. Am I missing something? Do I have to configure anything to enable this feature? Or has it been removed within the release to 1.x?

**Comment by odrotbohm** [comment]
What you are referring to is functionality provided by Spring Data REST. That in turn uses Spring HATEOAS to provide the HAL based responses.

Did your migration maybe lose the `spring-boot-starter-data-rest` dependency?

**Comment by RyamBaCo** [comment]
Thanks for pointing me to the right direction! The spring-boot-starter-data-rest dependency is present, but we set @RestResource(exported = false) to the save operation on our base repository, looks like the override behavior changed in Spring Boot 2.2

**Comment by odrotbohm** [comment]
We definitely need the method exposed to implement the backing functionality for the HTTP methods you mentioned. The Spring Data REST version included in Spring Boot has indeed seen changes to that area of functionality.

Find information about that in the [updated reference documentation](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#customizing-sdr.repository-exposure). In particular the newly available `ExposureConfiguration` allows more fine grained control over which HTTP methods are supported for certain domain types. More info on that [here](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#customizing-sdr.http-methods.default-exposure).
