### ISSUE TITLE
Not compatible with Jackson AUTO_DETECT disabled

### ISSUE THREAD

**Issue by reda-alaoui** [spring-projects/spring-hateoas#1147]
Hi everyone,

We are using this library in a project where we decided to turn off Jackson auto detection features like this:
```java
objectMapper
        .disable(AUTO_DETECT_CREATORS)
        .disable(AUTO_DETECT_FIELDS)
        .disable(AUTO_DETECT_GETTERS)
        .disable(AUTO_DETECT_IS_GETTERS)
        .disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
````
We did that to have full control on the content serialized to our api consumers.
Therefore, fields are serialized using opt-in instead of opt-out. For each field we want to serialize, we add `@JsonProperty` to it or its getter.

`org.springframework.hateoas.Link` seems to expect the activation of the Jackson auto detection feature. Indeed with auto detection disabled, the link `href` is not serialized anymore.

Would it be ok to fix this issue by appending `@JsonProperty` to every field expecting serialization? And maybe extend this to other classes that may expose the same issue?

**Comment by reda-alaoui** [comment]
Or maybe `HypermediaMappingInformation` implementations should enable auto detect feature on their copied ObjectMapper?

**Comment by reda-alaoui** [comment]
Output with auto detection:

```json
{
  "entity": {},
  "_links": {
    "foos": {
      "href": "http://localhost:8080/api/foos"
    },
    "bars": {
      "href": "http://localhost:8080/api/bars"
    }
  }
}
```

Output without auto detection:

```json
{
  "entity": {},
  "_links": {
    "foos": {},
    "bars": {}
  }
}
```

**Comment by odrotbohm** [comment]
Good catch. I think we never really anticipated that someone would be that defensive. I'll make sure our integration tests actually use that most restrictive setting and alter our model classes to make sure they properly serialize in that context.

**Comment by odrotbohm** [comment]
Would you mind giving the 1.1 snapshot builds a spin? If there's no bigger side effects of this I'll happily backport the fix.

**Comment by reda-alaoui** [comment]
Great ! I'll give it a try ASAP.
Thank you !

**Comment by reda-alaoui** [comment]
Just tested 1.1 snapshot on my project, looks good to me :+1:

**Comment by odrotbohm** [comment]
Backport is in place as well.
