### ISSUE TITLE
Add additional attributes to resource links

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-hateoas#116]
Clients should be able to determine how to interact with REST Services without prior knowledge of the services in HATEOAS, this includes the verb that should be used when interacting with those services. 

A link should be represented as 

```
{
  "rel":"next",
  "href":"...",
  "method":"PUT"
  "title":"Update the Resource",
  "type":"application/json"
}
```

**Comment by gregturn** [comment]
`Link` was upgraded with all the attributes of RFC-5988. See https://github.com/spring-projects/spring-hateoas/pull/567.
