### ISSUE TITLE
Question: is it possible to change the default response content-type to be application/json instead of application/hal+json?

### ISSUE THREAD

**Issue by adamvelo** [spring-projects/spring-hateoas#1164]
We have some clients who are struggling to deal with application/hal+json so I was just wondering if it was possible to customise the Spring config to return content-type application/json instead. Thanks.

**Comment by gregturn** [comment]
Spring Boot already does this. 

If you search on `HateoasProperties`, you'll find that `spring.hateoas.use-hal-as-default-json-media-type` (defaulted as `true`) is configured to serve up HAL for `application/json`.

**Comment by adamvelo** [comment]
@gregturn thanks for the super quick response!

I can't seem to get this setting to make any difference... with the above property set to false.. if a client sends accept: */* would you expect a content-type of application/json or application/hal+json?

Here is a repo with a single failing test: 

https://github.com/adamvelo/haldemo

**Comment by gregturn** [comment]
I'm sorry. I completely misread this property.

What `spring.hateoas.use-hal-as-default-json-media-type=true` does (whereby `true` is the default value)`, is that is you serve up a hypermedia endpoint, should an `Accept: application/json` header still cause the server to yield HAL?

The answer is: yes!

Essentially, if you leave out the property entirely, then this should work nicely.

```
$ curl -v localhost:8080/foo -H 'Accept: application/json' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /foo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: application/json
> 
< HTTP/1.1 200 
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Thu, 06 Feb 2020 03:00:51 GMT
< 
{ [78 bytes data]
100    72    0    72    0     0    379      0 --:--:-- --:--:-- --:--:--   380
* Connection #0 to host localhost left intact
{
  "content": "foo",
  "_links": {
    "self": {
      "href": "http://localhost:8080/foo"
    }
  }
}
```

P.S. I submitted a PR to your demo project that adds a link to nicely illustrate things. (https://github.com/adamvelo/haldemo/pull/1

**Comment by adamvelo** [comment]
@gregturn thanks for the update. Just to clarify then... it's not possible to prefer application/json over application/hal+json in the response when the client states accept: */* ?

thanks.

**Comment by gregturn** [comment]
No.  Submit a wildcard and it will send it’s preferred media type.
