### ISSUE TITLE
Link building does not consider method parameters declared in interfaces

### ISSUE THREAD

**Issue by krraghavan** [spring-projects/spring-hateoas#1189]
I generate all my Spring WebFlux methods in an interface from my Open API specification YAML file.  The controller implements the methods in this interface.  I also use WebFluxLinkBuilder to build my HATEOAS links in my returned response.  However, unless the implementation has the @RequestParam/@PathVariable annotations, the generated links do not get resolved with the actual values.  Ideally I shouldn't need to repeat what's in the interface in my implementation.

**Comment by gregturn** [comment]
You have an interface with `@RequestParam` but not the implementation itself?

**Comment by gregturn** [comment]
Makes sense given support for Spring Web itself in https://github.com/spring-projects/spring-framework/issues/15682.

**Comment by gregturn** [comment]
Expanded scope of this issue to Spring MVC.
