### ISSUE TITLE
XML response and Resource<T> wrapper

### ISSUE THREAD

**Issue by marlandy** [spring-projects/spring-hateoas#119]
Hi all!!,

I´ve working with spring-hateoas and I have a Controller that returns both JSON and XML responses according to the response format requested. 

When I return an entity object wrapped into a Resource<T> in XML format, I can´t see my entity content in the response. However, when my entity extends ResourceSupport and  is not wrapped into Resource<T>, there´s no problem. When JSON response it works fine in every way.

For example:

When I return:

``` java
// stadium extends ResourceSupport and is annotated by @XmlRootElement
return new ResponseEntity<>(stadium, HttpStatus.CREATED);
```

That´s the response:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<stadium>
    <atom:link rel="self" href="http://localhost:8080/soccer/api/stadiums/1003" />
    <name>Mestalla</name>
</stadium>
```

But the problem occurs when return:

``` java
// stadium does not extends ResourceSupport but has @XmlRootElement
Resource<Stadium> resource = new Resource<>(new Stadium("Mestalla"));
resource.add(/* whatever link*/);
return new ResponseEntity<>(resource, HttpStatus.CREATED);
```

That´s the response (No name tag. Root element is resource instead of stadium):

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource>    
    <atom:link rel="self" href="http://localhost:8080/soccer/api/stadiums/1003" />
</resource>
```

What I´m doing wrong?

Thanks and regards.

**Comment by gregturn** [comment]
As of #695, Spring HATEOAS no longer supports XML.
