### ISSUE TITLE
Caching ControllerLinkBuilder for efficient reuse

### ISSUE THREAD

**Issue by pimlottc** [spring-projects/spring-hateoas#120]
The steps ControllerLinkBuilder takes to determine the correct URL for a controller/method seem fairly expensive for a task that may have to be many times for some requests (especially the methodOn proxy-based version).  It does not look like there is any internal caching going on nor is the returned object flexible enough to be cached (as you must pass the resource-specific parameters through in the factory method call).

It seems like a better way would be to decouple the code that derives the template from the final parameterization and link building.  The API might look something more like:

```
LinkBuilder widgetHrefBuilder = ControllerLinkBuilder.linkTo(WidgetController.class);

for (Widget w : getWidgets()) {
  Link self = widgetHrefBuilder.withParameters(w.getId()).withSelfRel();
  ...
}
```

What do you think?  Am I missing something?

**Comment by gregturn** [comment]
Resolved via #749.
