### ISSUE TITLE
Make HypermediaWebTestClientConfigurer conditional on spring-test

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#1252]

**Comment by juergenzimmermann** [comment]
@gregturn Unfortunately this issue is - at least for me - a killer for upgrading Spring Boot.
I tried to define a constraint in build.gradle.kts, but the version number of Spring HATEOAS jumps back to 1.0.0.M3.

**Comment by gregturn** [comment]
@juergenzimmermann if you track https://github.com/spring-projects/spring-hateoas/pull/1251, I don't anticipate taking long to resolve this one.

**Comment by juergenzimmermann** [comment]
@gregturn Thank you very much. I'll give you feedback after you've merged the PR.

**Comment by odrotbohm** [comment]
That's in place plus a bit of polish in the configuration area to avoid premature initialization of beans.

**Comment by gregturn** [comment]
@juergenzimmermann Feel free to take Spring HATEOAS `1.1.0.BUILD-SNAPSHOT` out for a spin.

**Comment by juergenzimmermann** [comment]
@gregturn Thank you very much and congratulations! All my tests run successful with _Spring Boot 2.3.0.M4_ and _Spring HATEOAS 1.1.0.BUILD-SNAPSHOT_.
