### ISSUE TITLE
How to make HATEOAS consider contextPath ?

### ISSUE THREAD

**Issue by ludovic-andreas-toth** [spring-projects/spring-hateoas#1268]
Hi,

I have a problem described in more details here: https://stackoverflow.com/questions/61124099/context-path-not-considered-in-hateoas-links-when-upgrading-from-spring-boot-1-5.

Basically after upgrading to the latest version of spring boot(2.2.26), when using hateoas, the Links are not containing the context-path(server.servlet.context-path).

I have tried using forward-headers-strategy with  both FRAMEWORK and NATIVE with a ForwardedHeaderFilter. Adiitionally, the x-forwarded-prefix cannot be set from the config with tomcat.

Are there any guidelines about how to deal with this issue or how to avoid it ?

**Comment by gregturn** [comment]
Hmm. When I apply such a setting to `spring-hateoas-examples`, it works.

See https://github.com/spring-projects/spring-hateoas-examples/pull/31.

**Comment by gregturn** [comment]
If you rip out all forwarding settings and code, but keep the servlet context stuff, what happens then?

**Comment by gregturn** [comment]
Based on no feedback and my own example working, I'm closing this issue. If you have further feedback, we can reopen this issue.

**Comment by ctwoolsey** [comment]
@gregturn I'm seeing this issue in my API behind Spring-Boot-Gateway.  I hope it is just something I'm configuring incorrectly.  I'm using Spring Boot Framework 3.0.2.
