### ISSUE TITLE
Add Kotlin source to released artifacts

### ISSUE THREAD

**Issue by Patouche** [spring-projects/spring-hateoas#1270]
Hello,

I notice that the Koltin sources of spring hateoas are not present in the generate jar during the  maven phase attach-sources phases.

You will find soon a PR to solve this. Hope this may help.

**Comment by gregturn** [comment]
Resolved via fd9a9951.

**Comment by gregturn** [comment]
Thanks @Patouche!

**Comment by gregturn** [comment]
Backported `1.0.x`.
