### ISSUE TITLE
Align Naming for Kotlin Extension Functions with Spring

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-hateoas#1275]
Spring (WebFlux) has e.g. this extension function:
```
suspend fun ServerResponse.BodyBuilder.bodyValueAndAwait(body: Any): ServerResponse =
        bodyValue(body).awaitSingle()
```
See https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/kotlin/org/springframework/web/reactive/function/server/ServerResponseExtensions.kt#L62

Therefore, in https://github.com/spring-projects/spring-hateoas/issues/1213 a more Spring conform name would be `toCollectionModelAndAwait` because _waiting_ is also part of the method.

Furthermore, another Kotlin extension function is useful:
```
suspend fun <T : Any> SimpleReactiveRepresentationModelAssembler<T>.toModelAndAwait(
    entity: T,
    exchange: ServerWebExchange,
): EntityModel<T> = toModel(entity, exchange).awaitSingle()
```

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/24a005abde0352ab6974c7734c3ed77585982e15.

Thanks @juergenzimmermann!
