### ISSUE TITLE
Should HalLinkRelation and StringLinkRelation not have compatible equals and hashCode ?

### ISSUE THREAD

**Issue by edrik** [spring-projects/spring-hateoas#1290]
Somehow you would expect all of these to return true:
```java
LinkRelation.of( "acme:foo" ).value().equals( HalLinkRelation.curied( "acme", "foo" ).value() );
LinkRelation.of( "acme:foo" ).equals( HalLinkRelation.curied( "acme", "foo" ) );
LinkRelation.of( "acme:foo" ).equals( HalLinkRelation.of( LinkRelation.of( "acme:foo" ) ) );
```
But now only the first one that compares the exact `String` value is considered equals. The `isSameAs()` method is usable to some degree but would not work if you collect link relations in a `HashMap<LinkRelation,T>` or use it to check if a relation already exists in a `Set<LinkRelation>`.

The general question here is if the `HalLinkRelation` should be considered something to build on, as part of the lib or just internal type for the HAL serialization?

Or is there some other recommended way to construct and maintain an applications HAL link relations similar to the `IanaLinkRelations` so that you can have custom more complex `RepresentationModel` types that manages HAL's `_embedded` construct in combination with `_links`.

This is also a mater of optimization because if you know that the type of link relation you are building is a `HalLinkRelation` style relations, doing the extra `HalLinkRelation.of(LinkRelation)` for every link relation when serializing things feels a bit redundant.

**Comment by gregturn** [comment]
With 1.1.0.BUILD-SNAPSHOT we have added a new HalModelBuilder. 

Check out https://docs.spring.io/spring-hateoas/docs/1.1.0.BUILD-SNAPSHOT/reference/html/#mediatypes.hal.models. 

As for doing equals and hashCode comparisons between two different implementations of LinkRelation, I’d be very careful. Generally in polymorphic design you can’t compare sibling types like that unless the parent (or you) has define explicit comparators given this is an implementation detail. 

In essence we need more information before we can declare what is comparable between different LinkRelation types. Given @odrotbohm knows more about CURIES than I I may have to defer to him as to what is “equal” when taking about such link relations.

**Comment by odrotbohm** [comment]
`LinkRelation.isSameAs(…)` case insensitively compares the raw `String` values. There's nothing we can do about the `equals(…)` semantics as different implementations might carry additional semantics that prevent the equals comparison from being symmetric.

To your second example: the things you're comparing are not the same things. To a simple link relation that doesn't know anything about curies, `acme:foo` is an opaque string. If equals returned `true` for that case, e.g. a `HashMap`would potentially replace the latter with the former and drop significant information.

**Comment by edrik** [comment]
Yes, the reason why this cant really be done is quite obvious, and exactly the type of problems you encounter now if you try to use the `LinkRelation` interface type in your application code.
If you use anything else than the `StringLinkRelation` as a concrete implementation, things become quite unpredictable. You could easily have multiple code paths add seemingly the same link relation, but end up with the same thing added several times.

The `HalModelBuilder` looks promising, think the the "preview" concept is what I'm looking for 👍

Before upgrading to Spring HATEOAS 1.x.x and the shift to `LinkRelation` I resorted to having a abstract `Resource extends ResourceSupport` type that internally maintained a multimap with `String` relation as key and anything extending the `Resource` as value. Then remapped that to a `Map<String,Object>` type for proper `_embedded` json.

Now trying to refactor this to better utilize new concepts things didn't add up if I just changed `String` to `LinkRelation`. That's why I started to think that there must be some other way to build more complex HAL Resources, where you can model the recursive nature of `_embedded` with arbitrary relations. All i could find was the `CollectionModel` wrapping that looks to limited to one contained type.

The use-case here is a facade that hides quite complex business logic where there is not just one wrapped type per resource/model, and things don't always get linked to with the same relation in every context. So there is a need to define the relation for `_embedded` items inline on demand.

**Comment by edrik** [comment]
Think this can be closed with the conclusion that you should not use anything else than the `StringLinkRelation` via `LinkRelation.of(String)` as a concrete implementation in your application code?
