### ISSUE TITLE
The SPI for media types needs to reflect it's ONLY for internal usage.

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#1304]
On gitter, @toedter reported having an issue registering his custom mediatype for JSON:API.

Turns out, the problem was that when loading a provider from `spring.factories`, Spring HATEOAS filters against the list of media types registered via `@EnableHypermediaSupport`. Further digging shows that we don't actually have any tests exercising a custom media type loaded from `spring.factories`.

**Comment by odrotbohm** [comment]
I don't actually think, we need a fix for that but in the documentation. The `spring.factories` approach is just necessary for the media types that we ship support for OTTB. For custom media types, registering the `HypermediaMappingInformation` as bean should be sufficient to get activated. IIRC the reference docs were just wrongly suggesting `spring.factories` is needed.

**Comment by odrotbohm** [comment]
- [ ] Remove section on `MediaTypeConfigurationProvider` from the [reference documentation](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#mediatypes.custom.configuration).
- [ ] Update Javadoc of `MediaTypeConfigurationProvider` to note that this is not needed for a custom media type implementation but rather an internal artifact

**Comment by gregturn** [comment]
Resolved via 4720e563.

**Comment by toedter** [comment]
I am currently trying....
