### ISSUE TITLE
Cannot parse spring hateoas response

### ISSUE THREAD

**Issue by kucw** [spring-projects/spring-hateoas#1306]
Hi Spring Hateoas team,

I'm fairly new to spring hateoas and I encounter some problem while parsing the response generated by spring hateoas.

I'm using Spring Boot 2.2.4.RELEASE with Spring Hateoas 1.1.0.RELEASE and below is the detail of my code.

First, I create a StudentResponse to extend the RepresentationModel
```java
public class StudentResponse extends RepresentationModel<StudentResponse> {
    private Integer studentId;
    // ignore getter/setter
}
```

And then I try to add some hateoas links on student endpoint
```java
@RestController
public class StudentController {

    @RequestMapping("/student/{studentId}")
    public ResponseEntity<StudentResponse> getStudent(@PathVariable Integer studentId) {
        // initialize object
        StudentResponse studentResponse = new StudentResponse();
        studentResponse.setStudentId(studentId);

         // add hateoas self link
        studentResponse.add(linkTo(methodOn(StudentController.class)
               .getStudent(studentId)).withSelfRel());

        // return
        return new ResponseEntity<>(studentResponse, HttpStatus.OK);
    }
}
```

And the json response would be
```json
{
    "studentId": 1,
    "_links": [
        {
            "rel": "self",
            "href": "http://localhost:8080/student/1"
        }
    ]
}
```

Spring hateoas works fine till now. But if I try to parse the json response on the other endpoint, it will throw a `UnrecognizedPropertyException`
```java
@RequestMapping("/parst")
public ResponseEntity<?> print(@RequestBody String json) throws Exception {
    ObjectMapper objectMapper = new ObjectMapper();

    // try to transform json string to StudentResponse object, but failed. This line will throw an exception
    StudentResponse studentResponse = objectMapper.readValue(json, StudentResponse.class);

    return ResponseEntity.ok().build();
}
```

And the detail of the exception would be
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "_links" (class com.demo.StudentResponse), not marked as ignorable (2 known properties: "studentId", "links"])
 at [Source: (String)"{"studentId":1,"_links":[{"rel":"self","href":"http://localhost:8080/student/1"}]}"; 
```

Could you please tell me that which part I did wrong? Really appreciate for your time and your help.

**Comment by gregturn** [comment]
The problem is your instance of `ObjectMapper`. It doesn't speak "HAL", and hence doesn't know how to deserialize the JSON provided to it.

https://docs.spring.io/spring-hateoas/docs/1.1.0.RELEASE/reference/html/#client shows the baked on client-side support we provide. To be honest, `ObjectMapper` is a bit low level. Most people are usually invoking a hypermedia-powered from something like `WebClient` or `RestTemplate`.

Our support for those tools will configure the right message converters.

To use `ObjectMapper` directly, you have to register the HAL Jackson handlers yourself.

Though I'd advise against it, you can also do this: https://github.com/spring-projects/spring-hateoas/blob/17644464d999a52de3a1872612df556097ad58b3/src/test/java/org/springframework/hateoas/mediatype/hal/HalTestUtils.java#L51-L65

**Comment by kucw** [comment]
Hi @gregturn, thanks for quick reply. The `ObjectMapper` setting in HalTestUtils really helps me a lot!

Also, I agree it would be better to use `WebClient` or `RestTemplate` to do the endpoint call between micro services. But the reason I need to use `ObjectMapper` is that I hope to integrate Spring Hateoas with Rest-assured unit test framework.

Rest-assured uses default `ObjectMapper` to transform the response string to POJO and it will throw `UnrecognizedPropertyException` while processing that. The only solution is to provide a custom `ObjectMapper` for rest-assured to my understanding.

Btw, here are the test cases I write, and it works after I added the `ObjectMapper` setting based on HalTestUtils. Many thanks for your support!
```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = HateoasDemoApplication.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class StudentControllerTest {

    @Value("${local.server.port}")
    protected int serverPort;

    @Before
    public void init() {
        RestAssured.port = serverPort;

        // customize ObjectMapper in Rest-assured
        RestAssured.config = RestAssuredConfig.config().objectMapperConfig(
                new ObjectMapperConfig().jackson2ObjectMapperFactory(
                        new DefaultJackson2ObjectMapperFactory() {
                            @Override
                            public ObjectMapper create(Type cls, String charset) {
                                return HalTestUtils.halObjectMapper();
                            }
                        }
                ));
    }

    @Test
    public void parseStudentResponse() {
        String selfLink = given()
                .contentType(ContentType.JSON)
                .when()
                .get("/student/1")
                .then()
                .extract()
                .as(StudentResponse.class)
                .getLink("self").get().getHref();

        System.out.println(selfLink);
    }
}
```

**Comment by gregturn** [comment]
Great!

**Comment by onacit** [comment]
How can I parse, with the `halObjectMapper()` from the whole JSON string of `PagedModel<Some>`?

I tried.

```java
        if (true) {
            final var value = objectMapper.readValue(content, new TypeReference<PagedModel<T>>() {
            });
            return value;
        }
        if (false) {
            final var value = objectMapper.readValue(content, new TypeReference<PagedModel<T>>() {
                @Override
                public Type getType() {
                    return new TypeReferences.PagedModelType<T>().getType();
                }
            });
            return (PagedModel<T>) value;
        }
```

and had no luck.
