### ISSUE TITLE
Link uses Lomboks @Getter(onMethod)

### ISSUE THREAD

**Issue by thiotes** [spring-projects/spring-hateoas#1311]
I was wondering why our Swagger page describes Link as an object without properties, and i think it may be because of this annotation:

@Getter(onMethod = @__(@JsonProperty))

the usage here is, according to lombok documentation, for java version 7. We are using version 11 currently, which means the annotation likely isn't added to the getter. 

Generally i think it is probably a bad idea to use such version-specific annotations in a library, and just wanted to inform you.

**Comment by odrotbohm** [comment]
While what's stated in the docs probably was true at some point, can you qualify "isn't likely added" a bit more? I have quite a few Java 8 projects using the `@__` syntax an they all actually add the configured annotation to the getter properly.

**Comment by thiotes** [comment]
I didn't get any fields for the type Link in Swagger, looked around a bit, and thought this might be the issue. I wasn't sure of it though. I have found no way to actually look at the "resulting" code when it comes to lombok annotations.

By now, after some more experimentation, it seems that specific problem is caused because Links is an Iterable of Link, which isn't properly handled, rather than missing annotations. If you create, say, a List of Link, the properties will be available.
