### ISSUE TITLE
HalLinkRelation incorrectly parses relation sources with more than one colon in them

### ISSUE THREAD

**Issue by edrik** [spring-projects/spring-hateoas#1314]
Take a link relation like `"urn:ietf:rfc"` or `"http://example.com/?test=foo:bar"` you would expect to see `_links` with that exact relation.

Instead you get `"urn:ietf"` and `"http://example.com/?test=foo"`, basically `HalLinkRelation` splits on all `:` and only treats the second item as the local part and discards the rest.

https://github.com/spring-projects/spring-hateoas/blob/f3198b7d79ecfdde8957f19c8ddf99f526cc63d4/src/main/java/org/springframework/hateoas/mediatype/hal/HalLinkRelation.java#L81

Using `HalLinkRelation.uncuried()` works but as noted in #1290, using anything else than `LinkRelation.of()` in your code cant be recommended.

   -Fredrik

**Comment by gregturn** [comment]
I'm really unfamiliar with link relations like `urn:ietf:rfc`, especially in light of curied links.

I'll have to see what @odrotbohm thinks.

**Comment by edrik** [comment]
> I'm really unfamiliar with link relations like `urn:ietf:rfc`, especially in light of curied links.

That was only a random example of a namespaced `urn` type  `URI`. Not that relevant actually what the relation is. Because I can't really find what specification would dictate that you cant use any valid URI as relation. Considering that the usage of curied links is optional for hal+json.

   -Fredrik

**Comment by odrotbohm** [comment]
That's fixed. We now also verify the curie candidates to not be registered IANA URI schemes.
