### ISSUE TITLE
List community media type implementations in the reference docs

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-hateoas#1337]
- @toedter's implementation of [JSON:API](https://github.com/toedter/spring-hateoas-jsonapi)
- @ingogriebsch's implementation of [SIREN](https://github.com/ingogriebsch/spring-hateoas-siren)

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/b4ce7283a5aa6bfe0bfe730c574e60a60ae6a61b.
