### ISSUE TITLE
How to custom Wrapped Responses which wrap RepresentationModel?

### ISSUE THREAD

**Issue by lmtoo** [spring-projects/spring-hateoas#1346]
RESTful Service Best Practices has a Wrapped Responses section , which introduce  so-called JSEND response. 
and responses has with the following properties:

> • code – contains the HTTP response status code as an integer.
• status – contains the text: “success”, “fail”, or “error”. Where “fail” is for HTTP status response values from 500-599, “error” is for statuses 400-499, and “success” is for everything else (e.g. 1XX, 2XX and 3XX responses).
• message – only used for “fail” and “error” statuses to contain the error message. For internationalization (i18n) purposes, this could contain a message number or code, either alone or contained within delimiters.
• data – that contains the response body. In the case of “error” or “fail” statuses, this contains the cause, or exception name.

data should be the RepresentationModel.

for example:

the original response 

`{
    "id": 1,
    "name": "Steven Spielberg",
    "_embedded": {
        "movieList": [
            {
                "id": "1",
                "title": "ET"
            },
            {
                "id": "2",
                "title": "Jaws"
            }
        ]
    }
}`

if we enabled JSEND response , then the response should be:
`
{
    "code": 200,
    "message": "success",
    "data": {
        "id": 1,
        "name": "Steven Spielberg",
        "_embedded": {
            "movieList": [
                {
                    "id": "1",
                    "title": "ET"
                },
                {
                    "id": "2",
                    "title": "Jaws"
                }
            ]
        }
    }
}
`
wrapper class can be provided by developer

**Comment by odrotbohm** [comment]
> RESTful Service Best Practices has a Wrapped Responses section , which introduce so-called JSEND response.

Can you please clarify? What do you actually refer to and what has this to do with Spring HATEOAS?

**Comment by lmtoo** [comment]
It's here https://github.com/tfredrich/RestApiTutorial.com/tree/master/media
I just want to know how to wrap application/hal+json to a WrapperResponse before send to response.
WrapperResponse like this:

`
public class WrapperResponse<T> {
    
    private int code;
 
    private String msg;
 
    private Boolean success;
 
    private T data;

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Boolean getSuccess() {
        return success;
    }

    public void setSuccess(Boolean success) {
        this.success = success;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }

    public static <T> WrapperResponse<T> success(T data) {
        WrapperResponse<T> result = new WrapperResponse<T>();
        result.setSuccess(true);
        result.setCode(HttpStatus.OK.value());
        result.setMsg("success");
        result.setData(data);
        return result;
    }
}
`

**Comment by odrotbohm** [comment]
First of all, this is a bug tracker. Please don't use this for general questions. Rather post on StackOverflow for those.

That recommendation in the linked document looks pretty weird as it is at odds with a lot of REST principles (why would you reencode the status code into the body? It's already part of the response.) Also, mind that we cannot support every proprietary format advertised some company. There actually is [an RFC](https://tools.ietf.org/html/rfc7807) to describe errors and there's built in support for that in Spring HATEOAS.
