### ISSUE TITLE
Resources with one only item in Collection

### ISSUE THREAD

**Issue by SirMaster** [spring-projects/spring-hateoas#135]
Hi,

We found that when we have a class the extends org.springframework.hateoas.Resources that when we provide a collection with multiple items the output gets generated as so, when making a call to **/users** :

```
{
    "_links": {
        "self": {
            "href": "/users"
        }
    },
    "_embedded": {
        "userList": [
            {
                "_links": {
                    "self": {
                        "href": "/user/1"
                    }
                },
                "id": "1",
                "name": "bob"

            },
            {
                "_links": {
                    "self": {
                        "href": "/user/2"
                    }
                },
                "id": "1",
                "name": "fred"

            }
        ]
    },
    "count": 2
}
```

But if the collection only has one item in it, it outputs like so :

```
{
    "_links": {
        "self": {
            "href": "/users"
        }
    },
    "_embedded": {
        "user": {
            "_links": {
                "self": {
                    "href": "/user/1"
                }
            },
            "id": "1",
            "name": "bob"    
        }
    },
    "count": 1
}
```

Apparent from the above is for the same call to **/users** the output signature changes from and _embedded object having an array that contains users to and _embedded object that contains user object.

The code that does that is [here in the HalEmbeddedBuilder](https://github.com/spring-projects/spring-hateoas/blob/5c737d4b5311a2dfcee9cf580e98a5b9a2383e84/src/main/java/org/springframework/hateoas/hal/HalEmbeddedBuilder.java#L57)

My question is, was this done intentionally? Meaning was this done according to the HAL rules (I looked online but did see anything to lead me believe it is) or is this a small bug?

We are using build 0.9.0

M.

**Comment by axbarchuk** [comment]
@olivergierke Hi, could you help me pls. I try to use HAL spec., but I need to define _embedded with single resource, how can I do that now? Thanks.

Like that:
```
{
    "_links": {
        "self": {
            "href": "/users"
        }
    },
    "_embedded": {
        "user": {
            "_links": {
                "self": {
                    "href": "/user/1"
                }
            },
            "id": "1",
            "name": "bob"    
        }
    },
    "count": 1
}
```

**Comment by gregturn** [comment]
This issue has been closed for three years. If you have a new issue please open a new ticket.
