### ISSUE TITLE
Update links to JSON:API documentation (community based media types)

### ISSUE THREAD

**Issue by toedter** [spring-projects/spring-hateoas#1358]
I had to restructure the JSON:API for Spring HATEOAS documentation, since I now publish documentation for all released versions as well as the current snapshot on the same gh-pages branch.

The new links for the (always) latest release are:
Reference Docs: https://toedter.github.io/spring-hateoas-jsonapi/release/reference/index.html
API Docs: https://toedter.github.io/spring-hateoas-jsonapi/release/api/index.html

The new links for the current snapshot version are:
Reference Docs: https://toedter.github.io/spring-hateoas-jsonapi/snapshot/reference/index.html
API Docs: https://toedter.github.io/spring-hateoas-jsonapi/snapshot/api/index.html

You could either link to the latest released version, or to both, released and snapshot.
I did not submit a pull request since it is your decision on what and how you link.

Probably a table  would be nice (ignore empty header since GitHub cannot render Markdown tables without header), like

| |  |  |
| --- | --- | --- |
| Latest Release | [Reference Docs.](https://toedter.github.io/spring-hateoas-jsonapi/release/reference/index.html) | [API Docs.](https://toedter.github.io/spring-hateoas-jsonapi/release/api/index.html) |
| Current Snapshot | [Reference Docs.](https://toedter.github.io/spring-hateoas-jsonapi/snapshot/reference/index.html) | [API Docs.](https://toedter.github.io/spring-hateoas-jsonapi/snapshot/api/index.html) |

Thx

Kai

**Comment by gregturn** [comment]
Thanks @toedter !

**Comment by toedter** [comment]
That was quick! Thx @gregturn.
