### ISSUE TITLE
RepresentationModelProcessor<CollectionModel<CustomModel>> didn't come into effect when CustomModel directly inherit from RepresentationModel 

### ISSUE THREAD

**Issue by lmtoo** [spring-projects/spring-hateoas#1362]
I have a class ProjectNodeModel which subclass from RepresentationModel , but when I defined a bean RepresentationModelProcessor<CollectionModel<ProjectNodeModel>> in Configuration , this bean didn't come into effect,
I look into org.springframework.hateoas.server.mvc.RepresentationModelProcessorInvoker.CollectionModelProcessorWrapper#isValueTypeMatch , which doesn't cover this situation

**Comment by odrotbohm** [comment]
Sounds like a duplicate of #1425. Would you mind trying the latest releases to verify whether this is fixed in those?
