### ISSUE TITLE
Regression in DummyInvocationUtils when calling MethodInvocation.getMethod() in version 1.0.5.

### ISSUE THREAD

**Issue by rogozinds** [spring-projects/spring-hateoas#1376]
We start to get an exception when updated from version 1.0.1.RELEASE to 1.0.5.RELEASE of spring-hateoas dependency.

> Exception in thread "main" org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class java.lang.reflect.Method: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class java.lang.reflect.Method
> 	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:208)

This is the complete minimal example, that works with 1.0.1 and raises the exception with 1.0.5:

```java
public class MainDummyReflection {

    public static void main(String ... args) throws NoSuchMethodException {
        DummyController obj = DummyInvocationUtils.methodOn(DummyController.class);
        Object invocationValue = obj.getCity(null, null);
        Assert.isInstanceOf(LastInvocationAware.class, invocationValue);
        LastInvocationAware invocations = (LastInvocationAware) invocationValue;
        MethodInvocation invocation = invocations.getLastInvocation();
        //Exception here
        Method method = invocation.getMethod();
        AnnotationMappingDiscoverer mappingDiscoverer = new AnnotationMappingDiscoverer(RequestMapping.class);
        String mapping = mappingDiscoverer.getMapping(DummyController.class, method);
        System.out.println(mapping);
    }

    @RequestMapping("/cities/")
    public class DummyController {
        @GetMapping(path = "/{countryId}/cities/{cityId}")
        public Object getCity(String countryId, String cityId) {
            return new Object();
        }
    }
}
```

**Comment by gregturn** [comment]
Why are you using internal utilities?

If you’re building links, you should use WebMvcLinkBuilder as shown in  https://docs.spring.io/spring-hateoas/docs/1.0.5.RELEASE/reference/html/#fundamentals.obtaining-links.builder.methods.

What you’re doing is replicating internal code and exposing yourself to unnecessary risk.

**Comment by rogozinds** [comment]
> Why are you using internal utilities?
How can I identify, that it is an 'internal utility', I'm using public methods from public classes from org.springframework.hateoas.server.core package? There are no comments that it is 'internal' or should not be used.

>What you’re doing is replicating internal code and exposing yourself to unnecessary risk.
I agree that using some reflection magic with proxies is not the best option, but this code was there before me and I can only guess the reasoning why it was implemented that way (and just a side note, this is a very simplified example, so in the real example, there are reasons to implement this).

The current situation is that after increasing the minor version of the library we get an error, so it looks like a regression. In case you think, that it's an internal class and fixing this issue doesn't have much customer value, I would suggest adding a comment to the class explaining this.

**Comment by nealeu** [comment]
I agree. I'm getting the same issue as @rogozinds, yet I'm getting it while using WebMvcLinkBuilder.  I'll try reverting to 1.0.1 to see if it avoids the problem for us.

**Comment by odrotbohm** [comment]
The `ìnvocationValue` you obtain, is a proxy itself, so that `….getLastInvocations()` on it will be routed through the proxy again and thus record that call and try to proxy the result in turn. Which of course doesn't work. If you want to obtain the `LastInvocationAware` instance for such an original proxy, use `DummyInvocationUtils.getLastInvocationAware(…)`.

Please assume that classes not described in the reference documentation are internal. There's hardly a way to properly describe that otherwise as we need that type to be public to be able to refer to it from other packages. Again, `DummyInvocationUtils` is not intended for public usage. Or, to phrase it differently: we don't guarantee anything about it. API, functionality, nothing.

**Comment by nealeu** [comment]
Thanks for the help @odrotbohm.

I get there are no guarantees, but sometimes there are also no alternatives :-)

Your suggestion did the trick.
