### ISSUE TITLE
[Question] Is there a class that is a container for _embedded?

### ISSUE THREAD

**Issue by nareshbhatia** [spring-projects/spring-hateoas#1378]
I am just getting started with spring-hateoas. I see that `RepresentationModel` is a container for links. Is there a similar container for `_embedded`?

**Comment by odrotbohm** [comment]
Please have a look at `HalModelBuilder` for dedicated control over embedded objects. In general please rather use StackOverflow for questions. Thanks!

**Comment by nareshbhatia** [comment]
Thank you, @odrotbohm. Will use SO in the future.
