### ISSUE TITLE
Create an ObjectMapperCustomizer to allow tailoring ObjectMapper through media types configuration

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#1382]
Create a hook for users to customize the `ObjectMapper` created in the serializer, like this:

```java
public interface ObjectMapperCustomizer extends Consumer<ObjectMapper> {
}
```

Then, `HalConfiguration` could add `withObjectMapperCustomizer(ObjectMapperCustomizer)`, allowing users to supply a lambda function. 

`Jackson2HalModule` can then leverage `halConfiguration.getObjectMapperCustomizer.accept(mapper)` after getting or creating the `ObjectMapper`.

**Comment by toedter** [comment]
Seem like a great idea, I will try this out.

**Comment by gregturn** [comment]
Actually, your suggestion makes sense. I was away from my IDE and couldn't remember if a concrete interface was needed or not. Clearly not.
