### ISSUE TITLE
EntityModel<String> no longer writable

### ISSUE THREAD

**Issue by Gwaptiva** [spring-projects/spring-hateoas#1396]
I have a GET method that returns a `ResponseEntity` with the body set to an `EntityModel<String>` instance.
The content of the `EntityModel` instance is an empty string (but the issue below is the same for a non-empty string), and the EntityModel has a few `Link`s added.

Using HATEOAS 1.1.0.RELEASE (and before), my test returns a JSON object with status 200
When upgrading to 1.2.0 (and 1.2.1), the test returns a status 500 and log shows 

> 2020-11-11T11:21:29,999  WARN [main] (AbstractHandlerExceptionResolver.java:207) - Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Can not write a string, expecting field name (context: Object); nested exception is com.fasterxml.jackson.core.JsonGenerationException: Can not write a string, expecting field name (context: Object)]

All other libraries the same (Spring 5.3.1, Jjackson 2.11.3).
All regression tests that use `EntityModel`s of `Serializable` objects work as expected and as before.

Is this a bug? Or is this intended behaviour?

**Comment by XhstormR** [comment]
I have same  issues

**Comment by XhstormR** [comment]
1.1.1.RELEASE work
1.1.2.RELEASE not work

**Comment by dcominottim** [comment]
Seems to be the case of https://github.com/spring-projects/spring-data-rest/issues/1926.

**Comment by odrotbohm** [comment]
As indicated in #1371, it doesn't make sense to use `EntityModel` with scalar values. The fix for #1371 now explicitly rejects that. There was an upstream [bug in Spring Data REST](spring-projects/spring-data-rest#1926) that erroneously wrapped scalars into `EntityModel` in the first place which has been resolved as well. Closing as duplicate.
