### ISSUE TITLE
How to replace underscore in generated HAL entities

### ISSUE THREAD

**Issue by ericjalal** [spring-projects/spring-hateoas#1401]
Hello,

We have recently uplifted our HATEOAS library for APIs and because of a client issue we need to replace the underscore "_" in for example "_links" with a keyword like "hal" so it will look like "hallinks". Previously for a couple of years we were using a custom implementation by using `ResponseBodyAdvice<Object>` interface and the `beforeBodyWrite` interface. But now it doesn't work anymore after uplift to latest version. is there any clear reason why it doesn't happen or a solution how can we achieve this again?

Thanks

**Comment by gregturn** [comment]
I’m not sure why a framework that renders spec compliant HAL needs to support rendering non compliant HAL. 

If you need another format, safest thing is to code your own and register via our SPI for custom media types.
