### ISSUE TITLE
Snapshots published to Maven Central

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-hateoas#1422]
I got notified by [artifact listener](https://www.artifact-listener.org/) the other day that some Spring HATEOAS unstable/snapshot releases were published to Maven Central.

I suspect this wasn't intended and is likely related to #1417 so just a heads-up.

![Screenshot from 2020-12-21 08-11-24](https://user-images.githubusercontent.com/1149230/102749805-f0c27b00-4364-11eb-921b-c2899704043e.png)

**Comment by gregturn** [comment]
This was my method to verify things. That’s why they are all prefixed “0.0.0”. 

But yes, this is only used for releases, not snapshots, milestones or RCs.

**Comment by vpavic** [comment]
I see. That `0.0.0.` prefix did suggest it was a test, but I wasn't aware the intent was to publish to the Central.
I'll close this then, thanks for the feedback @gregturn and sorry for the noise. :slightly_smiling_face:
