### ISSUE TITLE
RepresentationModelProcessor not invoked for PagedModel / CollectionModel consisting of RepresentationModels

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-hateoas#1425]
**[koehnj](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50828)** opened **[DATAREST-1593](https://jira.spring.io/browse/DATAREST-1593?redirect=false)** and commented

The **isValueTypeMatch** method of

`org.springframework.hateoas.server.mvc.RepresentationModelProcessorInvoker.CollectionModelProcessorWrapper`

only checks if an element of the CollectionModel is either an instance of EntityModel or an instance of EmbeddedWrapper. It doesn't cover the fact that an element can also be an instance of RepresentationModel.

 

```java
if (element instanceof EntityModel) {
     return EntityModelProcessorWrapper.isValueTypeMatch((EntityModel<?>) element, resourceType);
} else if (element instanceof EmbeddedWrapper) {
     return isRawTypeAssignable(resourceType, ((EmbeddedWrapper) element).getRelTargetType());
}
```

 

Therefore the **isValueTypeMatch** method will evaluate to false which also causes the **supports** method to evaluate to false, hence the RepresentationModelProcessor will not be invoked

---

**Reference URL:** https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/server/mvc/RepresentationModelProcessorInvoker.java

**Comment by odrotbohm** [comment]
I've migrated the issue to the Spring HATEOAS bug tracker in which the relevant component lives. Any chance you can create a test case reproducing the error?

**Comment by koehnj** [comment]
```java

@Test // #1425
void doesInvokeProcessorForCollectionModelOfRepresentationModel() {

	CollectionModelOfGenericModelProcessor processor = new CollectionModelOfGenericModelProcessor();

	RepresentationModelProcessorInvoker invoker = new RepresentationModelProcessorInvoker(
			singletonList(processor));

	GenericModel<?> model = new GenericModel<>();

	invoker.invokeProcessorsFor(CollectionModel.of(singletonList(model)));

	assertThat(processor.invoked).isTrue();
}

static class GenericModel<T extends RepresentationModel<T>> extends RepresentationModel<T> {}

// 1425
static class CollectionModelOfGenericModelProcessor implements RepresentationModelProcessor<CollectionModel<GenericModel<?>>> {

	boolean invoked = false;

	@Override
	public CollectionModel<GenericModel<?>> process(CollectionModel<GenericModel<?>> model) {

		invoked = true;

		return model;
	}
}

```

Originally I added the test case to the already existing [test class](https://github.com/spring-projects/spring-hateoas/blob/master/src/test/java/org/springframework/hateoas/server/mvc/RepresentationModelProcessorInvokerUnitTests.java). Thats where the GenericModel comes from. Hopefully it's reasonable enough. Please let me know what you think. If you want i can provide additional test cases for the isValueTypeMatch and the supports method.

**Comment by odrotbohm** [comment]
If you're already at it, feel free to submit the stuff you can provide as PRs, even if it's just failing test. I can then take it from there. Thanks a lot already!

**Comment by koehnj** [comment]
Sorry for asking but did this work as expected?

**Comment by odrotbohm** [comment]
That's fixed for and back-ported to 1.2.x in #1431.

**Comment by koehnj** [comment]
Sounds great. Thanks a lot.

**Comment by onacit** [comment]
@odrotbohm Hi. My apologies. My restricted knowledges make me put question here. 

I have an entity whose transitive ancestor extends `EntityModel`.

I'm trying to test Spring Data Rest repositories using abstract class hierarchy.

```java
abstract class MyRepositoryTest<T extends MyRepository<U, V>, U extends MyEntity<U, V>, V> {
    final Class<T> repositoryClass;
    final Class<U> entityClass;
    final Class<V> idClass;

    @Test
    void readCollection1() throws Exception {
        final var uri = baseUri().path(collectionResourceRel()).build().toUri();
        final var responseType = new ParameterizedTypeReference<PagedModel<U>>() {
        };
        final var responseEntity = restTemplate.exchange(uri, HttpMethod.GET, HttpEntity.EMPTY, responseType);
        final var body = responseEntity.getBody();
    }
}
```

The method fails with,
```
2023-02-10T15:58:14.288+09:00  INFO 24814 --- [o-auto-1-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-02-10T15:58:14.288+09:00  INFO 24814 --- [o-auto-1-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-02-10T15:58:14.289+09:00  INFO 24814 --- [o-auto-1-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms

Type definition error: [simple type, class com.....data.jpa.domain._Mapped]
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class com.....data.jpa.domain._Mapped]
```

The `_Mapped` is my root ancestor of the entity class.

When I tried the method in my concrete test class with concrete entity class, it works.

```java
    MyEntityTest() {
        super(MyEntityRepository.class, MyEntity.class, Long.class);
    }

    @Test
    void readCollection2() throws Exception {
        final URI uri = baseUri().path(collectionResourceRel()).build().toUri();
        final var responseType = new ParameterizedTypeReference<PagedModel<MyEntity>>() {
        };
        final var responseEntity = restTemplate().exchange(uri, HttpMethod.GET, HttpEntity.EMPTY, responseType);
        final var body = responseEntity.getBody();
    }
```

How can I use the **generic** test method for all concrete classes? Thanks.
