### ISSUE TITLE
How let ControllerLinkBuilder see original request URI?

### ISSUE THREAD

**Issue by andrewtswu** [spring-projects/spring-hateoas#143]
Hi,

Our tomcat server can only see internal URIs due to the way we setup our servers. If a client, for example, wants to get a list of events, the external URI is

```
http://api.mydomain.com/events
```

However, internally, tomcat sees

```
http://api.mydomain.com/servlet/events
```

which causes all self links to have similar pattern. For example

```
http://api.mydomain.com/servlet/events
http://api.mydomain.com/servlet/events/:id
```

Is there an easy way to customize ControllerLinkBuilder to re-write the URIs?

**Comment by nickgrealy** [comment]
Just wondering, would handling a `X-Forwarded-Path` header solve this issue? i.e.
https://github.com/nickgrealy/spring-hateoas/commit/d069038dbdc24e0f66e3d64fba57978914c9e70b

You could then automatically inject the headers as part of your application filters... e.g.
https://gist.github.com/nickgrealy/b4a582c8e1c411c5396d#file-application-java-L18-L24

I haven't committed to this project before, so let me know if I can go ahead and submit a pull request (do you want the HeaderOverrideFilter.java from the example included too?).

@aleksz - re: not working for POST - that sounds like a separate issue to this

**Comment by olivergierke** [comment]
`ControllerLinkBuilder` already supports well-defined proxy server headers, so it's basically up to you making sure your proxy server sets those appropriately.

**Comment by otrosien** [comment]
Should be obsolete now. Current master is delegating this to UriComponentsBuilder, which is also base-path aware. (use `X-Forwarded-Prefix` header. see also https://jira.spring.io/browse/SPR-12500)

**Comment by gregturn** [comment]
Closed since we observe standard headers as well as support relative links as well.
