### ISSUE TITLE
linkTo and methodOn with custom RequestMappingHandlerMapping

### ISSUE THREAD

**Issue by benneq** [spring-projects/spring-hateoas#144]
I just wanted to implement/use Spring Hateoas, but I've got a problem:

I've got a custom RequestMappingHandlerMapping registered in WebMvcConfigurationSupport, which scans all Controllers for an additional annotation (@ApiVersion) in order to build custom URLs like: /v1/users if the Controller ist annotated with @RequestMapping("users") @ApiVersion(1).

Is it possible to modify Spring Hateoas to use the registered RequestMappingHandlerMapping in order to construct URLs using linkTo and methodOn?

**Comment by odrotbohm** [comment]
Duplicates #118.
