### ISSUE TITLE
Unable to proxy interface-implementing method on Mono.subscribe() 

### ISSUE THREAD

**Issue by namila007** [spring-projects/spring-hateoas#1448]
Hi, I'm using Spring hateos (2.3.5.Release) on Spring boot reactive stack. Here I'm getting following Info log once I request some resources (FIRST time only) 
```
[boundedElastic-1] INFO  o.s.aop.framework.CglibAopProxy - [] - Unable to proxy interface-implementing method [public final void reactor.core.publisher.Mono.subscribe(org.reactivestreams.Subscriber)] because it is marked as final: Consider using interface-based JDK proxies instead!
```

My controller >  (ps: `modelX` is a autowired model class)

```
 @GetMapping
  public Mono<EntityModel<ModelX>> health() {
    return Mono.defer(() -> Mono.just(modelX)).flatMap(modelX1-> linkTo(
        methodOn(HealthController.class).health()).withSelfRel().toMono()
        .map(link -> modelX1.removeLinks().add(link))).subscribeOn(Schedulers.boundedElastic());
  }
```

On here I observed that this happened for once (only on the first request for this endpoint) and this logger is printed when this ``methodOn(HealthController.class).health()`` method is invoked. Here I'm using ``org.springframework.hateoas.server.reactive.WebFluxLinkBuilder.*`` lib

**Comment by odrotbohm** [comment]
Do you have a sample project to reproduce this? What makes you think this is caused by HATEOAS? I am asking, because proxying applied by the dummy method invocation is actually proxying the declared method return type, i.e. a `Mono` here, not the actual value returned. Plus, the method is never really invoked. Only its invocation is recorded, which makes me think that this might be caused by something else.

**Comment by namila007** [comment]
I can't remember the actual cause now, as i remember, it happens if you invoke the method for the first time. I was using Springboot 2.3.5

**Comment by namila007** [comment]
check this sample https://github.com/namila007/sample-spring-hateos-reactive

**Comment by odrotbohm** [comment]
I just checked the sample. It's not the type that the output complains, but the `Mono.subscribe(…)` method, which is declared final. It shouldn't be a problem, as we never actually even call any of the methods on the proxy anyway. I'll take the issue back to the reactor team for further discussion. If you're not calling those methods from anywhere else but the controller, declaring `Publisher` should allow you to get rid of this, too.

**Comment by odrotbohm** [comment]
This is being taken care of by spring-projects/spring-framework#27439 and #1647.
