### ISSUE TITLE
API doc  says "curieProvider can be null" but it is required

### ISSUE THREAD

**Issue by andreaskanzlers5555** [spring-projects/spring-hateoas#1449]
API Documentation of
`org.springframework.hateoas.mediatype.hal.Jackson2HalModule.HalHandlerInstantiator`
states that in the constructor
"curieProvider - can be null."
(https://docs.spring.io/spring-hateoas/docs/1.2.3/api/)

But source code requires it.

**Comment by odrotbohm** [comment]
This has been corrected with #1447 for 1.3 already. I'll make sure, we're gonna have the Javadoc corrected for 1.2.x as well.
