### ISSUE TITLE
Multiple template variables using regular expression break link creation

### ISSUE THREAD

**Issue by jenny1976** [spring-projects/spring-hateoas#1450]
spring-boot 2.4.2, spring-hateoas 1.2.3

Since the current spring-boot update (see above) the link building via WebMvcLinkBuilder produces broken urls when the request mapping contains regular expressions in PathVariables. I could reproduce this issue with a mapping example from spring-docs:

Here's a snippet from my DemoController.java
```java
@GetMapping("/spring-web/{symbolicName:[a-z-]+}-{version:\\d\\.\\d\\.\\d}{extension:\\.[a-z]+}")
public ModelAndView handle(@PathVariable String symbolicName, @PathVariable String version, @PathVariable String extension) {
    return new ModelAndView();
}
```

and a unittest that shows the current bug:
```java
@Test
void aSpringDocExampleThatIsBroken() {
    WebMvcLinkBuilder linkBuilder = linkTo(methodOn(DemoController.class).handle("artifact", "1.1.1",".jar"));

    String url = linkBuilder.withSelfRel().getTemplate().expand().toString();

    // fails
    assertThat(url).isEqualTo("http://localhost/spring-web/artifact-1.1.1.jar");
    // the result is http://localhost/spring-web/artifact
}
```

I tested this bug in different variations. It's always the first PathVariable with a regular expression, that is evaluated correctly
but the following PathVars are ignored then and the url gets cut.

**Comment by odrotbohm** [comment]
Likely to be a side effect of the fix for #1413. Looking into it. One thing: you say "since the current Boot upgrade" which seems to imply that the expansion had properly worked before. #1413 was actually fixed because the regular expressions would not have been removed at all before. Can you confirm? You should be able to manually downgrade Spring HATEAOS to 1.2.2 by setting the `spring-hateoas.version` property to that version in your POM.

**Comment by odrotbohm** [comment]
Got it. The regex cleaning up the template variables was using a greedy capture and thus ate all but the first match. Fix coming in a bit.

**Comment by odrotbohm** [comment]
This is fixed and back-ported. Should be available in the latest snapshots.

**Comment by jenny1976** [comment]
thank you @odrotbohm for taking care so quickly! Helps us a ton 👍
