### ISSUE TITLE
JAXBException occurred : unable to marshal type "org.springframework.hateoas.Resource" as an element because it is not known to this context..

### ISSUE THREAD

**Issue by hungbang** [spring-projects/spring-hateoas#1487]
JAXBException occurred : unable to marshal type "org.springframework.hateoas.Resource" as an element because it is not known to this context..

- Spring boot 2
- cxf jaxb 
- Jersey
- Spring hateoas 0.16
- Request header:
Accept: application/json

**Comment by odrotbohm** [comment]
I looks like you're using an unmaintained version of Spring HATEOAS / Boot? Current supported versions are 1.2 and 1.1 of Spring HATEOAS and 2.3 / 2.4 of Spring Boot. Please upgrade to to these versions.

**Comment by hungbang** [comment]
@odrotbohm Thank you, I'll update the version of spring hateoas and hope it can be resolved.
