### ISSUE TITLE
AnnotatedParametersParameterAccessor uses DefaultFormattingConversionService

### ISSUE THREAD

**Issue by nickspacek** [spring-projects/spring-hateoas#149]
Unless I'm missing something, the use of DefaultFormattingConversionService means there is no way to support custom parameters in MVC Controllers using (for example) linkTo/methodOn. If I have a controller method like this:

```
@RequestMapping(/{vegetableId}
public void get(@PathVariable("vegetableId") Vegetable vegetable)
```

Then even if I register a custom Converter to convert the object to a string representation, the linkTo/methodOn won't work because the Converter isn't part of the DefaultFormattingConversionService. Shouldn't the AnnotatedParametersParameterAccessor be referencing a ConversionService from the ApplicationContext?

**Comment by odrotbohm** [comment]
Duplicates #118.
