### ISSUE TITLE
Spring for Android compatibility

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-hateoas#150]
I'm planning to use Spring HATEOAS to write a set of `*Resource` DTO classes to represent the resources in my REST API, and I'd like to be able to make these classes available for client programs. It appears that using them in full Java applications won't be a problem, but it would be very helpful to be able to reuse the DTOs in an Android client.

Right now it looks like Spring HATEOAS is coupled tightly enough with the main Spring Framework that such reuse isn't possible; would it be feasible to separate out the segments so that plain-vanilla `ResourceSupport` classes are usable on Android?

**Comment by jaredsburrows** [comment]
@kmbulebu You got this working with Android? You didn't need to add `"org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE"` or `"com.jayway.jsonpath:json-path:2.0.0"`?

**Comment by gregturn** [comment]
Targeting Android as a platform is not practical goal for Spring HATEOAS.

Building for that platform would imply another project, either using Spring HATEOAS or based on Spring HATEOAS. Or using suggested practics from the Android community, a platform we couldn't hope to sustain.
