### ISSUE TITLE
Feature Request: Support for JSON-LD and HYDRA media type

### ISSUE THREAD

**Issue by marcuslange** [spring-projects/spring-hateoas#1501]
JSON-LD: https://json-ld.org/
Hydra: https://www.hydra-cg.com/

**Comment by odrotbohm** [comment]
There's [an SPI](https://docs.spring.io/spring-hateoas/docs/1.3.x/reference/html/#mediatypes.custom) for third parties to add support for additional media types that [quite a few folks](https://docs.spring.io/spring-hateoas/docs/1.3.x/reference/html/#mediatypes.community) already make use of. We currently don't have any plans to extend the number of media types supported natively as maintaining them requires significant effort.

**Comment by RovoMe** [comment]
[hydra-java](https://github.com/dschulten/hydra-java) seems to add support for `spring-hateoas`
