### ISSUE TITLE
Gson support

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-hateoas#151]
I'm working on a project for which Gson seems to be a better fit than Jackson. I like the Spring HATEOAS `@EnableHypermediaSupport` tool, but it appears to assume Jackson and to add Jackson converters unconditionally. Is there a way (other than duplicating the functionality of `@EnableHypermediaSupport`) to get the other features without adding Jackson? If not, could this be added as a parameter on the annotation?

**Comment by totof3110** [comment]
+1. I have a project with a Gson message converter configured and HATEOAS resources don't get deserialized like with Jackson. :(

**Comment by rajeshkamal** [comment]
+1. It would be nice to have the Spring HATEOAS HAL working with Gson. We are also using Gson specifically for the Versioning support of the REST API models - https://sites.google.com/site/gson/gson-user-guide#TOC-Versioning-Support which is not something that is available with Jackson.

**Comment by jfourment** [comment]
+1 that. We are also really looking forward to be able to use gson

**Comment by jonpeterson** [comment]
@rajeshkamal For a while I've wanted a model versioning feature in Jackson, so I recently sat down and wrote one.

https://github.com/jonpeterson/jackson-module-model-versioning

**Comment by gregturn** [comment]
I'm marking this as 'unlikely' given at least 1/3 of the project is about hand rolled Jackson stuff to render hypermedia.

**Comment by taa-autorola-com** [comment]
We really need this as well, as we're also using Gson

**Comment by gregturn** [comment]
Since Spring HATEOAS is heavily built on top of Jackson, to code a Gson equivalent would really require another project.

At this point in time, I'm closing this issue. If anyone wants to start such a project, please let me know. I'd love to follow it.
