### ISSUE TITLE
Provide additional HtmlInputType's for checkbox, radio and file

### ISSUE THREAD

**Issue by ingogriebsch** [spring-projects/spring-hateoas#1523]
The custom Hypermedia implementation for [Siren](https://github.com/kevinswiber/siren#type-3) provides a [similar approach](https://github.com/ingogriebsch/spring-hateoas-siren/blob/master/src/main/java/de/ingogriebsch/spring/hateoas/siren/SirenActionFieldType.java) to deal with [html input types](https://html.spec.whatwg.org/#the-input-element) as Spring HATEOAS in version 1.3. 

To unify the approaches and to ease the usage for clients it would be really helpful if Spring HATEOAS could add HtmlInputType's for `datetime`, `checkbox`, `radio` and `file`.

Enhancing the `InputTypeFactory` to also handle these type's as much as possible would be the cream on the cake! :)

**Comment by odrotbohm** [comment]
That's certainly something we can explore. That said, this of course raises a couple of questions that I'd like to discuss in person. I'll ping you on Gitter. 🙃

**Comment by odrotbohm** [comment]
That's in place now, feel free to give the snapshots a spin.

**Comment by ingogriebsch** [comment]
Great! Many thanks, @odrotbohm ! :)
