### ISSUE TITLE
No properties in HAL-FORM _templates with SpringBoot

### ISSUE THREAD

**Issue by matthieu-vergne** [spring-projects/spring-hateoas#1526]
# Context

I try to implement a REST service with HATEOAS.
The complete code (reduced for investigating this bug) can be found [here](https://github.com/Sazaju/genshin/tree/bug-hal-form/genshin-service).

In a nutshell, I tried to follow the [documentation example](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#mediatypes.hal-forms.example).
I have a simple domain class:
```java
public class Product {
	public String name;
	public double price;
}
```
and a class to represent a partial update (PATCH):
```java
public class ProductPatch {
	public String newName;
	public Double newPrice;
}
```
I have both a GET and PATCH endpoints and I add the SELF link with an affordance to the PATCH:
```java
@GetMapping("/product")
@ResponseBody
public EntityModel<Product> getProduct() {
	Product product = getDefaultProduct();

	EntityModel<Product> model = EntityModel.of(product);
	ProductController controller = methodOn(ProductController.class);
	model.add(linkTo(controller.getProduct()).withRel(IanaLinkRelations.SELF)//
			.andAffordance(afford(controller.patchProduct(null))));

	return model;
}

@PatchMapping("/product")
@ResponseBody
public EntityModel<Product> patchProduct(@RequestBody ProductPatch patch) {
	Product product = getDefaultProduct();

	if (patch.newName != null) {
		product.name = patch.newName;
	}
	if (patch.newPrice != null) {
		product.price = patch.newPrice;
	}

	EntityModel<Product> model = EntityModel.of(product);
	ProductController controller = methodOn(ProductController.class);
	model.add(linkTo(controller.getProduct()).withRel(IanaLinkRelations.SELF)//
			.andAffordance(afford(controller.patchProduct(null))));

	return model;
}
```
When I get the product, here is the result:
```json
{
  "name": "my product",
  "price": 10,
  "_links": {
    "self": {
      "href": "http://localhost:8080/product"
    }
  },
  "_templates": {
    "default": {
      "method": "patch",
      "properties": []
    }
  }
}
```

I am using spring-boot-dependencies 2.4.5, which comes with spring-hateoas 1.2.5.
I also tried with enforcing spring-hateoas 1.3.0 but I obtained the same thing.

# Problem

The `_templates` is present with the right method (PATCH), which shows that the affordance has been set up.
But the properties list remains empty.

The documentation example tells that we should have `CustomerRepresentation
  extends RepresentationModel<CustomerRepresentation>`, so I first had `ProductPatch extends RepresentationModel<ProductPatch>`, but I had the same result.

# Expected

The `_templates` section should list the fields of `ProductPatch` (`newName` and `newPrice`).

I searched for empty properties on HAL-FORM templates here and elsewhere but to no avail.
I assume I did something wrong but I can't figure it out.

**Comment by odrotbohm** [comment]
The implementation is currently based on Java Beans `PropertyDescriptor`. Using getter methods instead of public fields should do the trick as a workaround.

**Comment by matthieu-vergne** [comment]
Indeed, that was the trick. Thanks. {^_^}b

**Comment by matthieu-vergne** [comment]
I assume the issue becomes "obsolete documentation", then. Although I would greatly appreciate to allow the use of fields alone.
