### ISSUE TITLE
RepresentationModel doesn't works as expected for List response

### ISSUE THREAD

**Issue by kucw** [spring-projects/spring-hateoas#1527]
I try to use HATEOAS for `List<RepresentationModel<?>>` response, but the format of `_links` field is not the same as a single object response `RepresentationModel<?>`.

How can I modify the code so that the `_links` in `List<RepresentationModel<?>>` will not returns a list but return a json object like `RepresentationModel<?>` does?

## Single Object Response (Works fine :white_check_mark: )
```java
@GetMapping("/products/{productId}")
public ResponseEntity<RepresentationModel<Product>> getProduct(@PathVariable String productId) {
    Product product = new Product(); //simulate a Product response object
    product.add(linkTo(methodOn(ProductController.class)
            .getProduct(product.getProductId)
            .withSelfRel());
    return ResponseEntity.ok(product);
}
```
```json
{
    "productId": "f240c97b-439e-4cf2-9335-3478949c952e",
    "productName": "test product",
    "_links": {
        "self": {
            "href": "http://localhost:9115/products/f240c97b-439e-4cf2-9335-3478949c952e"
        }
    }
}
```

## List Response (Not work as expected :x: )
```java
@GetMapping("/products")
public ResponseEntity<List<RepresentationModel<Product>>> getProducts() {
    Product product = new Product(); //simulate a Product response object
    product.add(linkTo(methodOn(ProductController.class)
            .getProduct(product.getProductId)
            .withSelfRel());

    List<Product> products = new ArrayList<>();
    products.add(product);    

    return ResponseEntity.ok(products);
}
```
```json
[
    {
        "productId": "52ab86a7-96a5-46a0-ae51-5782ddb9e2e3",
        "productName": "test product",
        "_links": [
            {
                "rel": "self",
                "href": "http://localhost:9115/products/52ab86a7-96a5-46a0-ae51-5782ddb9e2e3"
            }
        ]
    }
]
```

**Comment by odrotbohm** [comment]
The problem is that you're returning a `List` as a top-level type, which is not a type we can assign the media type specific Jackson customizations for as you don't – on the root level – express "I am doing hypermedia related stuff" but "I am just returning a list of things. We unfortunately cannot register a customization for `List` as that would tweak the representation of *all* lists, top-level or not. 

You should be able to see the representation rendered correctly if you rather wrap the `List` into a `CollectionModel` instance.

**Comment by kucw** [comment]
@odrotbohm Thanks for your prompt reply! I'll try to use the `CollectionModel` you mentioned above.

**Comment by odrotbohm** [comment]
Yes, I can: don't. 🙃 What's the reason you do this in the first place?

**Comment by kucw** [comment]
@odrotbohm We have several micro services in our system, and we use different Spring Boot version on them due to some security issues. Since we want to keep interface consistent among these micro services, that's why I'm trying to apply HAL on `List` response.

**Comment by kucw** [comment]
**Solution:** For those who encounters the same issue as I did, the solution is I added below configuration and it resolves the HAL link issue.

```java
@Bean
public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder,
                                                               HypermediaMappingInformation mappingInformation) {
    ObjectMapper objectMapper = jackson2ObjectMapperBuilder.build();

    // By adding this line, RepresentationModel works in a collection for newer spring-hateoas version (higher than 1.x)
    mappingInformation.configureObjectMapper(objectMapper);

    return objectMapper;
}
```
