### ISSUE TITLE
Readme does not match code

### ISSUE THREAD

**Issue by aleksz** [spring-projects/spring-hateoas#153]
I'm trying to use ResourceAssemblerSupport as described in readme, but looks like it does not match. According to readme ResourceAssemblerSupport should have method "createResource" and first generic type should point to entity. In code I don't see this method and first generic type is controller.

Found IdentifiableResourceAssemblerSupport, which has "createResource", but it also want's to know controller class. Looks like it does not use EntityLinks.

Do I miss something?

**Comment by gregturn** [comment]
Duplicates #893 
Resolved via https://github.com/spring-projects/spring-hateoas/commit/9ba7f0179c5c3475be4dc9a3aea30cfad359fc63.
