### ISSUE TITLE
ObjectMapper wiring behavior changes in spring-hateoas 1.3 

### ISSUE THREAD

**Issue by BasicWolf** [spring-projects/spring-hateoas#1541]
Dear developers, 

Our projects code got suddenly broken after upgrading to spring boot 2.5.0 hence transitive `spring-hateoas 1.3.1`. Suddenly a custom `java.security.PublicKey` JSON serializer implemented as

```kotlin
// Kotlin
@JsonComponent
class PublicKeySerializer : StdSerializer<PublicKey>(PublicKey::class.java) {
        override fun serialize(value: PublicKey, generator: JsonGenerator, provider: SerializerProvider) {
            ...
            generator.writeString(...)
        }
    }
```
stopped working - the execution did never reach `serialize()` when a response was generated via `RepresentationModelAssemblerSupport`.

~Digging the code revealed, that the `ObjectMapper` was wired (actually set) in [TypeConstrainedMappingJackson2HttpMessageConverter](https://github.com/spring-projects/spring-hateoas/blob/1.2.x/src/main/java/org/springframework/hateoas/server/mvc/TypeConstrainedMappingJackson2HttpMessageConverter.java#L57). The said converter was constructed in [WebConverters()](https://github.com/spring-projects/spring-hateoas/blob/1.2.x/src/main/java/org/springframework/hateoas/config/WebConverters.java#L46). The reason for the changes became clear when reading `git blame` and issue #1453.~ - this has nothing to do with the issue, please see discussion below.

The problem is that we don't configure any custom `ObjectMappers` since "it worked out of the box". Could you please advise the course of action, given that response has `application/vnd.vendor-specific-...+json` media type?

**Comment by odrotbohm** [comment]
Can you provide a sample project, ideally in Java? We rely on all Jackson customizations already present on the source `ObjectMapper` instance when we set up the customizations made to `MappingJackson2HttpMessageConverter` now.

It's also not quite clear to me how you register the custom media type and what you expect to happen for it? Is it supposed to be a HAL based one and pick up the Spring HATEOAS customizations for HAL?

**Comment by BasicWolf** [comment]
Thank you @odrotbohm , I'll get back to you once that sample project is ready. 

The custom media type is basically specified in request handler annotation as:
```
@PostMapping("/path/to/resource", produces = ["application/vnd.vendor-specific-0.5+json])
```

**Comment by BasicWolf** [comment]
Hi @odrotbohm , here is the demo project: https://github.com/BasicWolf/springhateoas-issue-demo-1541
The readme contains details on switching between "broken" and "working" state (basically setting spring-boot version in `build.gradle`). 

To answer your question about registering custom media type: we don’t register the type and we basically don’t need HAL.

Thank you.

**Comment by BasicWolf** [comment]
Hi @odrotbohm. I think we solved it, and pardon for misleading in the original issue description. 
It all boiled down to customizing media type for `HalConfiguration`.

In version 1.2 the `objectMapperRegistrations` in the `MappingJackson2HttpMessageConverter` was not touched by Spring-HATEOAS. Hence `MappingJackson2HttpMessageConverter` used the `defaultObjectMapper` from Spring context - the one with the auto-wired serializers. 

Things changed in 1.3: now `WebConverters.augment()` ends up calling `registerObjectMappersForType(...)` - which registers the `MappingJackson2HttpMessageConverter` for 
- `application/json`
- `application/hal+json`

To extend this list, we had to customize `HalConfiguration` as:

```java
    @Bean
    HalConfiguration applicationJsonHalConfiguration() {
        return new HalConfiguration()
                .withMediaType(MediaType.APPLICATION_JSON)
                .withMediaType(MediaType.valueOf("application/vnd.vendor-specific-...+json"));
    }
```

Do you see this as a proper solution? Or is there some way to make things "work out of the box" without any extra configuration as before?

Thank you.

**Comment by BasicWolf** [comment]
Hi @odrotbohm. I ~think~ though we solved it, and pardon for misleading in the original issue description.
But no, we haven't solved it. We have a clue though, what might have gone wrong:

In version 1.2 the `objectMapperRegistrations` in the `MappingJackson2HttpMessageConverter` was not touched by Spring-HATEOAS. Hence `MappingJackson2HttpMessageConverter` used the `defaultObjectMapper` from Spring context - the one with the auto-wired serializers.

Things changed in 1.3: now `WebConverters.augment()` ends up calling `registerObjectMappersForType(...)` - which registers the `MappingJackson2HttpMessageConverter` for
- `application/json`
- `application/hal+json`

We can register our media type in `HalConfiguration` - but that's not what we really want and it breaks our response formatting.

**Comment by arhohuttunen** [comment]
I am working with the same code base as @BasicWolf. Just to clarify a couple of things:

The custom vendor media type is not HAL compatible, it's basically just JSON. So, no, we **cannot** register our media type with `HalConfiguration`.

What is breaking here is the ability to use custom serializers together with the custom media type.

**Comment by odrotbohm** [comment]
If it's "just JSON", why extend `RepresentationModelSupport` then? The latter is supposed to be done if you'd like to express hypermedia affordances with your representations. That in turn means you're not actually returning "just JSON" but a format that knows how to express links. That can be any of the ones we ship with Spring HATEOAS itself or a community supported one (Siren, JSON API).

If you want to build a hypermedia-enabled JSON flavor yourself you need to put a bit of infrastructure in place as documented [here](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#mediatypes.custom). If I add the following to the sample application above, the test goes green:

```java
public class MyMediaTypeConfiguration implements HypermediaMappingInformation {

	@Override
	public List<MediaType> getMediaTypes() {
		return List.of(MediaType.parseMediaType(MimeType.BOOKER_v0_5));
	}
}
```

**Comment by arhohuttunen** [comment]
Yes, we actually do want to express links. Maybe "just JSON" was a bad way to express "not HAL".

And also yes, we don't need any further configuration for our vendor specific type, so the above media type configuration seems to work fine.

It's something that seemed to work before without it, which led to us thinking that it broke between `spring-hateoas` versions. Thanks for the clarification.

**Comment by odrotbohm** [comment]
The change is a side effect of the previous way of configuration causing invalid JSON being rendered in certain edge cases (e.g.: HAL-FORMS not activate but requested would produce arbitrary JSON that is not HAL-FORMS).

I can only recommend to piggy back on one of the supported hypermedia types. The default rendering you get from rendering `RepresentationModelSupport` via an `ObjectMapper` that's not equipped with explicit serializers for `RMS` is *completely unsupported*. I.e. we might change the structure of these classes in a way that tweaks the default representation. You basically risk breaking changes by upgrading to a newer version of Spring HATEOAS.

**Comment by arhohuttunen** [comment]
Right. Now I think I get it. So in other words, to persist the current formatting we would need to actually write the serializers for those.

It seems to me that we should indeed piggy back one of the existing types, but obviously we cannot break the current implementation.

**Comment by reda-alaoui** [comment]
I just had the same issue with the serialization of CollectionModel.
The main issue in this case is that our existing clients do not expect the content of the collection to be in `_embedded`.

The endpoint:
```java
@GetMapping(value = "/")
public ResponseEntity<?> greetings() {
  return ResponseEntity.ok(CollectionModel.of(Lists.newArrayList(new Greeting("toto"))));
}
```

With Spring HATEOAS 1.1.0:
```
GET /
accept: "application/json"

{
  "content": [{
    "name": "foo"
  }]
}
```
With Spring HATEOAS 1.3.1:
```
GET /
accept: "application/json"

{
  "_embedded": {
    "content": [{
      "name": "foo"
    }]
  }
}
```

Following the advice of @odrotbohm, I fixed the issue with:
```java
@Configuration
public class HypermediaBareJsonConfiguration implements HypermediaMappingInformation {
  @Override
  public List<MediaType> getMediaTypes() {
    return Collections.singletonList(MediaType.APPLICATION_JSON);
  }
}
```

I think this should be at least documented as a breaking change.

Moreover, I don't see how to get rid of this workaround without breaking all the existing clients. Some of our clients (most of them) don't understand hypermedia, so it was fine letting them use the same endpoint.
Are the Spring HATEOAS users expected to have one implementation producing hypermedia formats and another one producing application/json ? It seems to me the use case is widespread enough to deserve its explicit support in this project.

**Comment by odrotbohm** [comment]
As indicated in other tickets discussing this issue, the representation returning `content` has never been a supported one. If you use `RepresentationModel` you want / need to piggy-back onto some hypermedia type as otherwise the client doesn't actually know how to access hypermedia elements. Spring Boot actually enabled "HAL for `application/json` requests" by default, which caused us to hope that folks already use HAL as format by default, unless they *explicitly* out out of that. If they do that, they can / have to also register that new customization needed.

We can definitely mention that aspect in in the reference documentation but we strongly recommend to use a proper hypermedia type and not some arbitrary, unsupported format created by Jackson.
