### ISSUE TITLE
Testing with MockMVC

### ISSUE THREAD

**Issue by mikebski** [spring-projects/spring-hateoas#1550]
Is there any documentation for testing this with MockMVC? Everything works fine for me until I start trying to put resources of type `Content-Type:text/uri-list` at endpoints.

I'm sure there is some configuration needed, I get a 404 for the related resource endpoints, but I can't find documentation about it...

**Comment by odrotbohm** [comment]
Hard to tell without seeing some code. That said, HATEOAS doesn't come with any kind of support for the `text/uri-list` media type itself. Are you referring to Spring Data REST by accident?

**Comment by mikebski** [comment]
Yes, I guess this goes in the data rest repo instead...
