### ISSUE TITLE
Add @DecimalMin and @DecimalMax for Hal+Forms Property Metadata

### ISSUE THREAD

**Issue by talentedasian** [spring-projects/spring-hateoas#1557]
In the current [Spring Hateoas](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#mediatypes.hal-forms.metadata), it is not possible to add a limit for decimal values. It would be useful for fields accepting decimal values.

`@DecimalMin/@DecimalMax` currently does not work and is only limited to having the `@Min/@Max` annotations.

**Comment by talentedasian** [comment]
Since `Hal+Forms` currently does not have specifications for max decimals I suppose the Spring Hateoas team can just add support to `@DecimalMin/@DecimalMax` in the `Min/Max` `Hal+Forms` specification.

**Comment by talentedasian** [comment]
I'm guessing this would not be possible without changing `min` and `max` `HalProperty` fields to BigDecimals or Doubles to retain precision or the decimal values.

**Comment by talentedasian** [comment]
Would be wonderful to also update the reference documentation.

**Comment by odrotbohm** [comment]
@talentedasian – Would you mind stopping to mess with the tickets and pull requests? I'm getting lost in all the notifications for this ticket. Please let us take care of that, thanks!

**Comment by odrotbohm** [comment]
That's in place with the current snapshots for inclusion in 1.4 M1.
