### ISSUE TITLE
Consider @JsonProperty-defined property name for affordance metadata

### ISSUE THREAD

**Issue by talentedasian** [spring-projects/spring-hateoas#1563]
Make the default name or value of the field `name` of the `DefaultMetadataProperty` to the value that is present in the **@JsonProperty** annotation else, use the default field name.

**Comment by odrotbohm** [comment]
Would you mind taking a step back and describing the actual problem to be solved?

**Comment by talentedasian** [comment]
![image](https://user-images.githubusercontent.com/71717525/123751314-3058b980-d8ea-11eb-8070-866a489be53b.png)
The image above is the desired output. Even though the field is named `politicalParty`, a `@JsonProperty` annotation is present with the value of `political_party`. This should be the default behavior for names of Hal+Form _templates property name value(`_templates.default.properties[0].name`) because the `@JsonProperty` values are the one that are expected in the `@RequestBody`. 

For example, I have a DTO that is used in a `@RequestBody`:

```java
public class AddPoliticianDTORequest {

        @JsonProperty("first_name")
	String firstName;

        @JsonProperty("last_name")	
	String lastName;
	
```
Spring MVC expects the body of the **POST** method to have json values of **first_name** and **last_name**. If I were to make an affordance for this in a Hal+Form mediatype, the resulting data would  be:
```
"templates":{
   "default":{
      "method":"post",
      "properties":[
         {
            "name":"politicalParty",
            "required":true,
            "type":"text"
         }
      ],
      "target":"http://localhost:8080/api/politician/politicians"
   }
}
The response would ultimately break your clients that use your api since you expect political_party instead of "politicalParty" all because of the @JsonProperty. The name of the property values should always be the value of a @JsonProperty annotation when it is present and if not, use the default field name.
```

**Comment by odrotbohm** [comment]
Awesome, thanks for the additional context.
