### ISSUE TITLE
Controller returns `links` and not `_links` and much more (see body).

### ISSUE THREAD

**Issue by talentedasian** [spring-projects/spring-hateoas#1572]
Whenever I test my controller response with MockMvc, it does not return the correct response for links. 

1. See the **title** of this issue.
2. Links are rendered as an array instead of key value pairs. For example it should be 
```
_links: {

    }
```
and not 
```
links:[  {  }  ]
```

The test is a slice test only testing a single controller. The test class is annotated with `@WebMvcTest(controller.class)` and `@AutoConfigureMockMvc`.

**Comment by odrotbohm** [comment]
This suspiciously looks like you're not causing the HAL rendering to be active. It's hard to tell what causes this without further information because it could be the server set up, the test setup, the setup of the request being executed etc. Can you provide a minimal example project that reproduces the error?

**Comment by talentedasian** [comment]
```java
@WebMvcTest({Oauth2.class})
public class Oauth2ControllerTest {

	public MockMvc mvc;
	
	@BeforeEach
	public void setup(WebApplicationContext wac) {
		mvc = MockMvcBuilders.webAppContextSetup(wac)
				.alwaysDo(MockMvcResultHandlers.print())
				.build();
	}
	
	@Test
	public void shouldReturnHalForms() throws Exception {
		String jwt = JwtProvider.createJwtWithFixedExpirationDate("test sub", "1111", "test name");
		Cookie cookie = new Cookie("accessJwt", jwt);
		Cookie[] cookies = {cookie};
		
		mvc.perform(get(create("/login/oauth2/code/facebook"))
				.accept(MediaTypes.HAL_FORMS_JSON)
				.cookie(cookies))
			.andExpect(status().isOk());
	}
```

This test prints the links as arrays and not as key value pairs but doing a full spring boot test with the `@SpringBootTest` fixes this. I only need to test one controller so I am forced to do this up until I get a fix.

**Comment by odrotbohm** [comment]
I'd really have to get an executable sample to be able to debug it to tell more.

**Comment by gregturn** [comment]
Your web controller methods need to be returning Spring HATEOAS types (`RepresentationModel` or one of its subtypes) for things to render properly.

**Comment by talentedasian** [comment]
> Your web controller methods need to be returning Spring HATEOAS types (`RepresentationModel` or one of its subtypes) for things to render properly.

My DTO extends `RepresentationModel`

**Comment by odrotbohm** [comment]
Closing this due to the lack of feedback required to further diagnose this.
