### ISSUE TITLE
Release 1.4 M2

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-hateoas#1595]

**Comment by Fatezhang** [comment]
Hi @odrotbohm , just wonder when your team plan to full release 1.4? I really need some feature in the new version.

**Comment by odrotbohm** [comment]
We align with Spring Boot's release schedule and the 2.6 GA release of that is currently scheduled for November 18th. The RC – in case you think that's stable enough – is scheduled for October 21st.
