### ISSUE TITLE
Wrong nullability declarations for properties of `Link`

### ISSUE THREAD

**Issue by michael-arndt-gcx** [spring-projects/spring-hateoas#1602]
I am trying to add domain-specific meta-data to Links, however, because `package-info.java` contains

```
@org.springframework.lang.NonNullApi
package org.springframework.hateoas;
```

and Link contains no other nullability information, Kotlin expects every method to return non-nullable values, which is not the case, e.g. for `getHreflang` or `getMedia`.

Thus it's currently impossible to extend Link in Kotlin.

This can be fixed by adding correct nullability information to all methods that should be able to return null, e.g.

```java
@JsonProperty @Nullable
public String getHreflang() {
    …
}
```

**Comment by odrotbohm** [comment]
Good catch, thanks. That's fixed for the upcoming releases.
