### ISSUE TITLE
Use spring-hateoas to generate link from client side

### ISSUE THREAD

**Issue by nithril** [spring-projects/spring-hateoas#164]
My purpose is to use spring-hateoas to generate URI for a http client. 

``` java
Link link = linkTo(methodOn(PersonController.class).show(2L))
httpClient.get(link)
```

But `ControllerLinkBuilderFactory` is tightely coupled to  `ServletUriComponentsBuilder`. 

``` java
ControllerLinkBuilderFactory.linkTo(invocation){
//return a ServletUriComponentsBuilder
UriComponentsBuilder builder = ControllerLinkBuilder.getBuilder().path(mapping);
}
```

I wonder if it is possible to loosely coupled factory and urlbuilder class. eg. by creating an overridable method `createUriComponentsBuilder()`

**Comment by gregturn** [comment]
Creating client-side code that couples to server-side code, and uses it to create a link, a structure meant to decouple both sides?

Clients need to read links, consume links, and navigate links. Not build links.

**Comment by gregturn** [comment]
This is generally not a practice supported by Spring HATEOAS. If you wish to discuss more client-side options, please open a suitable issue.
