### ISSUE TITLE
Unable to Disable HalMediaTypeConfiguration

### ISSUE THREAD

**Issue by EarthCitizen** [spring-projects/spring-hateoas#1655]
I have the requirement to use `application/json` and have my own mixin for `PageModel`. This means (as far as I can tell) that I need to disable `HalMediaTypeConfiguration` entirely because it's mixins get registered and override the ones in my default mapper. Looking through the code, I did not find a way to prevent `HalMediaTypeConfiguration` from being used. The only solution I found was the following:

```java
public class CustomInstantiationAwareBeanPostProcessor implements InstantiationAwareBeanPostProcessor {
    @Override
    public Object postProcessBeforeInstantiation(Class<?> beanClass, String beanName) throws BeansException {
        if (HalMediaTypeConfiguration.class.equals(beanClass)) {
            return new HalMediaTypeConfiguration(null, null, null, null, null) {
                @Override
                public List<MediaType> getMediaTypes() { return List.of(); }

                @Override
                public ObjectMapper configureObjectMapper(ObjectMapper mapper) { return mapper; }
            };
        }

        return null;
    }
}
```
In my mind, such a brute-force method should not be necessary. This feels hacky, but I did not find another way to do it. I even tried implementing a `HypermediaMappingInformation` with media type `application/json`, but `HalMediaTypeConfiguration` took precedence.

If there is a clean way to disable `HalMediaTypeConfiguration` it was not obvious to me. If there is not a way, perhaps the solution is that custom instances of `HypermediaMappingInformation` that override a media type of one that is built-in take precedence?

**Comment by odrotbohm** [comment]
Can you take a step back and elaborate on what the actual media type requirements are for your application? What hypermedia format do you want to use in the first place?

**Comment by EarthCitizen** [comment]
@odrotbohm OK. So I removed my override of `HalMediaTypeConfiguration` in the post processor, removed my custom `HypermediaMappingInformation` implementation, and set up the configuration below (per your suggestion), and everything worked as expected.

```json
@Configuration
@EnableHypermediaSupport(type = {})
public class CustomHateoasConfiguration {}
```
