### ISSUE TITLE
Migrating old spring controllers to spring-hateoas problems.

### ISSUE THREAD

**Issue by bedge** [spring-projects/spring-hateoas#168]
This is a cross-post of a question on S.O.
http://stackoverflow.com/questions/22824059/spring-hateoas-the-method-methodonclassxxxxcontroller-is-undefined-for-the

In short, I think I'm running into old spring (pre-spring-boot) vs new spring version incompatibilities.

Is there a HOWTO guide for migrating old style controllers to hateoas?

This is a common problem for many in adopting new conventions. There's a huge amount of legacy code and unless there's a migration path, it's very difficult to move to new best practices.

**Comment by gregturn** [comment]
Given the SO question was closed and no discussion had followed here I'm closing this issue.
