### ISSUE TITLE
Allow creation of UriTemplates when pointing to controller methods.

### ISSUE THREAD

**Issue by Gotusso** [spring-projects/spring-hateoas#169]
Would be nice to have an easy way of return URL templates directly. For instance, suppose we have a method like

``` java
@RequestMapping
public HttpEntity<ListResource> list(
        @RequestParam(value = "query", required = false) String query,
        @RequestParam(value = "page", defaultValue = "1") Integer page,
        @RequestParam(value = "limit", defaultValue = "10") Integer limit) {
    // ...
}
```

I can reference an specific invocation with linkTo(methodOn(Controller.class).list("foo", 1, 20) but I think there is no easy way to reference a generic call without specifing the method parameters. Invoking with null results in a exception.

I would like to get something like

```
{
    rel: "list"
    href: "http://localhost:8080/myresource{?query,page,limit}"
}
```

Is that possible?
Regards

**Comment by meyertee** [comment]
I wonder if you guys have had any thoughts on this, a related problem also appears on [this StackOverflow question](http://stackoverflow.com/questions/25017037/template-variables-with-controllerlinkbuilder). The solution of _Chris DaMour_ kind of works, but only for non-required request-params.
The same problem exists when using `EntityLinks` as it's using the `ControllerLinkBuilder` under the hood.

Digging into the code I didn't find an obvious solution, I think there are two underlying problems:
* the escaping of _{_ and _}_ in path variables in `HierarchicalUriComponents.encodeBytes()` which can't be overridden. The only way I found is to replace _%7B_ and _%7D_ back to curly brackets in the resulting string.
* the fact that `UriComponents.expandUriComponent()` doesn't accept null values for required attributes & path variables. The method is used by `HierarchicalUriComponents expandInternal()`, which is used by `UriComponentsBuilder.buildAndExpand` and ultimately by `ControllerLinkBuilderFactory.linkTo()` - the point being that it's also not easy to override or change.

I found out that when using `EntityLinks.linkFor(Class<?> type, Object... parameters)` you can pass `UriComponents.UriTemplateVariables.SKIP_VALUE` as parameters which causes `UriComponents.expandUriComponent()` to accept them even if they're required, that's the workaround I'm using for now (plus unescaping _{}_)

The workarounds are compilated and insufficient though, so it would be really nice to have a proper and easy way to generate templated links - they're so common in HAL, that it's painful to have to create them with hacks.

In terms of signature maybe extra methods on the `LinkBuilder` could work:
```
Link linkToCollectionResource(Class<?> type, TemplateVariables variables);
Link linkToSingleResource(Class<?> type, TemplateVariables variables);
```
It could then build the link using the variables set on the `TemplateVariables` instance and automatically construct a templated link... just a thought.
Something similar could be passed to the builder: `linkTo(methodOn(Controller.class, variables).list(null, null, null)`

**Comment by lazee** [comment]
The HAL implementation in this project is really useless without a good support for templated urls. 

So, I really hope this could be prioritised. All other HAL implementations for Java has its own problems that prevents me from using it. HALBuilder for instance doesn't respect Jackson annotations in beans added to it.

**Comment by jiwhiz** [comment]
@lazee +1

My resource assembler classes are full of hack to work around this issue. Hope @olivergierke can fix it ASAP :)

**Comment by mikerahmati** [comment]
+1

**Comment by Chumper** [comment]
:+1:

**Comment by dschulten** [comment]
AffordanceBuilder from the feature/affordances branch, or from spring-hateoas-ext (maven released) allows to define templated URIs by passing null for variables that should be templated. Otherwise it aims to be a drop-in replacement for ControllerLinkBuilder. See also https://github.com/dschulten/hydra-java#affordancebuilder-for-rich-hyperlinks-from-v-0-2-0

We are working to get AffordanceBuilder into spring-hateoas, feedback appreciated.

**Comment by ryl** [comment]
I'm also running up against this problem. I would normally use spring data rest, but in this particular case, I'm working on a project with a backend for which there is no suitable spring-data-xxx (jpa, elasticsearch, mongodb, etc) flavor. My solution was to just us hateoas directly and expose things similar to how you would expect from spring data rest -- but without a means of creating templated urls, its really difficult. Would really like to see this feature.

**Comment by pax95** [comment]
+1

**Comment by megglos** [comment]
+1

**Comment by GDownes** [comment]
+1

**Comment by ptahchiev** [comment]
+1

**Comment by JoseAlavez** [comment]
+1

**Comment by osvaldopina** [comment]
I had this problem in the project that I'm currently working and I developed a framework to create links and templates from controller calls. It also allows the use of spel expressions to control link rendering. In the next major version it will be possible to generate links and templates using only annotations.  The repository is https://github.com/osvaldopina/linkbuilder. Any feedback will be appreciated.

**Comment by pgrund** [comment]
+1

**Comment by tmartinelli** [comment]
+1

**Comment by kranjcec** [comment]
+1

**Comment by olivergierke** [comment]
Just a quick heads up for you guys, we're going to have this fixed in a larger effort that will bring in an advanced accordances model built by @dschulten.

**Comment by johndeverall** [comment]
+1

**Comment by arobirosa** [comment]
+1

**Comment by openwms** [comment]
+1

**Comment by olivergierke** [comment]
That should be in place now.

**Comment by rworsnop** [comment]
@olivergierke  I'm seeing templates generated in this format:
   `http://localhost/foo?a={a}&b={b}`
For query parameters, shouldn't they look like this?
  `http://localhost/foo{?a,b}`

**Comment by olivergierke** [comment]
That depends on whether the parameter is required (former format) or optional (latter format). Mixing the two, works, too, but if you see the former format, I am pretty sure, your `@RequestParam`s are mapped with `required = true`.

**Comment by rworsnop** [comment]
Thanks for the quick response! Yes, that was exactly it. 

On a related note, what should I see when `@RequestParam` has a `defaultValue`? I'm seeing the parameter omitted from the template.
