### ISSUE TITLE
Adding support for a hateoas enabled client

### ISSUE THREAD

**Issue by dschulten** [spring-projects/spring-hateoas#17]
The promise of hateoas is to decouple clients from rest api changes. Standards for this seem to be evolving right now:

http://tools.ietf.org/html/rfc6570 defines how to create URI templates which contain variables or get parameters (March 2012)

In http://tools.ietf.org/html/draft-nottingham-json-home-00 Mark Nottingham comes up with a home document which tells clients how to use the api on a home document, it contains URI templates for the resources.

What is your take on this? Do you plan to add support for hateoas clients which need not be changed if the hateoas-enabled api changes? What should such a support look like?

In general, what would you recommend if someone wants to build a hateoas client based on spring-hateoas resources?

Best regards,
Dietrich

**Comment by gregturn** [comment]
Our current story for Java-based client-side support is here (`Traverson`, `WebClient`, `RestTemplate`, `WebTestClient`, and `TestRestTemplate`) => https://docs.spring.io/spring-hateoas/docs/1.1.0.M3/reference/html/#client

As for JavaScript tools, we aren't entering into that arena. The Spring team isn't focused on JS-based tools.
