### ISSUE TITLE
Add support for `javax.validation.constraints.NotBlank`

### ISSUE THREAD

**Issue by fdutton** [spring-projects/spring-hateoas#1753]
Currently, Jsr303AwarePropertyMetadata indicates that a property is required if the property is annotated with javax.validation.constraints.NotNull but it does not give the same consideration to properties annotated with javax.validation.constraints.NotBlank.

The presence of the `@NotBlank` annotation should be considered equivalent to the property being annotated with `@NotNull @Pattern(regex = "^\\s*(\\S+\\s*)+$")`.

Ideally, Jsr303AwarePropertyMetadata would support this annotation by updating its `isRequired` and `getPattern` methods. However, Jsr303AwarePropertyMetadata currently assumes that a property has zero-or-one `@Pattern` annotations, which is not valid. A property may have zero-or-more patterns.

In the case where a property is annotated with both `@NotBlank` and `@Pattern`, it may be acceptable to ignore the pattern implied by the `@NotBlank` annotation. Otherwise, it may be necessary to introduce a `getPatterns` method and deprecate `getPattern`.

**Comment by odrotbohm** [comment]
Sounds reasonable. Care to draft a PR to discuss?

**Comment by fdutton** [comment]
It would be my pleasure.

What is the process? Should I create a fork and submit the pull-request from there?

**Comment by odrotbohm** [comment]
Sounds good to me. Don't get overenthusiastic with formalities, I'll take care of those. The change plus a test case is just fine.

**Comment by fdutton** [comment]
I cloned the main branch and did a build without making any changes and this unit-test fails. It appears to be a race condition because it does not fail with stepping through the code with a debugger.
```
[INFO] Running org.springframework.hateoas.config.EnableHypermediaSupportIntegrationTest
[ERROR] Tests run: 21, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.699 s <<< FAILURE! - in org.springframework.hateoas.config.EnableHypermediaSupportIntegrationTest
[ERROR] registersNoOpMessageResolverIfMessagesBundleMissing  Time elapsed: 0.018 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: INSTANCE
 but was: org.springframework.hateoas.mediatype.MessageSourceResolver@e998bad
	at org.springframework.hateoas.config.EnableHypermediaSupportIntegrationTest.lambda$registersNoOpMessageResolverIfMessagesBundleMissing$11(EnableHypermediaSupportIntegrationTest.java:308)
	at org.springframework.hateoas.config.EnableHypermediaSupportIntegrationTest.registersNoOpMessageResolverIfMessagesBundleMissing(EnableHypermediaSupportIntegrationTest.java:306)
```
