### ISSUE TITLE
Retrieve all links with the same relation

### ISSUE THREAD

**Issue by SimonBodner** [spring-projects/spring-hateoas#1756]
Hi!

I am facing the following problem:
I am trying to request images from an API using Spring Hateoas.
The API gives me two linkes with the same relation name but the links themselve are different.
So ​let's say e.g.:

rel name is "get-image"

links: (among others): 
rel name: get-image; link: /abc/image/cover/...
rel name: get-image; link: /abc/image/screenshot/...

The problem is that in that case always just the first link is returned and all others with the same relation name are ignored.

I found out that the problem is located in `org.springframework.hateoas.ResourceSupport::getLink`.
The do-while loop always returns the first link found with the given relation name.
I'd would need all links with this relation name to be returned - not just the first one matching.

Any ideas on this? 

Thanks in advance!

**Comment by odrotbohm** [comment]
According to the method signature, `….getLink(…)` needs to return a single link. So, in case of multiple ones available for a particular link relation, it *has to* pick one. There's `getLinks(…)`, too, though, which just gives you all of them.

**Comment by SimonBodner** [comment]
Ah, I wasn't aware of `getLinks`method. Thanks!
