### ISSUE TITLE
WebFlux LinkTo builder does not work with eager path mapping (like {*foo})

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-hateoas#1793]
I have a controller with a mapping like this

```java
@RequestMapping("/{tenantId}/{*categoryPath}")
public class PageByPathController {
    private final PageRepository pageRepository;
    private final PageResourceAssembler pageResourceAssembler;

    @GetMapping
    public Mono<String> getItem(@PathVariable UUID tenantId,
                                @PathVariable String categoryPath,
                                @RequestHeader(value = "Accept-Language", required = false) String language) {
```

When I try to create the links for this method, I tried to use something like this:
```java
linkTo(methodOn(PageByPathController.class).getItem(entity.getTenantId(), entity.getPath(),null))
```

The resulting URLs path is then ```/2ffa5e8b-c141-4656-9dee-24d18a4f8ff0/{*categoryPath}``` So the categoryPath is not expanded.

**Comment by odrotbohm** [comment]
Can you elaborate, what `{*…}` is supposed to mean? It's not a valid [RFC6570](https://datatracker.ietf.org/doc/html/rfc6570) URI template variable.

**Comment by pcornelissen** [comment]
Correct, the methodOn(...) stuff is using the webmvc URL mapping to create the URLs.
The {*foo} is a "catch-all" so a mapping like

/{myId}/{*path}
Would map to /456789/foo/bar/baz and path would be foo/bar/baz

In contrast to 
/{myId}/{path} which would not match /456789/foo/bar/baz because path would only be foo and the /bar/baz suffix would not match

**Comment by odrotbohm** [comment]
I've applied a fix to `main` that adds the general support to that. Working on that, it became clear that we should rather have better abstractions in place that allow us to handle the different places we need to teak to make this work in a single place.

You now should be able to expand values properly. Handing `null` as a value triggers the composite segment template variable `{/…*}` – i.e. proper URI template syntax – being added to the URI to advertise the ability to expand more path segments.

Backports to 1.5 and 1.4 coming in a second. Feel free to give the snapshots a try.

**Comment by pcornelissen** [comment]
Thank you!
