### ISSUE TITLE
regardless of Accept Header controller produces HAL-Style links (since v1.3.x)

### ISSUE THREAD

**Issue by sleicht** [spring-projects/spring-hateoas#1799]
Since version **1.3.x** the Accept header is not respected for the EntityModel json. I could reproduce the issue using the basic example of [spring-projects/spring-hateoas-examples](https://github.com/sleicht/spring-hateoas-examples/tree/issue-1799)
```
### employees json
GET http://localhost:8080/employees
accept: application/json

### employees hal
GET http://localhost:8080/employees
accept: application/hal+json
```
Both calls return the same response with the same style of links: `"_links": {"self": {"href": "http://localhost:8080/employees"}}`

Expected would be this:
```
### employees json
GET http://localhost:8080/employees
accept: application/json
```
returns this self link: `"links": [{"rel": "self","href": "http://localhost:8080/employees"}]`

```
### employees hal
GET http://localhost:8080/employees
accept: application/hal+json
```
returns this self link: `"_links": {"self": {"href": "http://localhost:8080/employees"}}`

**Comment by sleicht** [comment]
Could it be related to this issue #1541? And if yes, how should the example be changed so that the expected responses would be returned?

**Comment by odrotbohm** [comment]
The expectation is invalid. As already expressed [here](https://github.com/spring-projects/spring-hateoas/issues/1541#issuecomment-857754162) and [here](https://github.com/spring-projects/spring-hateoas/issues/1541#issuecomment-862420980), that direct object, plain JSON rendering was never officially supported. Only media types that can be activated in `@EnableHypermediaSupport` are supported. The first one configured (Boot sets that to HAL by default) for that is used as the media type to be produced if `application/json` is requested.

**Comment by jamesdh** [comment]
@odrotbohm is it not possible to have the modern HAL representation rendered by default but the traditional "direct object, plain JSON rendering" if `application/json` is requested? I'm literally trying to migrate a client who had HAL disabled. Multiple web clients hit their API's, and migrating all of them at once isn't practical.

**Comment by odrotbohm** [comment]
[This comment](https://github.com/spring-projects/spring-hateoas/issues/1799#issuecomment-1159524993) has all info.

**Comment by jamesdh** [comment]
@odrotbohm So basically what you're saying is that in Spring, out of the box, you either get support for the `HypermediaType` types and nothing else, or you get everything else but not the `HypermediaType` types? Nothing in between?

**Comment by odrotbohm** [comment]
It does not make sense to support a Spring HATEOAS-specific, unspecified, ever-changing, additional JSON representation when the whole point of the library is to allow developers to make use of the existing, well-defined, stable media types. In the interest of reducing the effort to maintain client applications, that's the only reasonable way forward.
