### ISSUE TITLE
hateoas-The List collection eliminates the rel tags

### ISSUE THREAD

**Issue by jerry0818** [spring-projects/spring-hateoas#1805]
In a current project I need to return the List of an object and an object where the object is the uri containing the self.

When returning a single object.Like this:

`{
	"id": "111",
	"name": "Vinci",
	"age": 0,
	"sex": 0,
	"_links": {
		"self": {
			"href": "http://localhost:8080/User/GetUser/111"
		}
	}
}`

But when I use List to encapsulate a single object return, it turns out this:

`[
	{
		"id": "111",
		"name": "sofia",
		"age": 0,
		"sex": 0,
		"links": [
			{
				"rel": "self",
				"href": "http://localhost:8080/User/GetUser/111"
			}
		]
	}
]`

In contrast, a single object hypermedia _links subobject becomes a links array when returning the object collection, and the self label under the _links subobject has more rel correlation when returning the object collection。Of course, only if my object extends the RepresentationModel,

There are many related hateoas s that return List mostly by encapsulating objects through the CollectionModel but the List returning the result is nested by the "_embedded" tag I tried to get the array of objects under the " _embedded"  tag through the method of the CollectionModel object but all failed.

How does the object results in the object collection have the same hypermedia style as the result obtained by a single object?
Like this:
`[
	{
	    "id": "111",
	    "name": "Vinci",
	    "age": 0,
	    "sex": 0,
	    "_links": {
		    "self": {
			  "href": "http://localhost:8080/User/GetUser/111"
		     }
             }
	}
]`

**Comment by odrotbohm** [comment]
The media type-specific serializers only kick in for return types. There's currently no support for anything but that, and we don't intend to change that. I.e. the default Jackson rendering you see here is completely unsupported and there's no guarantee made about the structure resulting from such a serialization at all.
