### ISSUE TITLE
Support for Resources in a Resource to be added to _embedded

### ISSUE THREAD

**Issue by tombee** [spring-projects/spring-hateoas#193]
After speaking with @olivergierke, we came to the conclusion that there's no way to get a Resources collection added to an _embedded collection in the root of the envelope without using @JsonUnwrapped.

The problem then is that if there are multiple Resources fields, the last field serialized will overwrite the existing _embedded section.

I believe that @olivergierke suggests that a new custom serializer needs to be written to support adding Resources fields to the _embedded section.

**Comment by olivergierke** [comment]
Was this closed by accident?

**Comment by tombee** [comment]
Ah I thought it wasn't being addressed, since it's been open for so long without a reply :)

**Comment by olivergierke** [comment]
If we finally decide not to implement it, we can still close it. Currently I am just a bit swamped with other work. :)

**Comment by gregturn** [comment]
Related to #864

**Comment by gregturn** [comment]
In #864, I am working on a builder that supports:

```java
@GetMapping("/explicit-and-implicit-rels")
RepresentationModel<?> explicitAndImplicitRelations() {

    Staff staff1 = new Staff("Frodo Baggins", "ring bearer");
    Staff staff2 = new Staff("Bilbo Baggins", "burglar");

    Product product1 = new Product("ring of power", 999.99);
    Product product2 = new Product("Saruman's staff", 9.99);

    return ModelBuilder3 //
            .entity(staff1) //
            .entity(staff2) //
            .entity(product1) //
            .entity(product2) //
            .link(Link.of("/people/alan-watts")) //
            .entity(LinkRelation.of("ring bearers"), staff1) //
            .entity(LinkRelation.of("burglars"), staff2) //
            .link(Link.of("/people/frodo-baggins", LinkRelation.of("frodo"))) //
            .build();
}
```

Yielding...

```
{
  "_embedded" : {
    "burglars" : {
      "name" : "Bilbo Baggins",
      "role" : "burglar"
    },
    "staffs" : [ {
      "name" : "Frodo Baggins",
      "role" : "ring bearer"
    }, {
      "name" : "Bilbo Baggins",
      "role" : "burglar"
    } ],
    "ring bearers" : {
      "name" : "Frodo Baggins",
      "role" : "ring bearer"
    },
    "products" : [ {
      "name" : "ring of power",
      "price" : 999.99
    }, {
      "name" : "Saruman's staff",
      "price" : 9.99
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "/people/alan-watts"
    },
    "frodo" : {
      "href" : "/people/frodo-baggins"
    }
  }
}
```

**Comment by odrotbohm** [comment]
We took a first stab at a HAL specific model builder with 2cab91a33253e6e2e2587b868b871deb872dc168. See the [updated reference documentation](https://docs.spring.io/spring-hateoas/docs/1.1.0.BUILD-SNAPSHOT/reference/html/#mediatypes.hal.models) for details.

Feel free to reopen or create a new ticket in case you need additional features.
