### ISSUE TITLE
Documentation page is out of date, has broken links

### ISSUE THREAD

**Issue by stefanganzer** [spring-projects/spring-hateoas#1940]
The documentation page https://spring.io/projects/spring-hateoas#learn seems to be broken for the 1.5.x and 1.4.x releases:
* 1.5.2 is listed as GA, even though [1.5.3](https://mvnrepository.com/artifact/org.springframework.hateoas/spring-hateoas/1.5.3) has been released already
* The links to the [1.5.3-SNAPSHOT](https://docs.spring.io/spring-hateoas/docs/1.5.3-SNAPSHOT/reference/html/), [1.5.2](https://docs.spring.io/spring-hateoas/docs/1.5.2/reference/html/) reference and API documentations are broken. The same is true for the 1.4.x releases. https://docs.spring.io/spring-hateoas/docs/ shows that the documentation for these versions is missing altogether.

**Comment by odrotbohm** [comment]
This should be fixed with the just releases 1.5.4.
