### ISSUE TITLE
Jackson2HalModule.HalLinkListSerializer needs default constructor

### ISSUE THREAD

**Issue by csavory** [spring-projects/spring-hateoas#196]
I tried to reuse `HalLinkListSerializer` in one of my ResourceSupport objects to render a list of links using 

``` java
@JsonSerialize(using = Jackson2HalModule.HalLinkListSerializer.class)
```

It worked under one scenario, but on another Jackson would throw an exception saying that Jackson2HalModule$HalLinkListSerializer has no default constructor. 

I have a temporary workaround using this

``` java
    public static class CustomHalLinkListSerializer extends Jackson2HalModule.HalLinkListSerializer {

        public CustomHalLinkListSerializer() {
            super(null, null);
        }

    }
```

**Comment by piyushmor** [comment]
This is probably an issue even now!

**Comment by odrotbohm** [comment]
This works as designed. `HalHandlerInstantiator` will take care of creating instances of `CustomHalLinkListSerializer`, i.e. you need to register that with the `ObjectMapper` that serializes your objects. Spring HATEOAS equipped `HttpMessageConverters` responsible for rendering HAL already have that configured.

**Comment by piyushmor** [comment]
[org.springframework.http.converter.json.MappingJackson2HttpMessageConverter] Failed to evaluate Jackson serialization for type [class de.zalando.godfathers.employee.management.model.EmployeeResponse]: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalLinkListSerializer': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalLinkListSerializer]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalLinkListSerializer.<init>()

**Comment by piyushmor** [comment]
my model is: 
```
data class EmployeeResponse(
    val employees: List<EmployeeInformation>
) : EntityModel<EmployeeResponse>()

data class EmployeeInformation(
    val employeeId: String,
    val email: String? = null,
    val name: Name? = null,
    val discountAccounts: CollectionModel<DiscountAccount>? = null
) : EntityModel<EmployeeInformation>()

data class Name(
    val firstName: String,
    val lastName: String
)

data class DiscountAccount(
    val id: String,
    val active: Boolean,
    val countryCode: String,
    val coupons: CollectionModel<Coupon>? = null
) : EntityModel<DiscountAccount>()

data class Coupon(
    val id: String,
    val code: String,
    val active: Boolean
)
```

**Comment by odrotbohm** [comment]
`HalHandlerInstantiator` doesn't know anything about your custom extension of `HalLinkListSerializer` and I don't see too much value in opening all of this up for extension in the first place as we need to tweak the internals on a regular basis and it would ver quickly become an API maintenance nightmare.

The original poster's problem and the workaround should not be needed if all you want to do is reuse the existing implementations.

**Comment by piyushmor** [comment]
then I think I am facing a different problem that has the same symptom

**Comment by MikeTraceur** [comment]
maybe it will help others too. I faced the same Warning and couldn't find the solution. after debugging a bit in spring dependencies I realized my issue. I missed the produces part in my Get/Put/PostMapping:
`
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;
...

@RestController
@RequestMapping("/")
public class SubmitController {

	@Autowired
	private SubmitService submitService;

	@PostMapping(value = "/submit", produces = MediaTypes.HAL_JSON_VALUE) // don't leave produces empty or default
	public EntityModel<T> submit(@Valid @RequestBody SubmitEntity submitEntity,
		SubmitAnswer submitAnswer = submitService.submit(submitEntity);
		return EntityModel.of(submitAnswer, linkTo(methodOn(getClass()).submit()).withSelfRel());
`
