### ISSUE TITLE
Support Java 17 records as RepresentationModel's

### ISSUE THREAD

**Issue by johanhaleby** [spring-projects/spring-hateoas#1962]
Currently, you can't use Java 17 records as `RepresentationModel`s, e.g:

```java
record Name(String first, String last) extends RepresentationModel<Name> {
}
```

yields a compile-time error:

```
Type parameter 'com.mycompany.Name' is not within its bound; should extend 'org.springframework.hateoas.RepresentationModel<? extends com.mycompany.Name>'
``` 

I guess this is a limitation in Java itself, but wonder if perhaps there's a workaround for records?

**Comment by odrotbohm** [comment]
I don't think this makes too much sense actually, as a record is supposed to be immutable and a `RepresentationModel`, by design, is not.

**Comment by johanhaleby** [comment]
@odrotbohm You're right! Guess my main issue is with the verbosity of regular POJO's. Thanks for your reply and for a great project!

**Comment by it-chhaya** [comment]
Dear everyone,
If we want to apply the DTO pattern with HATEOAS, we should have:
- Entity
- Model
- DTO
Is it right?

I am still confused about these points, please kindly help me.
Thank you.

**Comment by paraita** [comment]
> Dear everyone, If we want to apply the DTO pattern with HATEOAS, we should have:
> 
> * Entity
> * Model
> * DTO
>   Is it right?
> 
> I am still confused about these points, please kindly help me. Thank you.

Entities and DTOs are both part of the "model" domain technically speaking. DTOs are a consumer perspective of one or more entities. You can embed extra information into your DTOs for the consumer to get more context about your DTOs, that's HATEOAS. Guys correct me if I'm wrong
