### ISSUE TITLE
Optional support for Validation API still on `javax.…` namespace

### ISSUE THREAD

**Issue by Brummolix** [spring-projects/spring-hateoas#1965]
org.springframework.hateoas.mediatype.PropertyUtils still uses javax.validation Annotations and checks for the presence of Jsr303 (JSR_303_PRESENT) via javax.validation.constraints.Email.
As Spring Hateoas 2 runs on top of Spring 6 which uses the jakarta Namespace, shouldn't this be switchted to jakarta namespace too?

**Comment by odrotbohm** [comment]
Good catch! The virtues of unit tests still working fine on the old APIs. 🤦🏼‍♂️
