### ISSUE TITLE
Forwarded headers in WebfluxLinkBuilder not applied since 2.1.1

### ISSUE THREAD

**Issue by evainga** [spring-projects/spring-hateoas#2030]
We wanted to update our Spring Boot App from 3.1.1 to 3.1.3. However after this update our urls built with Hateoas are not using forwarded port and protocol anymore and creating a bug.

We found this commit, that has been part of the Hateoas update to 2.1.1 and is included in the Spring Boot update to 3.1.2: https://github.com/spring-projects/spring-hateoas/commit/df9ea168ca13e7887cb9c6224f601844a808680a 
With this change the method .fromHttpRequest() is replaced by .fromUri() and thus .adaptFromForwardedHeaders() is not in use anymore and this is the probable cause for the breaking change after the update in our app...

Was the change a decision on purpose or is it a bug? From our perspective, due to the changed behaviour, it should not have been part of a patch update after all.

**Comment by odrotbohm** [comment]
This has been a fix for this CVE. Forwarded heare application needs to be handled by configuring an appropriate strategy as described in the Spring Boot ([here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.webserver.use-behind-a-proxy-server)) and Spring Framework ([here](https://docs.spring.io/spring-framework/reference/web/webmvc/filters.html#filters-forwarded-headers))reference documentation. Following this approach, the ne code will see the adapted URI already.
