### ISSUE TITLE
Wrong nullability declarations for `with…(…)` method parameter of `Link`

### ISSUE THREAD

**Issue by tgeens** [spring-projects/spring-hateoas#2084]
Following up on #1602 

The fields `hreflang`, `media`, `title`, `type`, `deprecation`, `profile`, `name` are nullable and since https://github.com/spring-projects/spring-hateoas/commit/55aa4ff278feab968d9ddd80cf81d6f9924196bb correctly annotated with `@Nullable` :+1: 

My IDE still gives me warnings for nullability-issues when calling the withXYZ methods with a potential null-value.

Shall I send a PR for this ?

**Comment by odrotbohm** [comment]
Sure thing, appreciated! 🙇
