### ISSUE TITLE
Example usage for Resources class?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-hateoas#211]
I understand that the purpose of the `Resources` class is to provide a convenient wrapper for embedded entities or snippets that get mapped to the HAL `_embedded` property (or equivalent), but I'm having a hard time understanding how to actually use it. Are the `Link`s on that class intended to represent the `_links` for the top-level entity? Do I extend `ResourcesMixin` with my entity class that has embedded snippets? If so, why is `getContent()` re-declared `abstract` instead of inheriting from `Resources`?

Also, the `HalResourcesSerializer` and `HalEmbeddedBuilder` seem to bake in the assumption that only a single link type to a given entity class exists (using a `RelProvider`, which only considers the class). I have a `Person` class that can be the target of a number of different link types (`owner`, `uploader`, `payee`, etc.); is there any way to specify a link type for a given embedded entity, or will I need a roll-my-own `Map` at this point?

**Comment by pimlottc** [comment]
I found this to be a useful tutorial on using Resources to embed items for collection endpoints:

http://keaplogik.blogspot.com/2015/01/spring-hateoas-embedded-resources-with.html

**Comment by gregturn** [comment]
https://github.com/spring-projects/spring-hateoas-examples/blob/master/basics/src/main/java/org/springframework/hateoas/examples/EmployeeController.java shows an example hypermedia-powered controller with single-item and aggregate-root links.

It doesn't illustrate different usages of the same domain object (`Employee`) in this case, but by looking at how it uses a `SimpleRepresentationModelAssembler`, it's easy to see how you could define more than one assembler, using different `LinkRelation`s for each context.
