### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-hateoas#2176]
On https://spring.io/projects/spring-hateoas#learn there are some broken links:

* 2.3.1 links to https://docs.spring.io/spring-hateoas/docs/current/reference/html/, which shows the documentation for version 2.2.3.
* 2.4.0-SNAPSHOT links to https://docs.spring.io/spring-hateoas/docs/2.4.0-SNAPSHOT/reference/html/, which returns 404 Not Found.
* 2.0.7-SNAPSHOT links to https://docs.spring.io/spring-hateoas/docs/2.0.7-SNAPSHOT/reference/html/, which returns 404 Not Found.
* 1.5.5-SNAPSHOT links to https://docs.spring.io/spring-hateoas/docs/1.5.5-SNAPSHOT/reference/html/, which returns 404 Not Found.

**Comment by odrotbohm** [comment]
This should be fixed now.

**Comment by breun** [comment]
The links seem fine now, except `2.4.0-SNAPSHOT`, which still links to https://docs.spring.io/spring-hateoas/docs/2.4.0-SNAPSHOT/reference/html/, which still returns 404 Not Found.
