### ISSUE TITLE
Javadoc sites links appear to be broken for 2.3.x

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-hateoas#2178]
At the time of writing, it looks like javadoc site links aren't correct:

* https://docs.spring.io/spring-hateoas/docs/current/api/ gives "Spring HATEOAS 2.2.3 API". (this is linked from https://spring.io/projects/spring-hateoas#learn for the 2.3.1 release). I think it should be 2.3.1.
* https://docs.spring.io/spring-hateoas/docs/2.3.1/api/ gives a 404
* https://docs.spring.io/spring-hateoas/docs/2.3.x/api/ gives "Spring HATEOAS 2.3.0-RC1 API". I think it should be 2.3.1
* https://docs.spring.io/spring-hateoas/docs/2.3.x-SNAPSHOT/api/ gives "Spring HATEOAS 2.3.0-SNAPSHOT API". I think it should be 2.3.2-SNAPSHOT

**Comment by odrotbohm** [comment]
This should be fixed now
