### ISSUE TITLE
HalEmbeddedBuilder should consider curies for relation types

### ISSUE THREAD

**Issue by edrik** [spring-projects/spring-hateoas#221]
At the moment it would be hard to use *Resources* for implementing the [Hypertext Cache Pattern](http://tools.ietf.org/html/draft-kelly-json-hal-06#section-8.3) if using a CurieProvider.

According to the [HAL spec](http://tools.ietf.org/html/draft-kelly-json-hal-06#section-4.1)  the type of rel for "_link" and "_embedded" should be considered equal. So embedding resources should also result in a rel with a curie when provided.

**Comment by olivergierke** [comment]
Implemented by the fix for #229, #233.
