### ISSUE TITLE
Uri Template {?value*} does not generate templated:true

### ISSUE THREAD

**Issue by jbigman** [spring-projects/spring-hateoas#227]
hi,

Creating a link with a template like {?value*} is not marked as templated on json generation.

http://localhost/api/rest/v1/userGroups/50/functions/{?ids} generates:

```
acm:group.functions.update: {
    href: "http://localhost/api/rest/v1/userGroups/50/functions/{?ids}",
    templated: true
}
```

http://localhost/api/rest/v1/userGroups/50/functions/{?id*} generates:

```
acm:group.functions.update: {
    href: "http://localhost/api/rest/v1/userGroups/50/functions/{?id*}"
}
```

**Comment by pcornelissen** [comment]
It would be really nice to have the templated field set appropriatlely. Right now I am my own consumer, so it doesn't matter that much, but for correctness sake the field should be set if the url is a templated uri

**Comment by gregturn** [comment]
Looks like this was patched in a previous commit against `UriTemplate`. Just adding a test case to confirm.
