### ISSUE TITLE
Add a resources property to the Resource class

### ISSUE THREAD

**Issue by jstano** [spring-projects/spring-hateoas#242]
It's not clear how to get the _embedded stuff in the Hal renderer working without having a new property in the Resource class or having a class derived from Resource with a resources property.

If you can provide an example of how to accomplish this without any changes to the project, that might be helpful.

Here's what I'm proposing:
   new Resource(someDTO)
      .withResources(someCollectionOfResources)
      .withResources(otherCollectionOfResources)

If no resources are added to the Resource, then nothing will be output by the renderers.

I'll create a Pull Request so we look over the code.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/issues/864.
