### ISSUE TITLE
HTTP PUT doesn't do update, but new

### ISSUE THREAD

**Issue by bashekking** [spring-projects/spring-hateoas#250]
HTTP PUT doesn't seem to work ok with PagingAndSortingRepository.
Not in my code (see below) but also not in spring-boot-sample-rest code (https://github.com/spring-projects/spring-boot/issues/1514) 

When I try to do an update with HTTP PUT of a simple json object 'brand', a new brand is created.
I use only a standard respository (see below) with a simple brand model (see below). When I do an update in code using the repository, the brand is actually modified.

Any help would be really appreciated, i'm breaking my head over this

My curl output (the field 'Location: http://localhost:8181/brands/13' shows that a new brand is created): 

$ curl -v -X PUT -d '{"name":"Alibastine"}' -H "Content-Type: application/json" http://localhost:8181/brands/1
- Hostname was NOT found in DNS cache
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 8181 (#0)
  > PUT /brands/1 HTTP/1.1
  > User-Agent: curl/7.35.0
  > Host: localhost:8181
  > Accept: _/_
  > Content-Type: application/json
  > Content-Length: 21
  > 
- upload completely sent off: 21 out of 21 bytes
  < HTTP/1.1 204 No Content
- Server Apache-Coyote/1.1 is not blacklisted
  < Server: Apache-Coyote/1.1
  < Access-Control-Allow-Origin: *
  < Access-Control-Allow-Headers: X-Requested-With, Origin, Content-Type, Accept
  < Location: http://localhost:8181/brands/13
  < Date: Thu, 04 Sep 2014 17:33:10 GMT

BrandRepository.java:
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.history.RevisionRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.builder.ws.models.entities.Brand;

@RepositoryRestResource(collectionResourceRel = "brands", path = "brands")
public interface BrandRepository extends PagingAndSortingRepository<Brand, Long>
    {
}

Brand.java:
import java.net.URL;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.validation.constraints.Size;

@Entity
public class Brand {
      @Id
    @GeneratedValue
    public Long id;

```
@Column(nullable = false)
@Size(min = 2, max = 30)
private String name;

public Brand(){

}

public Brand(String name){
    this.name=name;
}

public String getName() {
    return name;
}

public void setName(String name) {
    this.name = name;
}
```

}

Regards,

Bas

**Comment by gregturn** [comment]
Based upon https://github.com/spring-projects/spring-boot/issues/1514 and https://github.com/gregturn/brands, this issue is deemed invalid.

Regarding the newly added issue, please open a new ticket if you are still having issues. It's hard to sort out two unrelated things in one ticket.
