### ISSUE TITLE
XML configuration equivalent of @EnableHypermediaSupport

### ISSUE THREAD

**Issue by woemler** [spring-projects/spring-hateoas#259]
There currently does not seem to be any way to configure Spring-HATEOAS in a project that is using pure XML configuration, as the @EnableHypermediaSupport annotation is required in a Java config class.  While by no means a necessity, it would be nice to have the option to configure Spring-HATEOAS in XML to allow easier bootstrapping to existing projects.

**Comment by schvanhugten** [comment]
This works for me in Spring 3.2.9:

```xml
	<mvc:annotation-driven content-negotiation-manager="contentNegotiationManager" enableMatrixVariables="true"/>
	<context:component-scan base-package="nl.relate4u.innovation.api" />
	
	<bean id="contentNegotiationManager" class="org.springframework.web.accept.ContentNegotiationManagerFactoryBean">
	<!-- Turn off working out content type based on URL file extension, should fall back to looking at the Accept headers -->
	    <property name="favorPathExtension" value="false" />
	</bean>
	
    <bean id="restBeanRegistry" class="nl.relate4u.innovation.web.registry.RestBeanRegistry"
          factory-method="getInstance" scope="singleton">
    </bean>
```

**Comment by waldemar-schneider** [comment]
I posted an answer to [Stackoverflow](http://stackoverflow.com/questions/21040951/how-to-enable-hal-rendering-without-using-enablehypermediasupport-with-spring-h/25505826#25505826) with an example how i configured Spring (3.2.10) with Hateoas with XML-Configuration.

**Comment by gregturn** [comment]
People mostly use Java configuration instead of XML. Are there up-to-date apps still needing XML support? And do we want to engage on this front?

**Comment by mattluce** [comment]
Any plans to implement this?

**Comment by odrotbohm** [comment]
No, not with the chance of XML support in Spring potentially being deprecated in Spring 6 and a reasonable workaround existing.
