### ISSUE TITLE
PagedResourcesAssembler.getDefaultUriString() does not handle protocol properly (proxy)

### ISSUE THREAD

**Issue by matthewdfleming** [spring-projects/spring-hateoas#260]
The following code gets called at some point in the linkTo(methodOn... sequence:

```
private UriComponents getDefaultUriString() {
    return baseUri == null ? ServletUriComponentsBuilder.fromCurrentRequest().build() : baseUri;
}
```

This code doesn't deal with the protocol properly when proxied. So what I have is that some of my links are http and others are https. The links that happen via the ControllerLinkBuilderFactory are correct as they use the ControllerLinkBuilder.getBuilder() method that understands the "X-Forwarded-Ssl" header (which we are including in our virtual host).

I haven't fully tested but what seems to be working properly is the following (instead):

```
private UriComponents getDefaultUriString() {
    return baseUri == null ? getBuilder().build() : baseUri;
}

private static UriComponentsBuilder getBuilder() {

    HttpServletRequest request = getCurrentRequest();
    ServletUriComponentsBuilder builder = ServletUriComponentsBuilder.fromRequestUri(request);
...
```

The rest of the getBuilder() and getCurrentRequest() methods are monkey patched/copied from the ControllerLinkBuilder.

**Comment by vlfors** [comment]
This problem is urgent?

**Comment by otrosien** [comment]
@olivergierke this is basically another mis-alignment between X-Forwarded-Ssl support in hateoas, and missing support inside UriComponentsBuilder. See discussion in https://github.com/spring-projects/spring-hateoas/pull/519.

**Comment by olivergierke** [comment]
I see. However, `PagedResourcesAssembler` is part of Spring Data Commons, so we need to file a ticket over there to get anything done. I'd actually even go as far as that this should be brought up with the core Spring Framework team rather as `ServletUriComponentsBuilder` is maintained there.
