### ISSUE TITLE
How to configure MappingJackson2HttpMessageConverter registered by spring-hateoas?

### ISSUE THREAD

**Issue by ceefour** [spring-projects/spring-hateoas#262]
I'm sorry for misusing the issues as a forum, however there's already this question at StackOverflow http://stackoverflow.com/questions/24694493/how-to-configure-mappingjackson2httpmessageconverter-registered-by-spring-hateoa 3 months old and no solution.

**Comment by gregturn** [comment]
Superceded by #833.
