### ISSUE TITLE
Colon in Object passed to slash method on LinkBuilderSupport incorrectly splits the URI

### ISSUE THREAD

**Issue by jvans** [spring-projects/spring-hateoas#268]
Here is the test case that fails. 

```java
@Test
  public void test() {
    String myUrl = linkTo(DocsController.class, "123", "joebloggs@gmail.com")
      .slash("66532_1400130256920:title-CA1218187.pdf").toString();
    assertThat(myUrl, Matchers.endsWith("CA1218187.pdf"));
  }
```

linkTo returns "http://localhost/docs/accounts/123/users".

DocsControllerClass is annotated as follows:

```java
@Controller
@RequestMapping("/docs/accounts/{accountNumber}/users")
```

The full URL should end up looking like 
http://localhost/docs/accounts/123/users/66532_1400130256920:title-CA1218187.pdf

but instead ends up looking like
http://localhost/docs/accounts/123/users.

This is due to the fact that UriComponentBuilder.fromUriString is meant to parse a full URI, not just a fragment. It sees 66532_1400130256920 as the scheme and CA1218187.pdf as the scheme specific part.

**Comment by gregturn** [comment]
Duplicate #477

**Comment by gregturn** [comment]
I actually just ran this very test case, and it passes thanks to https://github.com/spring-projects/spring-hateoas/commit/d68700231eb1d8afaf27328cc5d576a71e966a2a.

```
@Test
public void test() {
    String myUrl = linkTo(DocsController.class, "123", "joebloggs@gmail.com")
            .slash("66532_1400130256920:title-CA1218187.pdf").toString();
    assertThat(myUrl).endsWith("CA1218187.pdf");
}

@Controller
private static class DocsController {

    @GetMapping("/docs/accounts/{accountNumber}/users")
    public RepresentationModel<?> foo() {
        return new RepresentationModel<>();
    }
}
```

<img width="206" alt="Screen Shot 2020-04-18 at 8 20 42 AM" src="https://user-images.githubusercontent.com/311040/79638871-8ca04500-814d-11ea-90a9-cf3ac1535b3f.png">
