### ISSUE TITLE
linkTo(methodOn(...)) sometimes misses slashes

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-hateoas#269]
I regulary use requestmapping that is partly defined on the class and on the method. This is an example:
```java
@RestController
@RequestMapping("user")
public class UserController {
    @Autowired
    BackofficeUserRepository repository;

    @RequestMapping(value = "{id}", method = RequestMethod.GET)
    public Resource<BackofficeUser> getUser(@PathVariable("id") UUID id) {
        Resource<BackofficeUser> resource = new Resource<>(repository.findUser(id));
        resource.add(linkTo(methodOn(UserController.class).getUser(id)).withSelfRel());
        return resource;
    }
}
```

This is perfectly legal spring mvc and it adds the missing slash between "user" and "{id}". But when I use the linkbuilder it doesn't do that. The result of the code above is  a link like "http://localhost/user105a8719-8d59-422d-84ba-cf53b9c93447".

As a workaround I can add the slash in my mapping, but I think the linkbuilder should come to the same conclusion as spring mvc when it comes to generating the links based in requestmapping annotations. ;-)

I'm using the version 0.16 BTW.

**Comment by dlvenable** [comment]
I am seeing this issue in version 0.17 as well.

**Comment by cpelka** [comment]
Same for me. If I got the HATEOAS principle right, it should be possible to navigate through the links returned by the server without the need to modify them.

That's at the moment not possible (or I miss something like @pcornelissen and @dlvenable before).

I'm responding in a dynamic way listening to only on known endpoint in my API: **/api** and I implemented a method listening at that and sending a set of links like this:

```java
Set<Link> links = new HashSet<>();
links.add(linkTo(MyEntityController.class).withRel(MyEntity.class.getSimpleName()));
Resources<Object> resources = new Resources<>(Collections.emptySet(), links);
return new ResponseEntity<>(resources, HttpStatus.OK);
```

Three ways to configure the controller, tested with that:

```java
@RequestMapping("/api/myentities")
```
result: http://localhost:6010/api/myentities

```java
@RequestMapping("/api/myentities/")
```
result: http://localhost:6010/api/myentities

```java
@RequestMapping("/api/myentities/*") 
```
result: http://localhost:6010/api/myentities/*

So, browsing the returned link will not work in default Spring (Boot) configuration as the controllers only listen to resource URLs with trailing slashed (unless it's a parameter).

Do we miss something here?

**Comment by olivergierke** [comment]
This is fixed by #423 being merged.

**Comment by nealeu** [comment]
Sorry to do archeology here, but @odrotbohm, you say that this is fixed, yet:

    @RequestMapping("/api/myentities/")

result: http://localhost:6010/api/myentities

is still the case all these years later, and isn't a covered test case in https://github.com/spring-projects/spring-hateoas/blob/master/src/test/java/org/springframework/hateoas/server/core/AnnotationMappingDiscovererUnitTest.java

For everyone's sake I'll open an issue for this behaviour to not break people's apps

**Comment by odrotbohm** [comment]
Just for reference, the original poster wasn't reporting trailing slashes but ones missing in between. Thanks for opening up the new ticket. I'll have a look.
