### ISSUE TITLE
How to add HTTP Method in Link

### ISSUE THREAD

**Issue by kumartheashwani** [spring-projects/spring-hateoas#274]
Current Link Class doesn't support HTTP Method. Is there a historical reason not to support it.
I am using spring-hateoas in project and our clients need HTTP Method. Can we extend existing Link class to support method as well.

**Comment by olivergierke** [comment]
There's no historical reason. Which HTTP methods a link supports belongs in the specification of the link relation, not each and every rendering of a link.

**Comment by dschulten** [comment]
Within the confines of Hal that is true. If you are looking for a way to represent other media-types which give clients a hint about possible methods, you might want to take look at hydra-java. It builds upon spring-hateoas, but has an AffordanceBuilder which describes not just a hyperlink like the Link class but a more rich hypermedia affordance.

Disclaimer: I am the author of that project and I started it to add Affordances to spring-hateoas in other media-types, which seem under-represented in spring-hateoas. Meant as an extension, not a competition to spring-hateoas.
