### ISSUE TITLE
Traverson should not distinguish between _links and _embedded

### ISSUE THREAD

**Issue by cskinfill** [spring-projects/spring-hateoas#276]
In HAL a resource linked to in the _links and an embedded resource in the _embedded should (well sort of) be interchangeable.  It would be great if Traverson was given a rel like "people" would look in the _links and in _embedded.  I think change is really in the HalLinkDiscoverer needs to be able to check _links and then also check _embedded.

**Comment by olivergierke** [comment]
So assuming you'd ask for the `self` link of a resource and find multiple ones in the representation, which one do you suggest we should return?

**Comment by gregturn** [comment]
Given the lack of followup to how to resolve ambiguous cases, I'm closing this ticket.
