### ISSUE TITLE
Publish JavaDoc and reference documentation

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-hateoas#278]
Hello

Through http://projects.spring.io/spring-hateoas/ the API link targets to the same link, here on Github there is no a link to read the API/javadoc, the unique way is through the source code itself.

Thanks.

**Comment by tommyb82** [comment]
I was just looking for the same - can't find published javadoc API anywhere. Would be very useful.

**Comment by olivergierke** [comment]
That should be fixed. JavaDoc preview can be found [here](https://docs.spring.io/spring-hateoas/docs/0.17.0.BUILD-SNAPSHOT/api/), reference docs as [HTML](https://docs.spring.io/spring-hateoas/docs/0.17.0.BUILD-SNAPSHOT/reference/html/index.html) or [PDF](https://docs.spring.io/spring-hateoas/docs/0.17.0.BUILD-SNAPSHOT/reference/pdf/spring-hateoas-reference.pdf).

**Comment by tommyb82** [comment]
Great, thanks Oliver!

**Comment by manueljordan** [comment]
Thank you very much Oliver!
