### ISSUE TITLE
Collection<Long> request parameter for WhereIn repository method mapped

### ISSUE THREAD

**Issue by syncro** [spring-projects/spring-hateoas#280]
Hi
I'm trying to expose findIn jpa method and  when trying to pass params as array of values (I'm using restsh)
get entries/search/findByIdIn --params "{ids: [6, 7]}"
getting the following error:
< 400 BAD_REQUEST
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Sat, 17 Jan 2015 11:28:06 GMT
< Connection: close
< 
{
  "cause" : {
    "cause" : null,
    "message" : "For input string: \"%5B6%2C7%5D\""
  },
  "message" : "Failed to convert from type java.lang.String to type @org.springframework.data.repository.query.Param java.lang.Long for value '%5B6%2C 7%5D'; nested exception is java.lang.NumberFormatException: For input string: \"%5B6%2C7%5D\""

although requesting with one value works just fine:
get entries/search/findByIdIn --params "{ids: 6}"

repostory interface method sign is the following:
	DMEntry findByIdIn(@Param("ids") Collection<Long> ids);

Cat you please advise on how I can pass the collection of values in request ?

**Comment by olivergierke** [comment]
You need to either use a plain `String` (i.e. `?ids=6,7`) or list the values individually (i.e. `?ids=6&ids=7`). JSON values are not supported for GET requests. Going forward, please file issues for Spring Data related topics in the corresponding [bug tracker](https://jira.spring.io/browse/DATACMNS).
