### ISSUE TITLE
Enhance UriTemplate builder to build links for request param based urls

### ISSUE THREAD

**Issue by grafjo** [spring-projects/spring-hateoas#281]
Hi guys,
I'm in the situation to describe a link to a search url using request parameters e.g `http://example.com/search?q=chien&lang=fr`.
The formal link description is `http://example.com/search{?q,lang}` -  [rfc6570](http://tools.ietf.org/html/rfc6570#section-1.1)

At the moment it's possible to build this link, but it's cumbersome:
```java
TemplateVariable queryParam = new TemplateVariable("q", 
        TemplateVariable.VariableType.REQUEST_PARAM);
TemplateVariable langParam = new TemplateVariable("lang", 
        TemplateVariable.VariableType.REQUEST_PARAM);

new UriTemplate("http://example.com/search")
    .with(new TemplateVariables(queryParam))
    .with(new TemplateVariables(langParam));
```

I suggest to enhance the UriTemplate with some builder methods like that:
```java
new UriTemplate("http://example.com/search")
    .with("q", TemplateVariable.VariableType.REQUEST_PARAM)
    .with("lang", TemplateVariable.VariableType.REQUEST_PARAM);

new UriTemplate("http://example.com/search")
    .withRequestParam("q")
    .withRequestParam("lang");
```

What do you think?

**Comment by olivergierke** [comment]
I've added `UriTemplate.with(String name, VariableType type)`.

**Comment by grafjo** [comment]
thank you!
