### ISSUE TITLE
Conditionally use CURIEs

### ISSUE THREAD

**Issue by vivin** [spring-projects/spring-hateoas#284]
Is there a way to build links to use CURIEs only in specific cases? Currently the documentation says that it will prefix any non-IANA-registered rel with the CURIE.

**Comment by olivergierke** [comment]
Simply extend `DefaultCurieProvider` and alter `getNamespacedRelFor(String rel)` as you like.

**Comment by vivin** [comment]
Awesome. Thank you very much!
