### ISSUE TITLE
Allow EmbeddedWrappers.wrap to wrap empty collections

### ISSUE THREAD

**Issue by trygvis** [spring-projects/spring-hateoas#286]
If this pattern is used in a controller:

    return new Resources<>(asList(wrappers.wrap(assembler.toResources(devices), Rels.DEVICE)));

It is very useful if `wrap()` would allow empty collections.

**Comment by ywmail** [comment]
please help to have a look at this question:
http://stackoverflow.com/questions/40648829/how-to-consume-empty-collection-without-hal-response-structure-in-spring-data-re
