### ISSUE TITLE
How do I force an array of links for a rel that has only one element in HAL?

### ISSUE THREAD

**Issue by elnur** [spring-projects/spring-hateoas#294]
When adding multiple links with the same rel, it works as expected:

```json
{
    "_links": {
        "items": [{
            "href": "/first_item"
        }, {
            "href": "/second_item"
        }]
    }
}
```

Now, suppose, we have only one item to be shown. It will render as:

```json
{
    "_links": {
        "items": {
            "href": "/first_item"
        }
    }
}
```

And that is not right because each client will have to handle this exceptional case.

This is how it's supposed to be rendered:

```json
{
    "_links": {
        "items": [{
            "href": "/first_item"
        }]
    }
}
```

Does the library support a way to enforce a link to be treated as a collection? If it does, how do I do that?

**Comment by olivergierke** [comment]
I guess this is a duplicate of #288, right?

**Comment by elnur** [comment]
Yes, indeed. Thanks!

BTW, I'm glad you're back on the project. I already started to think it's dead/abandoned. :wink:
