### ISSUE TITLE
Upgrade JsonPath Version

### ISSUE THREAD

**Issue by mxsb** [spring-projects/spring-hateoas#297]
You rely on a 0.9.x JsonPath Version, please upgrade to a 1.x JsonPath version.
Afaik the latest version is 1.2.0.

With the new JsonPath an Exception is thrown.
java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Lcom/jayway/jsonpath/JsonPath;

See https://jira.spring.io/browse/SPR-12299 for the same topic on the Spring Framework.

**Comment by olivergierke** [comment]
Fixed with #305.
