### ISSUE TITLE
ResourceAssemblerSupport createResourceWithId doesn't take current request path variables for creating self uri

### ISSUE THREAD

**Issue by BertDuerinck** [spring-projects/spring-hateoas#303]
when an endpoint has path variables inside his uri, then when the ResourceAssemblerSupport method createResourceWithId() also needs those path variables to create the self rel. It would be great that the class extends the parameters with the current path variables himself.

**Comment by olivergierke** [comment]
Could you elaborate a bit more on this? What is the request you get? What code do you call on `ResourceAssemblerSupport`? What is the outcome of this? What is the expected outcome?

**Comment by BertDuerinck** [comment]
I call on <code>ResourceAssemblerSupport</code> the following method :

<code>protected D createResourceWithId(Object id, T entity, Object... parameters)</code>

If i want the following self rel to be created for the entity:

<code>/customer/{customerId}/loyaltyprogramsubscription/{loyaltyProgramSubscriptionId}</code>

Then i need to pass myself customerId in the list of parameters of <code>createResourceWithId</code>, which i don't have at that moment.

I see for the moment 2 solutions:

1) pass customerId to the ResourceAssembler, but then i have to make a wrapper object containing the entity and the customerId. This is not really what i want to do.

2) Or, i'll fetch the <code>URI_TEMPLATE_VARIABLES_ATTRIBUTE</code> attributes from the current request, and pass them as parameters.

Could the hateoas framework do the second solution out-of-the box for us?

**Comment by geoff-wasilwa** [comment]
@BertDuerinck is this still a problem?

**Comment by Vincent-Pang** [comment]
Hi, (I think) I am facing the similar problem.

My restful link is something like
/categories/{categoryId}/products/{productId}

I have a ProductController like this
```
@RestController
@RequestMapping("/categories/{categoryId}/products")
public class ProductController
{
    @RequestMapping(method = RequestMethod.GET)
    public ResponseEntity getCategoryProductList(@PathVariable int categoryId)
    {
        // i have to new ResourceAssembler everytime here ...
        ProductResourceAssembler assembler = new ProductResourceAssembler(categoryId);

        List resourceList = assembler.toResources( ... );

        return ResponseEntity.ok(resourceList);
    }
}
```

And my ProductResourceAssembler
```
public class ProductResourceAssembler extends ResourceAssemblerSupport<Product, ProductResource>
{
    private int categoryId;

    public ProductResourceAssembler(int categoryId)
    {
        ...
        this.categoryId = categoryId;
    }

    @Override
    public ProductResource toResource(Product entity)
    {
        ProductResource resource = createResourceWithId(entity.id, entity, categoryId);
        ...
        return resource;
    }
}
```

I have to new ResourceAssembler in every request because of different "categoryId". Is my implementation good enough? or is there any improvement (e.g. not to new the assembler for every request, and re-use it somehow)?

**Comment by gregturn** [comment]
Reading the various use cases, I think a clarification is in order. `RepresentationModelAssemblerSupport` (as it's now named) is designed to do a very explicit thing: **afford you `self` links that end in `/{id}`**

The code at its heart is: `linkTo(this.controllerClass, parameters).slash(id).withSelfRel()`.

This says, grab the controller class (which will read the class-level Spring Web annotations) and apply literally `/{id}` with whatever you `id` is.

If the models you are building have a differently designed URI for `self`, then `RepresentationModelAssemblerSupport` is not for you.

Never fear. I recommend going back to it's parent interface, `RepresentationModelAssembler` and considering that as your basis for building up a product. Given `RepresentationModelAssembler` has simply this:

```java
D toModel(T entity);
```
...as its signature, every assembler built on this has the power to use any contextual information an incoming entity provides to build your model.

Or...consider `SimpleRepresentationModelAssembler`, which is an immediate subinterface thereof.

Neither of these interfaces have the `/{id}` requirement baked in, and thus empowers you to define your own representation while still doing a bit of legwork for you.

Based on this, I'm closing this issue. Good luck!
