### ISSUE TITLE
UriTemplate cuts off uri part after last path variable

### ISSUE THREAD

**Issue by BertDuerinck** [spring-projects/spring-hateoas#312]
I have an URI where the last part of the URI is not a path variable:

<code>/customer/{customerId}/programs</code>

when using it in a Link object:

<code>
ResourceSupport resource = new ResourceSupport();
resource.add(new Link("/customer/{customerId}/programs", "programs"));
</code>

then the outcome is <code>/customer/{customerId}</code> in the href of the link.

this should be <code>/customer/{customerId}/programs</code>

**Comment by olivergierke** [comment]
I can see this passing in the current snapshots:

```java
Link link = new Link("/customer/{customerId}/programs", "programs");
assertThat(link.getHref(), is("/customer/{customerId}/programs"));
```

Would you mind trying `0.17.0.BUILD-SNAPSHOT` and see if you still see the error with it?

**Comment by BertDuerinck** [comment]
Yes, this is working correctly

**Comment by olivergierke** [comment]
Thanks for verifying!
