### ISSUE TITLE
JSON-Path in HalLinkDiscoverer doesn't work for URI rels

### ISSUE THREAD

**Issue by aheusingfeld** [spring-projects/spring-hateoas#314]
As of [RFC5988](http://tools.ietf.org/html/rfc5988) link relations can be URIs pointing to a document describing the target of the link. 

Given I have the following JSON:
```
{
    "_links": {
        "http://example.com/rels/widget/submit-voting": {
            "href": "http://localhost/votings/submit-voting"
        },
        "self": {
            "href": "http://localhost/votings"
        }
    },
    "items": {}
}
```
the JSON-Path expression `$_links..%s.href` in `org.springframework.hateoas.hal.HalLinkDiscoverer` doesn't work for those URIs. When it is used in `JsonPathLinkDiscoverer.getExpression(String)` it results in an `com.jayway.jsonpath.InvalidPathException`.

**Comment by olivergierke** [comment]
This should be fixed. Feel free to give the snapshots a try.
