### ISSUE TITLE
ResourceSupport might benefit from having a method that returns a list of links that have the same rel.

### ISSUE THREAD

**Issue by vivin** [spring-projects/spring-hateoas#318]
Currently there is a method called `getLink(String rel)` that returns a link with the given rel. However, it is possible to have multiple links that share the same rel. Therefore, I think it might be beneficial to have a method like so:

``` java
public List<Link> getLinks(String rel);
```

Which will return a list of links that have the given rel.

**Comment by chrylis** [comment]
#157

**Comment by vivin** [comment]
Ahh thanks! I did not see the original issue. @olivergierke thoughts about this?

**Comment by chrylis** [comment]
That's not a 100% duplicate, but I think we're looking at the same issue. Essentially, the current `getLink` (1) returns a single value and (2) doesn't play nicely with the map-navigation syntax offered by Groovy and *EL. What I'd prefer to see in place of your signature is

    Map<String, Collection<Link>> getLinks();

That way, something like `myobj.links['picture'].href` would work.

**Comment by vivin** [comment]
I think changing the signature of the existing one would be a breaking change, unfortunately. The new method I suggested would sort of do what you want, except instead of working with a map directly, you're asking the `ResourceSupport` class to filter out links with the rel you want. The performance would be lacking since it would be `O(n)` since you have to traverse the entire list. I think that could be mitigated if the internal representation is modified from `List<T>` into `Map<K, V>`.

**Comment by chrylis** [comment]
It absolutely would be a breaking change, but we're still at major version 0. (I note additionally that HAL seems to specify that link rels are unique per entity, which means that the current list-based implementation is also problematic in permitting duplicates.) Changing the internal representation is what I recommended a while back, but I haven't heard any comments.

**Comment by dschulten** [comment]
Hi,

although I find it problematic, too, to use duplicates, HAL specifically 
allows them in section 4.1.1 where it says that the value of the rel may be 
an array of link objects. It uses this feature explicitly for curies.

Best,
Dietrich



Am 23. März 2015 04:24:11 schrieb Christopher Smith <notifications@github.com>:

**Comment by chrylis** [comment]
Aha. Well, in that case, something with the semantics of a multimap are probably best.

**Comment by vivin** [comment]
Yes, a rel can represent multiple links and HAL does allow that. Internally a `Map<String, List<Link>>` would make much more sense, I think, but I haven't heard any comments either about this issue (and some others as well).

**Comment by olivergierke** [comment]
What if we just added `List<Link> getLinks(String rel)`?

**Comment by chrylis** [comment]
That would be an improvement, but it's still awkward in contexts (Groovy, SpEL) that support map-style syntax.

**Comment by olivergierke** [comment]
`foo.getLinks(…).href`?

**Comment by chrylis** [comment]
Works okay if you're looking for links for a specific rel (though still more cumbersome than `foo.links.picture[0].href`, since `getLinks` isn't a property accessor), but there's no simple way to iterate over rels.

**Comment by gregturn** [comment]
Your saying to offer a keys() and values() pair of ops, similar to a Map.

**Comment by chrylis** [comment]
@gregturn I've actually suggested just making the links a `Map<String,Link>` (or `Map<String,Collection<Link>>`. The interface makes a lot more sense to me.

**Comment by vivin** [comment]
@olivergierke `List<Link> getLinks(String rel)` would work. To address @chrylis concerns, perhaps a method `Map<String, List<Link>> getLinks()` would work.

**Comment by gregturn** [comment]
Related to #542

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/pull/566/commits/0e8b0e13cac1ff3bc36fbefa25168e404f398795
