### ISSUE TITLE
Improve curie rendering in case no namespaced links are present

### ISSUE THREAD

**Issue by sesto** [spring-projects/spring-hateoas#320]
Example:

```javascript
{
  "_links": {
    "self": {
      "href": "blah"
    }
  },
  "_embedded": {
    "customer": {
      "customerId": 12345,
      "_links": {
        "self": {
          "href": "Blah"
        }
      }
    }
  }
}
```

**Comment by olivergierke** [comment]
The output in itself doesn't look wrong? You say you have a `CurieProvider` registered? Which Spring HATEOAS version do you use? 0.17 ships a fix for curies not getting applied everywhere.

**Comment by sesto** [comment]
I use 0.17 and have CurieProvider registered.
I am talking about the case when embedded resources is not a collection, which according to HAL specs is perfectly possible:  "It is an object whose property names are link relation types (as
   defined by [RFC5988]) and values are either a Resource Object or an
   array of Resource Objects".
We have something like this:
{
  "_links": {
    "self": {
      "href": "blah"
    }
  },
  "_embedded": {
    "resourceA": {
      "id": 9876,
      "_links": {
        "self": {
          "href": "Blah1"
        }
      }
    },
    "resourceB": {
      "id": 12345,
      "_links": {
        "self": {
          "href": "Blah"
        }
      }
    }
  }
}

Here, there are actually 2 problems:
- it is not clear, whether API supports this kind of embedding. Resources class supports only imbedding of collections. We have to use our own implementation.
- no curie namespaces are added to the embedded resources as well as no curies link added to the root resource
I would expect to have something like this:
{
  "_links": {
    "self": {
      "href": "blah"
    },
    "curies": [
      {
        "href": "/resources-{rel}",
        "name": "ab",
        "templated": true
      }
    ]
  },
  "_embedded": {
    "ab:resourceA": {
      "id": 9876,
      "_links": {
        "self": {
          "href": "Blah1"
        }
      }
    },
    "ab:resourceB": {
      "id": 12345,
      "_links": {
        "self": {
          "href": "Blah"
        }
      }
    }
  }
}

**Comment by tomhylsan** [comment]
Possibly related to this is that curies are also not added even though non-iana rel's exist. This seems like a HAL contract breach and it breaks the HAL browser. 

It usually happens when rels are prefixed prior to being serialized in Jackson2HalModule#serialize. 

A workaround is currently to change:
```
if (!link.getRel().equals(rel)) {
    curiedLinkPresent = true;
}
```
to:
```
curiedLinkPresent = !IanaRels.isIanaRel(rel) && rel.contains(":");
```

**Comment by olivergierke** [comment]
This should be fixed. I altered the curie rendering to inspect embedded items. We now also skip the curie rendering for nested resources assuming *all* curies being present on the root level.
