### ISSUE TITLE
Switch to Groovy-based Maven POM

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-hateoas#323]

**Comment by vivin** [comment]
Are you guys planning to switch to gradle at all? Just curious.

**Comment by olivergierke** [comment]
No.

**Comment by vivin** [comment]
Thanks!

On Thu, Mar 19, 2015 at 11:07 AM, Oliver Gierke <notifications@github.com>
wrote:

> No.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-projects/spring-hateoas/issues/323#issuecomment-83696716>
> .
>



-- 
Ruin untold;
And thine own sadness,
Sing in the grass,
When eve has forgot, that no more hear common things that gleam and pass;
But seek alone to lip, sad Rose of love and ruin untold;
And thine own mother
Can know it as I know
More than another
What makes your own sadness,
Set in her eyes.

$s="01:11:02:11:01:11:02:13:01:11:01:11:01:13:02:12:01:13:01:11:
    04:11:06:12:04:11:01:12:01:13:02:12:01:14:01:13:01:11:03:12:
    01:11:04:12:02:11:01:11:01:13:02:11:03:11:06:11:01:11:05:12:
    02:11:01:11:01:13:02:11:02:12:01:12:04:11:06:12:01:11:04:12:
    04:11:01:12:03:12:01:12:01:11:01:12:01:12:02:11:01:11:01:13:
    02:11:01:02:11:01:12:02";
@a=split(/:/,$s);$j="";foreach$c(@a) {@n=split(//,$c);$j.=$n[0]x$n[1];}
for($i=0;$i<$j=~y///c;$i+=8){print
chr(unpack("N",pack("B32",substr("0"x32 .substr($j,$i,8),-32))));}

**Comment by gregturn** [comment]
Mind I close this one @olivergierke?

**Comment by olivergierke** [comment]
Feel free to. I guess the biggest obstacle currently is that most of our release automation is much better in manipulating an XML file than some Groovy script.
