### ISSUE TITLE
How to set custom serializer for ResourceSupport in spring

### ISSUE THREAD

**Issue by vltsu** [spring-projects/spring-hateoas#324]
Hello! 
I have the same problem as in #288, and I wrote my own serializer to replace Jackson2HalModule.HalLinkListSerializer. But how to tell spring to use this serializer? I tried to write 

```
public abstract class MyOwnResourceSupportMixIn extends ResourceSupport {
    @Override
    @XmlElement(name = "link")
    @JsonProperty("_links")
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_EMPTY, using = MyOwnSerializer.class)
}
```

and set 

```
public class MixInModule extends SimpleModule {
    public MixInModule() {
        setMixInAnnotation(ResourceSupport.class, MyOwnResourceSupportMixIn.class);
```

and register this MixInModule in spring configuration, but it leads to stackoverflow error.

I see the mention of _HalHandlerInstantiator_ in one of the issues, maybe I should use this method. But can you give me some example of how to use it in spring?

**Comment by vivin** [comment]
@vltsu It is possible to do this. Take a look at my comment on #288. You can use the same ideas to accomplish what you are trying to do.

**Comment by vltsu** [comment]
@vivin thank you for reply. Also the solution can be found here http://stackoverflow.com/questions/29129257/how-to-display-a-link-on-a-particular-rel-as-an-array-even-if-there-is-only-one

**Comment by vivin** [comment]
Cool! Seems to be along similar lines as my solution.

**Comment by gregturn** [comment]
Superseded by #833.
