### ISSUE TITLE
linkTo methodOn includes port 443 with HTTPS

### ISSUE THREAD

**Issue by dlvenable** [spring-projects/spring-hateoas#327]
When using:

linkTo(methodOn(MyController.class).getSomething(value)).toUri()

The resulting URI includes port 443.
https://myhost.com:443/my/controller

It should only be
https://myhost.com/my/controller

It is certainly not a terrible bug, but it is redundant.

**Comment by olivergierke** [comment]
Is this a duplicate of #301?

**Comment by dlvenable** [comment]
@olivergierke, from reading the description I believe it is.
