### ISSUE TITLE
Add SIREN support

### ISSUE THREAD

**Issue by lucaguada** [spring-projects/spring-hateoas#334]
Any plan to add support for Siren? or a fluent API in order to generate HATEOAS entities in such way?

it would be interesting to add an integration with siren4j - https://github.com/eserating/siren4j.

**Comment by nickgrealy** [comment]
+1

**Comment by ilyes** [comment]
That would be great

**Comment by groll75** [comment]
+1

**Comment by dschulten** [comment]
Just released [spring-hateoas-ext](https://github.com/dschulten/hydra-java#affordancebuilder-for-rich-hyperlinks) 0.2.0-beta5 to Maven central, it has a [SirenMessageConverter](https://github.com/dschulten/hydra-java#sirenmessageconverter-from-v-020-beta5).

Configuration sample: https://github.com/dschulten/hydra-java/blob/master/hydra-sample/service/src/main/java/de/escalon/hypermedia/sample/Config.java

It is based on AffordanceBuilder, which can also be found at the spring-hateoas [affordances feature branch](https://github.com/spring-projects/spring-hateoas/tree/feature/affordances). I will merge in the latest changes from spring-hateoas-ext into the feature branch during the next days.

**Comment by andifalk** [comment]
+1

**Comment by sintetico82** [comment]
+1

**Comment by mozinrat** [comment]
+1, I hope spring team really looks at this, its being overlooked for more than 2 years.

**Comment by gregturn** [comment]
With Affordances added via #612 (https://github.com/spring-projects/spring-hateoas/commit/70448a854098343897fd99e3227b4a61db54b921), we will be able to move forward with adding support for SIREN.

**Comment by gregturn** [comment]
You may wish to revisit this light of https://github.com/spring-projects/spring-hateoas/issues/833

**Comment by lazee** [comment]
What happened to the Siren support? Seems like all the other issues that blocked this are closed or fixed?

**Comment by gregturn** [comment]
As a project we slowed on implementing new media types and instead shifting to other aspects like affordances, renaming “resource” to “model” and WebFlux support. 

But by making it easy for others to [plug-in their own media type](https://docs.spring.io/spring-hateoas/docs/1.1.0.M3/reference/html/#mediatypes.custom), nothing is stopping someone else from coding and publishing a module that supports SIREN (or whatever).

**Comment by ingogriebsch** [comment]
The following is probably of interest to some of you: https://github.com/ingogriebsch/spring-hateoas-siren

**Comment by odrotbohm** [comment]
I think we should curate a list of well-known extensions on the project website and in the documentation to make sure users easily find those implementations.

**Comment by gregturn** [comment]
Superceded by #1337.
