### ISSUE TITLE
Returning hal+json response from the spring mvc interceptor

### ISSUE THREAD

**Issue by rajiv-shringi-A1** [spring-projects/spring-hateoas#338]
Our requirement is to return a JSON response by default, and return a HAL response if the client specifies the accepted content type as hal+json. 

We want to avoid writing two methods for each case (where one method produces json and another method produces hal+json), and instead have just one method returning json by default, and trigger the HAL processing in a Spring mvc interceptor if the content type specified is hal+json.

Is there any way to do this using the current spring mvc and spring hateoas framework? I am able to add links to the response, but the output is not HAL compatible

Snippet of my interceptor code:

    @Override
    public void postHandle(HttpServletRequest req, HttpServletResponse res, Object method, ModelAndView mv) throws Exception {
		if (mv != null) {
			Map<String, Object> modelMap = mv.getModel();
			if (modelMap != null) {
				Object response = modelMap.get("response");
				if (response instanceof Response) {
					modelMap.put("response", responseAssembler.toResource((Response) response));
				}
		}
	}

My response assembler looks like this:

    @Component
    @EnableHypermediaSupport(type = { HypermediaType.HAL }) 
    public class ResponseAssembler implements ResourceAssembler<Response, Resource<Response>> {

	    @Autowired
	    public ResponseAssembler() {
		    super();
	    }

	    @Override
	    public Resource<Response> toResource(Response response) {
		    Resource<Response> resource = new Resource<>(response);
		    resource.add(linkTo(Response.class).slash(response.getUri()).slash(response.getKey()).withSelfRel());
		    return resource;
	    }
    }

The output I see is 

    {
        "value": "this is a test value",
        "links":{
            "self":{
                "href": "http://localhost:8080/get/key1"
            }
        }
    }

What I want is the HAL compatible output i.e. _links instead of links

    {
        "value": "this is a test value",
        "_links":{
            "self":{
                "href": "http://localhost:8080/get/key1"
            }
        }
    }

Adding the @EnableHypermediaSupport(type = { HypermediaType.HAL })  to my resource assembler component does not work. The only way I can get this to work is to add @EnableHypermediaSupport(type = { HypermediaType.HAL }) to my controller and return a Resource<Response> from my controller method. But as I mentioned above this would mean adding two methods for each use case and we do not want that.

**Comment by rajiv-shringi-A1** [comment]
Figured out a way to do this using @ControllerAdvice

**Comment by nitinvarshney1983** [comment]
how did you do it. Can you please share any example?

**Comment by gregturn** [comment]
You want to avoid the enable annotation in general. It switches off Boot's auto configured HAL settings. From there you need your controller methods to return ResourceSupport-based objects. Anything else will not render proper HAL  

As for "JSON not HAL" I don't know what to tell you. When this project started HAL didn't exist. The format with "links" instead of "_links" doesn't follow any standard out there but is purely based on Jackson serialization. I wouldn't shoot for that but instead stick with pure HAL. This has the side effect of not needing to render two forms of JSON.
