### ISSUE TITLE
Vnd.error links key on json response

### ISSUE THREAD

**Issue by fjginermontagud** [spring-projects/spring-hateoas#345]
I noticed that "links" key don't has underscore at beginning (_links), and this not conform to the vnd.error specs.

For example:

``` json
[
    {
        "logref": "error",
        "message": "Could not find test",
        "links": [
            {
                "rel": "about",
                "href": "http://..."
            }
        ]
    }
]
```

This vnd.error is produced by this code:

``` java
@ControllerAdvice
class TestControllerAdvice {

    @ResponseBody
    @ExceptionHandler(TestNotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    VndErrors testNotFoundExceptionHandler(TestNotFoundException ex) {
        return new VndErrors(
                "error",
                ex.getMessage(),
                new Link("http://...", "about")
        );
    }
}
```

**Comment by gregturn** [comment]
VndErrors is incredibly HAL specific. It leans on having registered the Jackson2HalModule to properly render things.

We clean up the implementation to better match the spec via https://github.com/spring-projects/spring-hateoas/commit/4f3be119c08a0b5db690fe6727632705baae8e4e, but are planning to deprecate the whole things and embrace RFC-7807
