### ISSUE TITLE
Traverson: provide a flexible way to supply parameters, etc. at every hop

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#346]
Right now, only one set of parameters and headers can be supplied, and its on the last hop. Augment Traverson to allow overriding things at different hops as needed.

A proposal is to add another follow() method like this:

```java
traverson.follow("foo", "bar").
  follow("foobar", parameters).
  follow("asd", "fgh");
```
This provides the ability to chain multiple follows together, allowing hop-level overrides. I think the secondary parameter might should be a container that would support parameters, headers, or anything else needed in the future, without rewriting the core API again.

```java
traverson.follow("foo", "bar").
  follow("foobar", new Hop().parameters().headers())
  follow("asd", "fgh");
```
In addition, since debugging is hard when doing multiple hops, I would like something inspired by MockMvc's andDo(print()) operation as well.

```java
PrinterHandler printer = new PrinterHandler();
RecoderHandler recorder = new RecoderHandler();
HalVerifier verifier = new HalVerifier();
traverson.follow("foo", "bar").andDo(printer).andDo(recorder).andDo(verifier).toObject(new Resource<Actor>());
```
This allows plugging in multiple "handlers" that can each do something different. In this sample, one can be dedicated to printing results of each hop to the console, the second can record details of each hop for test verification, and the third can be involved in verifying that results are HAL documents. Also having the option to insert handlers on the Hop() class as well would be handy to strategically place them.

All of this should strive to NOT break backwards compatibility and allow existing code to work, but provide a smooth path to make the hops as sophisticated as desired by the consumer.

**Comment by gregturn** [comment]
In working on this, I now believe the API should look like this:

```java
ParameterizedTypeReference<Resource<Item>> typeReference = new
     ParameterizedTypeReference<Resource<Item>>() {};
Resource<Item> result = traverson.follow(new Hop("item").withParam("projection", "noImages"))
				.toObject(typeReference);
```
In this configuration, the rel is a constructor argument. Simply supplying a string to follow() results in the string being wrapped inside a Hop with no extra parameters, which in turn is the unit of work for traverson. A list of string-based rels is turned into a list of hops.

**Comment by olivergierke** [comment]
Welcome addition. Please make sure we start simple: adding overloads for `follow(…)` taking a `Map` of parameters for that single hop being a good candidate for a PR. I'd like to keep some focus here as every step more will make the PR hard to review and prolong the review process.
