### ISSUE TITLE
Add Support for Resolving Property Values in @RequestMapping(value)

### ISSUE THREAD

**Issue by kevinconaway** [spring-projects/spring-hateoas#361]
The `@RequestMapping(value)` annotation supports property values for dynamically specifying the endpoint value, like `@RequestMapping(value="${some.request.mapping})`

I am using the [Springfox](http://springfox.github.io/) project to document my API and I would like to be able to add a Link to the [Swagger2 documentation](https://github.com/springfox/springfox/blob/fd503636177b518c07b55f8d323630f2ec6c431f/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java) in my API:

I'm adding a link to a resource via:
 `resource.add(linkTo(methodOn(Swagger2Controller.class).getDocumentation(null)).withRel("swagger.json"));` 

and the resuling link looks like:

 `http://localhost:8080/api/${springfox.documentation.swagger.v2.path:/v2/api-docs}`

**Comment by jghiloni** [comment]
I'd like to throw my support behind this as well

**Comment by joeybic** [comment]
Is anybody still working on this? I know it's been more than a year, but it'd be super helpful if this worked...

**Comment by huehnerlady** [comment]
@gregturn Any update on this? It would be very important to us, will this be fixed soon? It is hanging for 3 years now 😞

**Comment by odrotbohm** [comment]
Resolved by #1328

**Comment by mirceade** [comment]
I don't get it, this doesn't really work in 1.4.0 with Kotlin.
