### ISSUE TITLE
Support for multiple Curie namespaces in the same application

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-hateoas#363]
Up to now `CurieProvider` is mainly an API for users to implement. There is a `DefaultCurieProvider` but it is very simple and only works by adding a fixed namespace to all unqualified links, without providing any mechanism to declare other namespaces. I expect some applications have multiple namespaces and the user who declares the rels knows what the prefixes are, and would like simply to map each one to a different `UriTemplate`.

**Comment by olivergierke** [comment]
That should be in place. There's now an additional constructor that takes a `Map` and allows to define the curie that shall be used for general link expansion.
