### ISSUE TITLE
The ControllerLinkBuilder does not strip the X-Forwarded-Prefix

### ISSUE THREAD

**Issue by jmnarloch** [spring-projects/spring-hateoas#367]
I had created issue in Data REST tracker: https://jira.spring.io/browse/DATAREST-620 intially, although all the link handling is done by spring-hateoas anyway.

So the problem is as fallows, I am doing a proxy forwading through Zuul enabled application and all links that orginally were configured at baseUri `/api` are being appended to the proxy path in generated HATEOAS links:

Original path:
`/api/loans/search/active`

Becomes after proxy forward (with configured path: /api/v1):
`/api/v1/api/loans/search/active`

Spring Zuul out of the box adds X-Forwarded-Prefix e.g.
`"x-forwarded-prefix":"/api"`

that should be used to strip the prefix path out of the generated uri.

**Comment by gregturn** [comment]
I used Zuul recently with a custom path, and it worked perfectly with the following Zuul config. 

https://github.com/gregturn/spring-a-gram/blob/master/spring-a-gram-frontend/src/main/resources/application.yml

**Comment by jmnarloch** [comment]
Well yes the proxy forwarding works fine, but the generated links are not correct.

**Comment by olivergierke** [comment]
I just verified in a unit test that the value of the `X-Forwarded-Prefix` header is appended to generated URIs correctly. You might wanna debug `ControllerLinkBuilder.getBuilder()` and `ServletUriComponentsBuilder.fromServletMapping(…)` explicitly to see it's added.

I am puzzled though, that you expect something stripped. As you can see in the [introducing commit](https://github.com/spring-projects/spring-framework/commit/d322bcfbf47cd865569e85932cefefbb6da1d5fd) in Spring Framework, the value of the header, gets *added* to URIs created. Can you maybe clarify your scenario, which URIs are requested, how you'd expect which headers to influence the URIs in which way?

**Comment by jmnarloch** [comment]
Got it. Thanks for finding this out, that was helpful. So now I understand *why* this works this way, although maybe not entirely *what for*. My original comment about stripping the prefix part of the url was based on falt assumption, that the whole part of url `/api/loans/search/active` is being appended to request context path, but clearly this not the case.

I'm affraid that at the moment I can not fallback to version prior to the Spring 4.1.3 version to see if this behaviour is different.

So as simple as I can explain my use case and the problem: 
This is the HAL response that I have from accessing the REST endpoint directly:

`http://localhost:8541/api`
```
{
  "_links" : {
    "applications" : {
      "href" : "http://localhost:8541/api/applications"
    },
    "loans" : {
      "href" : "http://localhost:8541/api/loans"
    },
    "customers" : {
      "href" : "http://localhost:8541/api/customers"
    },
   ...
  }
}
```

This what I have when I access the same endpoint through Zuul proxy:

`http://localhost:8080/api/v1/` - which add only simple version aware routing
```
{
  "_links" : {
    "applications" : {
      "href" : "http://localhost:8080/api/v1/api/applications"
    },
    "loans" : {
      "href" : "http://localhost:8080/api/v1/api/loans"
    },
    "customers" : {
      "href" : "http://localhost:8080/api/v1/api/customers"
    },
    ...
  }
}
```

With Zuul setup:
```
zuul:
  ignoredServices: '*'
  routes:
    api:
      path: /api/v1/**
      url: http://localhost:8541/api
 ...
```

In every of this case the links do not point to the correct service url and in this sense the `/api` part in  `v1/api/customers` would have to stripped to correct that.

Apart from REST extension or Spring Hateoas I wish that Zuul would have more fine grained control over which headers are being added and allow to skip X-Forwarded-Prefix header at the moment.

**Comment by olivergierke** [comment]
@dsyer, @spencergibb - Any comments?

**Comment by dsyer** [comment]
It looks like it's behaving as expected. If you don't want the `/api` prefix you have to remove it from the backend service (i.e. `http://localhost:8541/loans` would be the loans endpoint).

**Comment by olivergierke** [comment]
Aa far as I've understood, he'd like to insert the version prefix for the public URI. So essentially route the public URL `/api/v1/applications` to `http://localhost:8541/api/applications`. Shouldn't that be possible? It's weird that the front-end proxy imposes some resource naming constraints on the backend service.

**Comment by dsyer** [comment]
But the links are being created in the backend. There's no information there other than the `X-Forwarded-*` headers, so I don't see what else it can do. A user can change the `X-Forwarded-Prefix` if that would solve the "problem" by writing their own `ZuulFilter` (in this case).

**Comment by jmnarloch** [comment]
OK, Thanks for clearing this out. I appreciate your help.

@dsyer You are completely right about removing the context `/api` path. It does not get propagated afterwards and this will work.

Since I have full control over the backend path mappings  I can map the endpoints directly to root at the moment, although I would probably end up with custom `ZuulFilter` in the end.

Although my personal opinion is that this might be a quite common use case and sooner or later this issue might get back.

**Comment by dsyer** [comment]
OK. It's probably next to open an issue an spring-cloud-netflix and specifically mention the feature of being able to specify the `X-Forwarded-Prefix` separately from the route prefix (I believe that's what you need).

**Comment by gregturn** [comment]
So in my linked configuration up above. It was a fluke that it worked because I was mapping /api to /api, being the same?

**Comment by dsyer** [comment]
If you like. I would say you made a sensible choice of path prefix.
