### ISSUE TITLE
Spring Hateos for Android

### ISSUE THREAD

**Issue by jaredsburrows** [spring-projects/spring-hateoas#371]
Could we create a specific module for Android? Something slim like the Android REST template.

```
compile 'org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE'
compile 'org.springframework.android:spring-android-rest-template:2.0.0.M3'
compile 'com.fasterxml.jackson.core:jackson-databind:2.6.0' // needed by rest-template
compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'
compile 'org.slf4j:slf4j-android:1.7.12'
compile('org.springframework.hateoas:spring-hateoas:0.17.0.RELEASE') {
    exclude module: 'commons-logging'
    exclude module: 'spring-beans'
    exclude module: 'spring-context'
    exclude module: 'spring-core'
    exclude module: 'spring-web'
}
compile('org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE') { // needed by "spring-hateoas"
    exclude module: 'commons-logging'
    exclude module: 'spring-beans'
    exclude module: 'spring-context'
    exclude module: 'spring-web'
}
compile ('com.jayway.jsonpath:json-path:2.0.0') { // needed by "spring-hateoas"
    exclude module: 'asm'
}
```

**Error:**

`gradle assembleFreeDebug`

<pre>
:app:course-notes:dexFreeDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lorg/objectweb/asm/AnnotationVisitor;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)

:app:course-notes:dexFreeDebug FAILED
</pre>

**Comment by fritzZz** [comment]
I've the same error. Anyone has solved?

**Comment by mustafaguc** [comment]
i've created a [repository] (https://github.com/mustafaguc/spring-data-rest-android) and upload artifacts to bintray. Include bintray repository in your build.gradle and add dependency : 

```
repositories {
    maven {
            url  "http://dl.bintray.com/power/maven"
        }
}

compile 'spring-contrib:spring-data-rest-android:1.1'

**Comment by mockitoo** [comment]
i've created a [repository](https://github.com/mockitoo/spring-data-rest-android) and uploaded artifacts to bintray. Add bintray repository and dependency to  build.gradle file : 

```
repositories {
   maven {
            url  "http://dl.bintray.com/power/maven"
        }
}  

compile 'spring-contrib:spring-data-rest-android:1.1'

**Comment by gregturn** [comment]
By all means, create your own Spring HATEOAS spin off module that focuses on Android. However, in general, we can't commit resources to such a platform specific feature at this time.
