### ISSUE TITLE
Support for java 8 optional method parameters

### ISSUE THREAD

**Issue by mogronalol** [spring-projects/spring-hateoas#373]
Something like:

```
@RequestMapping("/someurl")
public Object foo(@RequestParam final Optional<String> optionalParameter)
```

I 'd expect this to produce `/someurl`

```
linkTo(methodOn(Controller.class).foo(Optional.empty())).withSelfRel()
```

And for this to produce `/someurl?optionalParameter=bar`

```
linkTo(methodOn(Controller.class).foo(Optional.of("bar"))).withSelfRel()
```

Currently you get an exception, because it looks like there is no `Converter` implementation that supports Optionals.

**Comment by vlfors** [comment]
I think that problem not in "spring-hateoas". I'm have used "Optional" and in result got error. 
```java
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type @org.springframework.web.bind.annotation.RequestParam java.util.Optional<java.lang.String> to type java.lang.String
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:313)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
	at org.springframework.hateoas.mvc.AnnotatedParametersParameterAccessor$BoundMethodParameter.asString(AnnotatedParametersParameterAccessor.java:172)
	at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:141)
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:135)
	at hello.GreetingController.foo(GreetingController.java:33)
```
Function 
```java
public String asString() {
			if (value == null) {
				return null;
			}
			return (String) CONVERSION_SERVICE.convert(value, parameterTypeDecsriptor, STRING_DESCRIPTOR);
		}
```
Error in metod CONVERSIONSERVICE.convert(value, parameterTypeDecsriptor, STRING DESCRIPTOR) of package org.springframework.core.convert.support;

Errors shown while in debug mode 
```java
protected GenericConverter getConverter (TypeDescriptor sourceType, TypeDescriptor targetType) 
converter = this.converters.find(sourceType, targetType); //ln. 257 
  
```
package org.springframework.core.convert.support;
not found converter

**Comment by mogronalol** [comment]
I think the converters are registered in a static class somewhere in spring hateoas.  Ideally converters in the conversion service should be configurable but they are not.  If they aren't I think OptionalConverter should be there as part of the static collection.

**Comment by markphelps** [comment]
As @mogronalol mentioned, It looks like [AnnotatedParametersParameterAccessor. BoundMethodParameter](https://github.com/spring-projects/spring-hateoas/blob/666a16cc3a89bb1d4d3e1af64bbeb7f53da2dceb/src/main/java/org/springframework/hateoas/mvc/AnnotatedParametersParameterAccessor.java#L110) instantiates a new [DefaultFormattingConversionService](https://github.com/spring-projects/spring-framework/blob/c622f4c487b0a42db8e04d1ec905ea7942885462/spring-context/src/main/java/org/springframework/format/support/DefaultFormattingConversionService.java) which does not have support for Optional.

Perhaps a solution would be creating an OptionalConverter and adding it to the DefaultFormattingConversionService if java.util.Optional is on the class path? I'm not sure what ramifications this could have, however it seems do-able since the same is done for JodaTime and others in the DefaultFormattingConversionService.

**Comment by ashut0shpandey** [comment]
Do we know if this issue is being worked on  or we already have a solution for it?

**Comment by CanD42** [comment]
I'm running into the same right now. Isn't there a solution yet? Thanks

**Comment by gregturn** [comment]
#618 introduces mechanism to inject a custom ConversionService. 

The other wrinkle is the fact that Spring HATEOAS is presently based on Java 6. There are plans to pull things up to Java 8 in the near future but we have to complete some other tasks first.

**Comment by matthieu-vergne** [comment]
Looking at your link and digging in the discussions, it seems something is available since recently, but I fail to understand how to use it. Could someone explain whether there is now a workaround for this issue?

**Comment by gregturn** [comment]
This feature now works. I created:

```java
@GetMapping("/optional")
public ResponseEntity<?> optionalGetter(@RequestParam Optional<String> optionalParameter) {
	return ResponseEntity.noContent().build();
}
```
Then, I wrote a couple tests, and verified that `Optional` is now fully supported by the default converter service used by Spring HATEOAS.
```java
@Test
void optionalWebMethodsShouldWork() {

	assertThat(linkTo(methodOn(WebMvcEmployeeController.class).optionalGetter(Optional.empty())).withSelfRel().toString())
			.isEqualTo(Link.of("http://localhost/optional{?optionalParameter}").toString());

	assertThat(linkTo(methodOn(WebMvcEmployeeController.class).optionalGetter(Optional.of("bar"))).withSelfRel().toString())
			.isEqualTo(Link.of("http://localhost/optional?optionalParameter=bar").toString());
}
```
With this passing green, it should illustrate you have full support for Java 8 Optional.
