### ISSUE TITLE
A few problems - test cases included!

### ISSUE THREAD

**Issue by claym** [spring-projects/spring-hateoas#384]
It's entirely possible I'm doing something wrong, and it's possible I'm submitting this to the wrong place (spring-data-rest doesn't have github issues), but I've had some issues with things like

returnBodyOnCreate
returnBodyOnUpdate
exposeIds

The test cases can be found in this project:

https://github.com/claym/hateoas/tree/spring-hateoas-test-cases

Notes on each test case in HateoasApplicationTests.java

exposedIds(): works, as specified in hateoas.RestRepoConfig.java

exposedIdsInResponseEntity(): Traverson look up of a collection - the `Resource<Widget>` don't have ids. The other body values are there.

returnBodyOnCreate(): Should return body on create, does not, just an empty, newly instantiated object. Pretty straight forward.

returnBodyOnUpdate(): A little contrived, doing the PUT through exchange(), but I would think this would return an object on update.

It is *entirely* possible I am doing things wrong, so if I am, please let me know. 

I've done what I can to verify creates/updates are happening appropriately on the server, but the responses are just a little odd.

I'm using: 

Spring Boot 1.3.0M4, as 1.2.5 has issues with the RestRespositoryConfiguration

this uses spring-data-rest 2.4.0RC1 - oddly enough if you use 2.4.0-RELEASE, you get this error:

`java.lang.ClassNotFoundException: org.springframework.data.rest.core.config.EnumTranslationConfiguration`

Spring hateoas 0.18.0-RELEASE - 0.17-RELEASE has some issues with Traverson

There's a gradle build file included, and it does everything in memory, so hopefully you should just be able to pull and run `gradle test`.

Let me know what I'm doing wrong or if you have any questions.

**Comment by gregturn** [comment]
For Spring Data REST, you can open issues here => https://jira.spring.io/browse/DATAREST

I would suggest testing against Spring HATEOAS 0.19.0, using Boot 1.3.0.M4 (which you are), and setting <spring-data-release.train> to Gosling-RELEASE.

This way, you will be using the latest release of things.

**Comment by claym** [comment]
Well, that fixed most of it :)

Still have the issue in 

exposedIdsInResponseEntity(): Traverson look up of a collection - the Resource<Widget> don't have ids. The other body values are there.

I'll log that over with the DATAREST project. Thanks!
