### ISSUE TITLE
Add Support to ControllerLinkBuilder for Composed Annotations

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-hateoas#392]
Spring 4.2 supports creating composed MVC annotations like `@Get` and `@Post`, for example as provided by [Spring Composed](https://github.com/sbrannen/spring-composed).  `ControllerLinkBuilder` ignores these annotations and generates incorrect hrefs. Support for this would be great.

**Comment by bbilger** [comment]
:+1:

**Comment by dwdking** [comment]
@Singleshot, I have annotations working with GetMapper, PostMapper, etc on controller methods but haven't been able to use a composed annotation of RequestMapper as shown here https://github.com/dwdking/example-hateoas. Where were you using the annotation, on the type or method?

**Comment by gregturn** [comment]
Superceded by #471 and #497.
