### ISSUE TITLE
Add feature to create child via POST parent/parendId/children url

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [spring-projects/spring-hateoas#394]
[This stackoverflow question](http://stackoverflow.com/questions/25311978/posting-a-onetomany-sub-resource-association-in-spring-data-rest) is no mine, but none the less could you please add support for creating child entities via parent url?

**Comment by gregturn** [comment]
Considering the SO has been answered by @olivergierke, im closing this issue.

**Comment by gregturn** [comment]
Considering the SO has been answered by @olivergierke, im closing this issue.
