### ISSUE TITLE
Support for UriTemplate's with composite values

### ISSUE THREAD

**Issue by janbols** [spring-projects/spring-hateoas#396]
Currently UriTemplate does not have support for composite values (see http://tools.ietf.org/html/rfc6570#section-2.4.2). 

This means we cannot create a template for a URL like the following:

```
http://localhost/resource{?address*}
```

Expanding it with [firstAddress, secondAddress, thirdAddress] would result in the following URI:

```
http://localhost/resource?address=firstAddress&address=secondAddress&address=thirdAddress
```

A possible solution might be to add an extra field on TemplateVariable to indicate if it's composite and allow to call UriTemplate#expand() using a MultiValueMap.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/pull/484
