### ISSUE TITLE
Resource<T> in RestTemplate's getForObject

### ISSUE THREAD

**Issue by bep** [spring-projects/spring-hateoas#4]
I have a hard time figuring out how to use the `Resource` wrapper in Spring's `RestTemplate`'s `get`/`put`/`postForObject` methods, where the second param is `Class<T> responseType`.

Of course this may be a missing feature in `RestTemplate`, but I just wonder if you have any workarounds.

**Comment by gregturn** [comment]
Seeing the question has been answered, I'm closing this issue.
