### ISSUE TITLE
Special characters in path variables are escaped multiple times when added with slash()

### ISSUE THREAD

**Issue by pgpx** [spring-projects/spring-hateoas#40]
I'm trying to use a URI-encoded value as a path segment value when constructing a link with LinkBuilder's slash() method, but I find that any 'special' characters (such as %) will be repeatedly double-encoded by each subsequent slash() call.

For example:

``` java
linkToCurrentMapping().slash("first")
    .slash("sec%ond").slash("thi%rd")
    .slash("fourth").withSelfRel();
```

Should return `http://localhost/first/sec%25ond/thi%25rd/fourth` but gets `http://localhost/first/sec%252525ond/thi%2525rd/fourth`

I think that this is being caused by LinkBuilderSupport's interaction with HierarchicalUriComponentBuilder.toUri and URI (which always encodes the path).

Note that I'm actually trying to percent-encode a path as a path segment value, but if I don't explicitly percent-encode slashes in the path, then they are not encoded at all:

``` java
linkToCurrentMapping().slash("first")
    .slash("sec/ond").slash("third").withSelfRel();
```

I would like `http://localhost/first/sec%2Fond/third/fourth` but get `http://localhost/first/sec/ond/third` (due to the `StringUtils.tokenizeToStringArray(object.toString(), "/")` call in LinkBuilderSupport.slash).

Here's the full unit test: https://gist.github.com/4436408

**Comment by some-ejit** [comment]
It appears that the problem is in UriTemplate:

    public URI expand(Object... uriVariableValues) {
        UriComponents expandedComponents = this.uriComponents.expand(uriVariableValues);
        UriComponents encodedComponents = expandedComponents.encode();
        return encodedComponents.toUri();
    }

This expandedComponents.encode() is causing any arguments for the URI template to be encoded. When the URI is encoded once again later ....

**Comment by olivergierke** [comment]
We've just pushed a removals for an unnecessary back-and-forth conversion in the course of the fix for #398. Does that maybe even fix that issue here?

**Comment by pgpx** [comment]
This fixes my first test (thanks!), so the following passes:
```java
Link l = linkToCurrentMapping().slash("first")
   .slash("sec%ond").slash("thi%rd").slash("fourth").withSelfRel();
assertEquals("http://localhost/first/sec%25ond/thi%25rd/fourth", l.getHref());
```

However, it doesn't encode any `/` characters at all - though maybe that is by design?

```java
linkToCurrentMapping().slash("first")
    .slash("sec/ond").slash("third").withSelfRel();
```
I would like `http://localhost/first/sec%2Fond/third` but get `http://localhost/first/sec/ond/third`

**Comment by gregturn** [comment]
`.slash()` basically appends "/" with the contents. However, "/" is still the token splitting thing, so `.slash("sec/ond")` is just like typing `slash("sec").slash("ond")`.

To support this, we'd need to pre-encode the `slash()` command, which I'm not convinced on.

**Comment by gregturn** [comment]
I think it's safe to say that if you NEED to encode a "/" and NOT have it split into two paths, you are responsible for that. 

There is little way in framework code to detect this rare corner case.
