### ISSUE TITLE
JSON unwrapped for Resource class doesn't work for mapper with FIELD property accessor

### ISSUE THREAD

**Issue by pnowy** [spring-projects/spring-hateoas#414]
On our project we are using the following configuration for ObjectMapper:

``` java
ObjectMapper mapper = new ObjectMapper();
mapper.setVisibility(mapper.getSerializationConfig().getDefaultVisibilityChecker()
            .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
            .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
            .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
            .withIsGetterVisibility(JsonAutoDetect.Visibility.NONE)
            .withCreatorVisibility(JsonAutoDetect.Visibility.NONE));
```

With above configuration the @JsonUnwrapped annotation doesn't work. For example class:

``` java
    private static class Person {
        private String firstname;

        public Person() {
        }

        private Person(String firstname) {
            this.firstname = firstname;
        }
    }
```

We get the json:

``` json
{
    "content": {
        "firstname": "Harry"
    },
    "links": []
}
```

The "content" tag shouldn't be here. I suggest add annotation @JsonUnwrapped to the Rosource class for the content property too (not only for getter).

**Comment by olivergierke** [comment]
The reason we only keep the annotations on the accessors is that they can't be reconfigured using mixins or for subtypes in case they're applied to the fields. So I am afraid we'd break some client setups if we add that annotation.

**Comment by pnowy** [comment]
Your argument sounds reasonable and I agree that it is a useful feature. I myself was using it in order to avoid the problems with the content unwrapping when the content is a map. Example:

```java
public class MapUnwrappedResource<T extends Map> extends Resource<T> {

	public MapUnwrappedResource(T content, Link... links) {
		super(content, links);
	}

	public MapUnwrappedResource(T content, Iterable<Link> links) {
		super(content, links);
	}

	@XmlAnyElement
	@JsonIgnore
	public T getContent() {
		return super.getContent();
	}

	@JsonAnyGetter
	@XmlAnyElement
	public T getUnwrappedContent() {
		return super.getContent();
	}

}
```

I just only wondering if we add the annotation to the field it should have impact only to the clients who are using the configuration with the field visibility (if someone uses the serialization based on getters and setter shouldn't feel the change because still could override the behavior by the setters/getters).

I assume if someone is using ```ObjectMapper``` configuration mentioned on the first comment should have had the problem a long time ago. Do you remember someone on the past reported that kind of problems?

**Comment by pnowy** [comment]
Closing the ticket. Lack of response.
