### ISSUE TITLE
Support optional Link properties of HAL Spec like "deprecation"

### ISSUE THREAD

**Issue by fabianbuch** [spring-projects/spring-hateoas#417]
HAL specifies additional properties to rel, href and templated in Section 5:

https://tools.ietf.org/html/draft-kelly-json-hal-07#section-5

Is it possible to support these by extending the LinkMixin with "type", "deprecation" and "name"? This would allow deprecating links to deprecated APIs and clients to e. g. automatically log a warning when using deprecated APIs.

**Comment by wallner** [comment]
This is something we would also be very interested in, especially in the optional 'title' attribute. Would you consider a patch, if we came up with one?

**Comment by tkrille** [comment]
+1, we need the `title` attribute too.

**Comment by olivergierke** [comment]
Fixed with #567.
