### ISSUE TITLE
ResourceSupport dosen't implement Serializable

### ISSUE THREAD

**Issue by famaridon** [spring-projects/spring-hateoas#424]
Hi,

I'm trying to use @Cachable with Redis and spring-hateoas and I have one problem.

First RestController call is ok (create cache) the second is ko because _links is missing.

I fork project to add implements Serializable on ResourceSupport and it work fine.

Can you add Serializable to ResourceSupport or give me other solution?

Kind regards

**Comment by olivergierke** [comment]
Not sure what to make of this. `ResourceSupport` instances are not mean to be (Java-)serialized as their only reason of existence is to make sure JSON serializers render hypermedia elements.

**Comment by famaridon** [comment]
Ok but Redis Cache default use JdkSerializationRedisSerializer to serialize/deserialize object to/from Redis. 

I will try to write my RedisSerializer to  serialize/deserialize inJSon but deserialize method doesn't have that wanted type.

It will be risky to add Serializable to ResourceSupport?

**Comment by TYsewyn** [comment]
@famaridon You shouldn't put the `@Cacheable` annotation on your REST controller. Instead you need to create an abstraction layer with a method which will fetch your objects from your DB and annotate that with `@Cacheable`. The second time your REST controller will try to call the abstraction layer it will get the results from your cache. The sole purpose of `Resource` and `Resources` is to convert your data into DTO objects so json serializers know how to render hypermedia elements, as said by @olivergierke

**Comment by gregturn** [comment]
Based on lack of activity, I'm closing this issue.
