### ISSUE TITLE
Backlog of Open Pull Requests

### ISSUE THREAD

**Issue by nickgrealy** [spring-projects/spring-hateoas#425]
Hi,

I just wanted to draw attention to the backlog of [36 Open Pull Requests](https://github.com/spring-projects/spring-hateoas/pulls), and inquire as to whether there is a plan to action them?

Specifically, I created some Pull Requests 3 months ago, which hasn't been triaged or commented on. There's other Open Pull Requests from as far back as Jun 2013 which don't have a comment or label.

- Is there a plan for actioning them?
- Are the Open Pull Requests not conforming to the project standards?
- Who is coordinating the Pull Requests / strategic direction? (Is @olivergierke back from holidays?)
- Have they already been triaged through some other process?
- Are you under-resourced - would you like assistance in reviewing the backlog (more than happy to help out)?

I raised this issue, only because I noticed Issues were being responded to, and Pull Requests were not. It'd be a shame for people to contribute work, and have it overlooked.

Yours sincerely,
Nick Grealy

**Comment by olivergierke** [comment]
What is holidays? :)

<img width="224" alt="bildschirmfoto 2016-01-13 um 17 03 21" src="https://cloud.githubusercontent.com/assets/128577/12299833/ff675660-ba18-11e5-9d96-856469ae1636.PNG">

Generally speaking, issues are often easier to deal with as they usually raise question and can be answered with further questions. Pull requests are usually merged more easily in case they don't require any (big) additional polishing effort. Most of them are unfortunately lacking tests, context etc. Beyond that, most development and releases are driven by needs in downstream projects (e.g. Spring Data REST).

It's not that work is overlooked but Spring HATEOAS is by far not the only project we are (I am) busy with and thus the time available to spend on it is rather limited, unfortunately.

I'll close this one as it's not something we can fix within the codebase or with a release but happy to go on discussing.

**Comment by nickgrealy** [comment]
Sure no problem. I understand you're busy with other projects, let me know if I can help out in any way.

I'll make sure I use Issues to provide context for the existing pull requests (and give them a spotlight), and will update them with any missing test cases.

Thanks for the response, mostly I just wanted to get some feedback (discussion is good).

**Comment by olivergierke** [comment]
Thanks for understanding! Looking forward to more exchange :).
