### ISSUE TITLE
JAXB vs Jackson annotations in ResourcesMixin, ResourcesSupportMixin

### ISSUE THREAD

**Issue by reva** [spring-projects/spring-hateoas#427]
I am probably missing something, but shouldn't the `@XmlElement` annotations on 'ResourceSupportMixin' and 'ResourcesMixIn' match the respective `@JsonProperty` annotation? Why are the property names different?

**Comment by gregturn** [comment]
Superseded by https://github.com/spring-projects/spring-hateoas/pull/695
