### ISSUE TITLE
RestTemplate configuration to deserialize HAL and also POST/PATCH back to server

### ISSUE THREAD

**Issue by lnhrdt** [spring-projects/spring-hateoas#430]
We're having an issue with RestTemplate and HATEOAS on a project. We have a Spring REST client application that communicates with a SDR app. We can't get a RestTemplate configuration that can both serialize and deserialize our entities in the client.

Our entities look like this (excerpt):

``` java
@JsonIgnoreProperties(ignoreUnknown = true)
public class User extends ResourceSupport {
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @JsonSerialize(using = SelfLinkSerializer.class)
    public Organization getOrganization() {
        if (hasLink("organization")) {
            URI organization = UriComponentsBuilder.fromUriString(getLink("organization").getHref()).build().toUri();
            Traverson traverson = new Traverson(organization, MediaTypes.HAL_JSON);
            return traverson.follow("self").toObject(Organization.class);
        }
        return null;
    }

    public void setOrganization(Organization organization) {
        if (hasLink("organization")) {
            getLinks().remove(getLink("organization"));
        }
        Link organizationLink = new Link(organization.getLink("self").getHref(), "organization");
        add(organizationLink);
    }
}
```

Our RestTemplate that can deserialize responses from the server has Jackson2HalModule in the ObjectMapper:

``` java
...
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
objectMapper.registerModule(new Jackson2HalModule());
...
```

But that RestTemplate can't serialize entities for PUT, PATCH etc. We have to take the Jackson2HalModule line out of the configuration. Then it can serialize the request but fails on deserializing the response. So we don't have a working solution using RestTemplate.

We've put together a sample application that demonstrates our problem:
https://github.com/lennyk/resttemplate-spike-server (run the spring app)
https://github.com/lennyk/resttemplate-spike (run the test with the server running)

Any ideas?

**Comment by gregturn** [comment]
See my feedback at https://github.com/lennyk/resttemplate-spike/pull/1

**Comment by gregturn** [comment]
With no followup to my test example, I'm closing this issue.

**Comment by lnhrdt** [comment]
Thanks Greg! It was very helpful on the relevant project last year!
