### ISSUE TITLE
EmbeddedMapper private but used in public constructor

### ISSUE THREAD

**Issue by drdamour** [spring-projects/spring-hateoas#433]
https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/hal/Jackson2HalModule.java#L121

having a tough time working with this new serializer, this one in particular is difficult...how can i create my own embedded mapper?

**Comment by gregturn** [comment]
Existing media types aren't really designed for external usage. It's primarily to support HAL-FORMS (and other tentative HAL extensions), which is in another package as well as the other modules of Spring HATEOAS that need to instantiate things.

That being said, we have designed an SPI to register your own media types. See #833.

**Comment by drdamour** [comment]
that's too bad because the existing one has no way to force a single link to be represented as a link array with a single entry in the output json..so if you add a second link later clients that are tightly coupled to the json contract complain that an object became an array.

**Comment by odrotbohm** [comment]
@drdamour – Would you mind checking the options available on `HalConfiguration`? There are plenty of ways to define whether links shall be rendered as arrays. As of 1.0 M1 even on a per link relation basis.

**Comment by drdamour** [comment]
hey look at https://github.com/spring-projects/spring-hateoas/blob/a89e57eed7e12819b87be7f1b977dddfd432541d/src/main/java/org/springframework/hateoas/mediatype/hal/HalConfiguration.java#L99 that's very handy! guess i need to RTFM (again).

thanks

**Comment by odrotbohm** [comment]
It's pretty new,  so don't be too harsh on yourself :). Happy coding!

**Comment by drdamour** [comment]
yeah if you added support for #175 i could use the OOTB one
