### ISSUE TITLE
Given link header is not RFC5988 compliant

### ISSUE THREAD

**Issue by khong07** [spring-projects/spring-hateoas#440]
Hello,

By using `Links.valueOf` in Spring Hateoas, I'm facing an `IllegalArgumentException`

My url contains a comma `,` in the query params
http://localhost:8080/test?page=0&filter=foo,bar

The parsing using `source.split(",");` failed because it splits at `filter=foo` but not `filter=foo,bar`

Proposition: you could use a regex pattern to split the link header url
```java
Pattern LINK_HEADER_PATTERN = Pattern.compile("(<[^>]*>;rel=\"[^\"]*\")");
Matcher matcher = LINK_HEADER_PATTERN.matcher(link);
while (matcher.find()) {
      links.add(matcher.group());
}
```

**Comment by olivergierke** [comment]
That's in place now.
