### ISSUE TITLE
Support Slice in the PagedResourcesAssembler

### ISSUE THREAD

**Issue by anthofo** [spring-projects/spring-hateoas#443]
Hi,

Sometimes we cannot have informations such as the total elements and total pages of a request, that's where we're using a Slice instead of a Page.
But the PagedResourcesAssembler does not allows to convert a Slice to a Resource, it would be great to add a `toResource(Slice<T> entity)` method, or even add SlicedResourcesAssembler class.

**Comment by olivergierke** [comment]
That needs to go into Spring Data Commons actually as this is where `PagedResourcesAssembler` lives. I've created [DATACMNS-845](https://jira.spring.io/browse/DATACMNS-845) for that.
