### ISSUE TITLE
RepresentationModelAssemblerSupport does not expose controllerClass/resourceType to subclasses

### ISSUE THREAD

**Issue by sebster** [spring-projects/spring-hateoas#445]
I would like to add additional links in my toResource method of a subclass of ResourceAssemblerSupport, but the controllerClass needed to construct the link is not visible. It's easy to workaround by adding a controllerClass field in the subclass as well, but it I think it would be nicer if there were protected getControllerClass()/getResourceType() methods for subclasses to use.

**Comment by marceloverdijk** [comment]
+1 Although I can workaround this quite easily it feels that we are early adopters using Spring HATEOAS.
@olivergierke I see many open issues and PR's and 0.19 release is of last September. Is this project moving forward? I can create a PR is you like?

**Comment by gregturn** [comment]
Would support #572.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/a0469e0371bbff3950d708d9ab0bbed16aa8e855.
