### ISSUE TITLE
Support for vendor specific media types

### ISSUE THREAD

**Issue by zersaegen** [spring-projects/spring-hateoas#454]
This issue has already been reported [here](https://github.com/spring-projects/spring-hateoas/issues/263) and several times on [stackoverflow](http://stackoverflow.com/questions/27494779/cannot-do-haljson-level-3-restful-api-with-spring-hateoas-due-to-lack-of-clarit) but still there is no answer on how to add vendor specific media types like `application/vnd.com.company.entity+json` so they get rendered as HAL.

After looking into the project I would have expected two ways to add custom media types:
1. Override the media types in `Jackson2ModuleRegisteringBeanPostProcessor` where the message converter and the object mapper are set up. I don't know if this is even possible but I did not find an obvious way to do so, so I assume and hope this is not the way one should go.
2. Extend `HypermediaType` but as this is a enum, I don't see a way to do this either.

Both ways really seem to make it hard to add custom media types, and I can't imagine/I don't hope the supposed ways in the mentioned issue or on stackoverflow are the way to go.

Funny enough, I even gave an answer to the stackoverflow question I mentioned above myself ([here](http://stackoverflow.com/a/29676436/1089459)) but still one year later there is no way to support this absolutey basic Hateoas feature. How is a media type driven library supposed to work if it does not support media types? I don't want to be harsh and I really appreciate all the effort put in this project, but I just don't get it. Currently it feels more like a `spring-hal` project.

Stackoverflow:
[1](http://stackoverflow.com/q/26761845/1089459)
[2](http://stackoverflow.com/q/27494779/1089459)

Other related issues:
#333
#263
#262
#134
#87
#37

**Comment by gregturn** [comment]
Related to #518

**Comment by gregturn** [comment]
Resolved via #833.
