### ISSUE TITLE
Support for Google App Engine

### ISSUE THREAD

**Issue by TiGz** [spring-projects/spring-hateoas#456]
Currently when running on Google flexible app engine links that should be https are being generated as http because Google doesn't set either the X-Forwarded-Proto or X-Forwarded-Ssl header when terminating SSL in their load balancer.

I have a fix for this in PR https://github.com/spring-projects/spring-hateoas/pull/453

**Comment by gregturn** [comment]
Based on https://cloud.google.com/appengine/docs/flexible/java/upgrading and the retirement of this header, I'm closing this issue.
