### ISSUE TITLE
Is there a way to force spring-hateoas to generate https links instead of http?

### ISSUE THREAD

**Issue by Aracki** [spring-projects/spring-hateoas#461]
I asked question on stackoverflow:
http://stackoverflow.com/questions/37855319/forcing-spring-hateoas-to-generate-https-links-instead-of-http

I'm using _spring-boot:1.3.3, spring-hateoas:0.19.0 and spring-data-rest-core:2.4.4_

Regards!

**Comment by olivergierke** [comment]
Spring HATEOAS uses the underlying Spring Framework infrastructure to use the protocol information of the incoming request. That in turn considers well known HTTP headers like `X-Forwarded-Proto` which means that if you set those in a proxy, Spring HATEOAS will do what you expect it to. Alternatively you could put infrastructure in front of your application to redirect HTTP requests to HTTPS.

Going forward please use StackOverflow for general purpose questions.

**Comment by aboger** [comment]
It seems that as of Spring-Boot 2.1 / Spring 5.1, it needs a bit of addional configuration:

    @Bean
    FilterRegistrationBean<ForwardedHeaderFilter> forwardedHeaderFilter() {
        FilterRegistrationBean<ForwardedHeaderFilter> bean = new FilterRegistrationBean<>();
        bean.setFilter(new ForwardedHeaderFilter());
        return bean;
    }

See https://stackoverflow.com/questions/30020188/how-to-configure-spring-hateoas-behind-proxy
