### ISSUE TITLE
AnnotationMappingDiscoverer should read @RequestMapping#params()

### ISSUE THREAD

**Issue by sp00m** [spring-projects/spring-hateoas#467]
`@RequestMapping` allows to use requests' GET parameters to map incoming requests without having to inject parameters into a `@RequestParam` annotated method parameter:

```
@RequestMapping(method = GET, value = "/foobar", params = { "!one", "two", "three!=3", "four=4" })
public ResponseEntity<?> get() {
  return foobar();
}
```

This is pretty useful when you want clean API endpoints as well as clean code (e.g. no need of single method delegating to other methods thanks to a switch/case on the parameter's value).

It could be great if `linkTo(methodOn(FooBarApi.class).get())` took these `params` into account as well, by generating for the above example at least:

```
http://example.com/foobar?four=4
```

And why not:

```
http://example.com/foobar?four=4&two=true
```

But iff no `@RequestParam` matched this `two` parameter (otherwise, the actual value would have been given when calling `linkTo(methodOn(FooBarApi.class).get(twoParamValue))`).

What do you think about it?

Technically, when dealing with the `@RequestMapping` annotation, the `AnnotationMappingDiscoverer` instance used in `ControllerLinkBuilderFactory` could instantiate an new `org.springframework.web.servlet.mvc.condition.ParamsRequestCondition` to parse thoses `params`.

**Comment by odrotbohm** [comment]
This should be in place thanks to @reda-alaoui's contribution. Minor comment on the original description: we do not add `two=true` as suggested as there's no value given in the `params` definition.
