### ISSUE TITLE
Is there a way to return _links in array

### ISSUE THREAD

**Issue by jiangchuan1220** [spring-projects/spring-hateoas#476]
I use Spring hateoas in my Spring boot project, it add _embedded and _links into response body. I expect the _links to be a array as follows:
"_links": [
    "self": {
      "href": "http://localhost:8080/lists"
    }
  ]
However, the response turns out the _links is an Object as follows:
"_links": {
    "self": {
      "href": "http://localhost:8080/lists"
    }
  }
Is there any way to change the _links from object to array (from "{}" to "[]") ?
This problem comes out when I use swagger to generate api description. Swagger expects the _links to be array, as follows:
 "_links": [
    {
      "href": "string",
      "rel": "string",
      "templated": true
    }
  ]
Looking forward to your reply! Thanks.

**Comment by gregturn** [comment]
What you're asking for is invalid JSON. Each of the "_links" entries is a key-value pair. The only way to return an array would be to return a different structure like an array of keys, an array of URIs, or an array of some other subtype. None of those match the HAL spec's format[1].

If the issue you are running into is some JavaScript code where you wish to iterate over _links and perhaps present them on the page would be to use code like this...

```
Objects.keys(myObj._links).map(key => {
    // do something with myObj._links[key] URI....
})
```

If you are using Java code to consume the _links entry, then either **Map.keySet()** or **Map.entrySet()** gives you an API to iterate over and consume the rel/URI entries in the hypermedia.

As to Swagger, then it appears they are asking for an invalid HAL format. And regarding Swagger, not quite sure what the use case is for wrapping a Spring HATEOAS powered service that comes with fully loaded hypermedia, and wrapping it with a format that totally eschews hypermedia in favor of hard coded links.

[1] - http://stateless.co/hal_specification.html
