### ISSUE TITLE
VndErrors.VndError#logRef is not optional

### ISSUE THREAD

**Issue by matlach** [spring-projects/spring-hateoas#478]
According to the specification https://github.com/blongden/vnd.error

> logref
> 
> OPTIONAL
> 
> For expressing a (numeric/alpha/alphanumeric) identifier to refer to the specific error on the server side for logging purposes (i.e. a request number).

The logref attribute should be optional. Though, in Spring org.springframework.hateoas.VndErrors.VndError:

```
        /**
         * Creates a new {@link VndError} with the given logref, a message as well as some {@link Link}s.
         * 
         * @param logref must not be {@literal null} or empty.
         * @param message must not be {@literal null} or empty.
         * @param links
         */
        public VndError(String logref, String message, Link... links) {

            Assert.hasText(logref, "Logref must not be null or empty!");
            Assert.hasText(message, "Message must not be null or empty!");

            this.logref = logref;
            this.message = message;
            this.add(Arrays.asList(links));
        }
```

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/4f3be119c08a0b5db690fe6727632705baae8e4e.
