### ISSUE TITLE
Jackson2HalModule.EmbeddedMapper private access dilutes reusability

### ISSUE THREAD

**Issue by karlthepagan** [spring-projects/spring-hateoas#480]
https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/hal/Jackson2HalModule.java#L875

I am pursuing a custom Link Data shape (an intermediate in pursuit of json-api) different from HAL.

When attempting to reuse portions of Jackson2HalModule, I can't instantiate HalLinkListSerializer (public) without EmbeddedMapper unless I use the provided HalHandlerInstantiator which brings in its own custom ResourcesSerializer.

Making EmbeddedMapper class public resolves this issue.

**Comment by karlthepagan** [comment]
Jumped out to my home system to fix this - PR #481

**Comment by gregturn** [comment]
Not sure the benefit of making such an inner class public. I wrote a separate mediatype handler for Collection+JSON and didn't need it. Frankly, `EmbeddedMapper` looks to be purely for HAL. Adjusting/expanding it to serve other mediatypes implies it should be a top level class, which I don't agree with.

**Comment by gregturn** [comment]
In general, we don't want the innards of one media type leaking into another and causing coupling.

See #833 for details on how to write your own media type.
