### ISSUE TITLE
UriTemplate Does not handle URLs that contain a space

### ISSUE THREAD

**Issue by JamesTPF** [spring-projects/spring-hateoas#487]
Given a baseURI of
`http://server/domain/attributes?property=foodTypes&style=Healthy%20Snacks`
Which you have to pass into the Traverson constructor (which takes a URI and so values must be correctly encoded).
This URI then gets converted into a String in this method:

```
        private String traverseToFinalUrl(boolean expandFinalUrl) {
            String uri = getAndFindLinkWithRel(baseUri.toString(), rels.iterator());
            UriTemplate uriTemplate = new UriTemplate(uri);
            return expandFinalUrl ? uriTemplate.expand(templateParameters).toString() : uriTemplate.toString();
        }
```

Which is called from

```
        public <T> T toObject(ParameterizedTypeReference<T> type) {
            Assert.notNull(type, "Target type must not be null!");
            return operations.exchange(traverseToFinalUrl(true), GET, prepareRequest(headers), type).getBody();
        }
```

However, in the RestTemplate class this gets converted back into a URI in here:

```
    @Override
    public <T> T execute(String url, HttpMethod method, RequestCallback requestCallback,
            ResponseExtractor<T> responseExtractor, Object... urlVariables) throws RestClientException {

        URI expanded = getUriTemplateHandler().expand(url, urlVariables);
        return doExecute(expanded, method, requestCallback, responseExtractor);
    }
```

The DefaultUriTemplateHandler will then reencode the `%20` to be `%2520` which means that the wrong value gets sent to the server.

So I guess the `traverseToFinalUrl` method when it is expanding the template should decode the variable values?

**Comment by JamesTPF** [comment]
Still investigating the actual cause of this.

**Comment by JamesTPF** [comment]
This issue appears to be fixed in the latest code.

**Comment by olivergierke** [comment]
Closing for now, feel free to reopen if the problem appears again.
