### ISSUE TITLE
example usage of Resources and PagedResources

### ISSUE THREAD

**Issue by jaconstantine** [spring-projects/spring-hateoas#488]
I've implemented collection endpoints by specifying ResponseEntity<Collection<ModelA>> foo()
in my Api and implementing that method in my controller.  What's wrong with that approach?  In fact I have no idea how or why to use Resources or PagedResources at all.  Can you provide:
- why Resources / PagedResources are useful
- detailed example usage for each

Thanks

**Comment by gregturn** [comment]
Here's one example. 

https://github.com/spring-cloud/spring-cloud-spinnaker/blob/master/src/main/java/org/springframework/cloud/spinnaker/ModuleController.java

**Comment by jaconstantine** [comment]
Thanks. Got anything for PagedResources?

**Comment by mvitz** [comment]
As I stumbled over this as well and initially thought it was a bug (see https://github.com/spring-projects/spring-boot/issues/8135) I would like to see some documentation for the Resources class as well.

**Comment by gregturn** [comment]
Check out https://github.com/spring-projects/spring-hateoas-examples.
