### ISSUE TITLE
inconsistent "links" formating

### ISSUE THREAD

**Issue by jaconstantine** [spring-projects/spring-hateoas#489]
I'm using spring-hateoas - 0.20.0.RELEASE, On the same controller, most methods are formatting links like this:

```
    "links": [
      {
        "rel": "self",
        "href": "http://localhost:8090/clown/spite/zsnkq02"
      }
```

but one method is formatting them like this:

```
  "_links": {
    "self": {
      "href": "http://localhost:8090/clown/spite/zsnkq02/crevice/US.NK.003.01.002.02.10/24"
    }
  },
```

Both are being sent the header:   `Accept: application/json` and I'm seeing `Content-Type: application/json;charset=UTF-8` in the response headers.

**Comment by gregturn** [comment]
I've never seen an app with Spring HATEOAS actually mix formats. That is the old format (which is years old) along with HAL.

You might have to put together a sample project and host it on github so we can look at it.

**Comment by jaconstantine** [comment]
Ok, I tried adding the annotation ```@EnableHypermediaSupport(type= {HypermediaType.HAL})``` to the startup class.  That seems to have fixed the issue.

```
@SpringBootApplication
@EnableSwagger2
@EnableHypermediaSupport(type= {HypermediaType.HAL})
@ComponentScan(basePackages = "com.foobar")
public class Swagger2SpringBoot implements CommandLineRunner {
    ...
```

**Comment by gregturn** [comment]
👍

**Comment by Rasive** [comment]
Wow... thanks, this bug was seriously driving me nuts...

**Comment by gregturn** [comment]
Based on the op's last comment, I'm closing this issue.
