### ISSUE TITLE
Option to set arraylist size in resourcesupport

### ISSUE THREAD

**Issue by pulquero** [spring-projects/spring-hateoas#494]
By default, ResourceSupport has a links ArrayList of 16. This can create a bit of bloat if you sometimes have a lot of resources without actual links. It would be nice if there was a constructor to set the size or pass-in a list of links. Or maybe an empty list by default and then grows on adding a first link.

**Comment by gregturn** [comment]
Where do you see this? 

```
public class ResourceSupport implements Identifiable<Link> {

	private final List<Link> links;

	public ResourceSupport() {
		this.links = new ArrayList<Link>();
	}
```

The only way to populate this is using the constructor (which initializes with an empty list) followed by the various add() operations. Hence, nothing is initialized to 16.

Furthermore, it's an anti-pattern to initialize collections with a certain size because you may actually be working against HotSpot.

As to your request for loading up a list, ResourceSupport supports passing in ANY iterable list:

```
	public void add(Iterable<Link> links) {
		Assert.notNull(links, "Given links must not be null!");
		for (Link candidate : links) {
			add(candidate);
		}
	}
```

**Comment by pulquero** [comment]
new ArrayList() by default allocates an array of size 16 or 10 in later java versions.

**Comment by gregturn** [comment]
How is 16 or 10 entries in this day and age bloat? By that same logic we should scan the entire Spring portfolio and every 3rd party library for similar usage and institute similar constructor calls. I would call this premature optimization not based on any profiled metrics.

**Comment by pulquero** [comment]
It adds up for a large number of resource objects (imagine complex response objects with nested resources). Then that multiplied by the number of concurrent requests.

I think there is quite a difference between a transient response object in a high load context and something like a spring bean factory which is long-lived.

This was only a suggestion for a possible improvement based on my experience of using it. You kind of making me wish I hadn't bothered now :-(

**Comment by gregturn** [comment]
I didn't mean to push you down. I just haven't heard anyone mention such an issue. If you have actual metrics tabulating this strain, that would have been useful to post. Or a load bearing test case that would generate the strain, allowing us to profile and come up with a suitable solution. Just throwing out "The default ArrayList of 16 isn't good enough" doesn't sell the problem.

**Comment by pulquero** [comment]
You can count me as the first then. I already have a solution in-place and have made you aware of a potential weakness in the code. It is now up to you to decide whether it represents a use-case you wish to cater for or not.
