### ISSUE TITLE
Alps.Ext lacks required attribute id

### ISSUE THREAD

**Issue by Avonsoft** [spring-projects/spring-hateoas#499]
The extension class [Ext.java](https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/alps/Ext.java) does not correctly implement the ALPS specification, as it is missing the id property.

The specification can be found [here](https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-01#section-2.2.4).

**Comment by Avonsoft** [comment]
Added a pull request #500 to include the property, and fixed the appropriate unit test.

**Comment by olivergierke** [comment]
That's merged, thanks!
