### ISSUE TITLE
`addPaginationLinks` linked in javadocs does not exist and never has

### ISSUE THREAD

**Issue by jroweboy** [spring-projects/spring-hateoas#501]
I've been trying to find some answers about how pagination works in spring-hateoas, but this part has me a little confused. I searched the entire git histroy for the method referenced here https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/PagedResources.java#L116 and it looks like its never existed. I'm curious to know if that see also should just be removed or should that method be written.

**Comment by otrosien** [comment]
There's addPaginationLinks in spring-data-commons (https://github.com/spring-projects/spring-data-commons/blob/db62390de90c93a78743c97cc2cc9ccd964994a5/src/main/java/org/springframework/data/web/PagedResourcesAssembler.java#L208), which is most likely to be meant here.

**Comment by gregturn** [comment]
Given that Spring Data Commons uses Spring HATEOAS, and not the other way around, the javadocs should have this link cleaned out.
