### ISSUE TITLE
Spring HATEOAS Forms support

### ISSUE THREAD

**Issue by anderruiz** [spring-projects/spring-hateoas#503]
Hi to all, we’ve been working (Hdiv Security Team) in an extension for Spring HATEOAS project to support FORMs using several different implementations, i.e. XHTML, HAL-Forms, Siren or Uber. The work is based on Dietrich Schulten initial Affordances implementation. Our changes were pushed to Hdiv-Affordances branch in Spring HATEOAS for Oliver Gierke to review them.

A sample app working with Spring HATEOAS and HAL-Forms is available here:

https://github.com/hdiv/hdiv-bank-for-services -> master

We are currently analyzing the best way to integrate it with Spring Data REST by modifying the RESTBucks showcase also

Anyone that could be interested please contact us without hesitation, all suggestions are welcomed :)

**Comment by gregturn** [comment]
Whereas I support the idea of HAL-FORMS, Siren, and Uber, I don't think XHTML is a good idea. That mediatype is quite dated and given this project is mostly JSON oriented, not sure the value investing in this mediatype.

**Comment by gregturn** [comment]
Superceded by #612 and resolved via https://github.com/spring-projects/spring-hateoas/commit/70448a854098343897fd99e3227b4a61db54b921.

Final solution isn't precisely the same thing, but we plan to iterate over it in the near future and expand to support other mediatypes. Feel free to check the HAL-FORMS section of code and their corresponding unit tests.

Also, see monitor [Spring HATEOAS Examples repo](https://github.com/spring-projects/spring-hateoas-examples) as we plan to add an Affordances example very soon.
