### ISSUE TITLE
Link.valueOf does not accept relations with dot or minus

### ISSUE THREAD

**Issue by helge-tack** [spring-projects/spring-hateoas#504]
The method Link.getAttributeMap uses an incorrect pattern to parse the RFC 5988 relation type. It uses `(\w+)=\"(\p{Alnum}*)"` but should use, according to RC 5988, `(\w+)=\"(\p{Lower}[\p{Lower}\p{Digit}\.\-]*)"`.

**Comment by olivergierke** [comment]
That's in place now. I also added support for URIs as link relations.
