### ISSUE TITLE
Book that illustrates many of the features of Spring HATEOAS

### ISSUE THREAD

**Issue by evarga** [spring-projects/spring-hateoas#512]
Hi Guys,

I would like to share with you an information about my book [Creating Maintainable APIs](http://www.apress.com/9781484221952) in which I devote Part II of the book to hypermedia-driven REST APIs. I've used Spring HATEOAS in the examples to demonstrate the principles in practice. The book is accompanied with a full source code available at GitHub (see the link to the publisher's site).

I hope you will find the content useful!

Thanks,
Ervin

**Comment by olivergierke** [comment]
Thanks for the ping, but this is a bug tracker :/.
