### ISSUE TITLE
Performance of ControllerLinkBuilder#linkTo degrades over time when used with #methodOn

### ISSUE THREAD

**Issue by feffef** [spring-projects/spring-hateoas#525]
When profiling our application we noticed that more time than expected is spent in ControllerLinkBuilder#linkTo.

What's more worrying is that the response times for resources that include a lot of links is not constant, but increases with every request:

**To reproduce this**
- git clone https://github.com/spring-guides/gs-rest-hateoas.git
- add the following code to the GreetingController in the "complete" project
```       
for (int i = 0; i < 1000; i++) {
  greeting.add(linkTo(methodOn(GreetingController.class).greeting("Item" + i)).withRel("item"));
}
````
- The first request to http://localhost:8080/greeting takes several seconds - this is expected given the large number of links
- However, the response times increases with every request to that same resource

Profiling showed that almost all time is spend in AnnotatedParametersParameterAccessor$BoundMethodParameter#asString, which is using the same static DefaultFormattingConversionService instance throughout the lifetime of the service.

Looking at the code it seems that this DefaultFormattingConversionService is using a  ConcurrentReferenceHashMap (GenericConversionService#converterCache) to re-use the same GenericConverter instances for  every unique sourceType / targetType combination.

It looks as if the GenericConversionService#converterCache map is growing with each call to ControllerLinkBuilder#linkTo(Object), which would explain performance decreasing over time (especially because profiling also shows TypeDescriptor#equals as a hotspot)

What I don't understand: 
- is this an issue with the TypeDescriptor instances not being considered equal, when they should be? 
- is the ConcurrentReferenceHashMap not properly removing entries for TypeDescriptors that no longer exists?
- or am I missing something completely different?

With a quick search I only found this post:
http://stackoverflow.com/questions/36303642/spring-hateoas-controllerlinkbuilder-methodon-increasing-response-times-signific

The answers there suggests to simply not use #methodOn because of the additional proxy being created. But our profiling suggests that the time spend creating the proxy and calling its method is insignificant compared to the time spent in ControllerLinkBuilder#linkTo, so I really hope this can be solved without having to give up on using #methodOn.

Hope this helps to narrow this down and looking forward for a solution. as I really like the idea of being able to create links using ControllerLinkBuilder#methodOn that always match the configured path mappings.

**Comment by olivergierke** [comment]
That seems to duplicate #511 and is ultimately caused by an issue in Spring Framework itself (see [this ticket](https://jira.spring.io/browse/SPR-14926). I've put both optimizations on our side in place for #511 and the ticket in Spring Framework is fixed, too, alongside other optimizations (esp. when it comes to controller methods pointed to that use date bindings.

Would you mind giving the 0.22 snapshots a try alongside current Spring Framework snapshots? You should see that issue resolved or at least vastly mitigated.

**Comment by feffef** [comment]
That's great news - also searching for closed issues would have saved me a lot of time :o)

I updated the dependencies in the exampple project
```
        <spring-hateoas.version>0.22.0.BUILD-SNAPSHOT</spring-hateoas.version>
        <spring.version>4.3.5.BUILD-SNAPSHOT</spring.version>
```
and added the snapshot repo
```
    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/libs-snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
```

The same example posted aboce that renders 1000 links now responds within ~800ms on the first request, and ~150/200ms for all repeated requests to the same resource.

Using 0.20.0-RELEASE and 4.3.4.RELEASE, the first request took ~4000ms, and increased by ~3000ms for every follow-up request.

Great work, and this completely resolve the issue for our use case (as we are not dealing with thousands of links per resource in our app, just a few dozens).

Any idea when these versions will be released?

**Comment by olivergierke** [comment]
Thanks again for the detailed write up. We're basically waiting for Spring Framework 4.3.5 shipping, which is scheduled for early next week. So we should have it out as Christmas present the latest 😄 .
