### ISSUE TITLE
Using @GetMapping produces duplicate Paths

### ISSUE THREAD

**Issue by philippn** [spring-projects/spring-hateoas#528]
With release 0.22.0, @GetMapping and friends are supported now. Unfortunately it's completely broken because all paths are being duplicated.

Steps to reproduce:
1) Clone https://github.com/spring-guides/gs-rest-hateoas.git
2) Import /complete as Maven project
3) In the POM set property 
<spring-hateoas.version>0.22.0.RELEASE</spring-hateoas.version>
4) In GreetingController, change @RequestMapping("/greeting") to @GetMapping("/greeting")
5) Launch application and navigate to http://localhost:8080/greeting
6) Inspect self link, see blow for example
![path-duplication](https://cloud.githubusercontent.com/assets/445105/21422988/e0bf7568-c83a-11e6-8803-4259cdc370f6.png)

**Comment by philippn** [comment]
Just tested again with changing it back ti @RequestMapping, and I'm seeing the same behaviour. So this problem is not limited to @GetMapping and friends but of more general nature.

I guess it can be considered a duplicate of #527.

**Comment by olivergierke** [comment]
Resolving as duplicate. Continuing at #527.
