### ISSUE TITLE
"Get Link functionality" of ResourceSupport class

### ISSUE THREAD

**Issue by 6pet6ter6** [spring-projects/spring-hateoas#542]
Links in a ResourceSupport class are stored in an ArrayList, this makes it possible to hold several links with the same 'rel' with different hrefs. If I call the method getLink(rel), only the first matching entry is returned.

	
```
public Link getLink(String rel) {

		for (Link link : links) {
			if (link.getRel().equals(rel)) {
				return link;
			}
		}

		return null;
	}
```
On client side the produced JSON looks like a multi valued map with one or more entries for one rel.
Wouldn't it be better to use such a map in the ResourceSupport class itself to keep consistency?

**Comment by gregturn** [comment]
Since Link and ResourceSupport are mediatype neutral containers, there is no need to force them to store things in relation to one mediatype (HAL in this case).

However, the desire to retrieve ALL links related to a given rel makes sense, given RFC5988 supports this.
