### ISSUE TITLE
PUT/PATCH fails for set of hrefs but POST works

### ISSUE THREAD

**Issue by cliveseldon** [spring-projects/spring-hateoas#548]
I have a class Project which can have a Set of users:

@ManyToMany(fetch=FetchType.EAGER)
private Set<User> members;

POSTs with hrefs to the Users work, e.g.:

curl -i -X POST -H "Content-Type:application/hal+json" -d  '{"members":["http://localhost:9000/api/users/32770","http://localhost:9000/api/users/1"]}' http://localhost:9000/api/projects

but PUT/PATCH fails:

curl -i -X PUT -H "Content-Type:application/hal+json" -d  '{"members":["http://localhost:9000/api/users/32770","http://localhost:9000/api/users/1"]}' http://localhost:9000/api/projects/32773

The Error is:
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of example.jpa.model.User: no String-argument constructor/factory method to deserialize from String value ('http://localhost:9000/api/users/1')

Doing the same PUT with a single item in the list succeeds, e.g.:

curl -i -X PUT -H "Content-Type:application/hal+json" -d  '{"members":["http://localhost:9000/api/users/1"]}' http://localhost:9000/api/projects/32773

I have seen some related issues for PUT but nothing that seems to resolve this issue.

I'm using : spring-data-rest-core-2.5.6.RELEASE

**Comment by cliveseldon** [comment]
Looking at the code I don't quite understand the logic in org.springframework.data.rest.webmvc.json.handleArrayNode
which seems to loop over the current values. 

	private boolean handleArrayNode(ArrayNode array, Collection<Object> collection, ObjectMapper mapper,
			TypeInformation<?> componentType) throws Exception {

		Assert.notNull(array, "ArrayNode must not be null!");
		Assert.notNull(collection, "Source collection must not be null!");
		Assert.notNull(mapper, "ObjectMapper must not be null!");

		// We need an iterator for the original collection.
		// We might modify it but we want to keep iterating over the original collection.
		Iterator<Object> value = new ArrayList<Object>(collection).iterator();
		boolean nestedObjectFound = false;

		for (JsonNode jsonNode : array) {

			if (!value.hasNext()) {

				Class<?> type = componentType == null ? Object.class : componentType.getType();
				collection.add(mapper.treeToValue(jsonNode, type));

				continue;
			}

			Object next = value.next();

			if (ArrayNode.class.isInstance(jsonNode)) {
				return handleArray(jsonNode, next, mapper, componentType);
			}

			if (ObjectNode.class.isInstance(jsonNode)) {

				nestedObjectFound = true;
				doMerge((ObjectNode) jsonNode, next, mapper);
			}
		}

		// there are more items in the collection than contained in the JSON node - remove it.
		while (value.hasNext()) {
			collection.remove(value.next());
		}

		return nestedObjectFound;
	}


if the existing collection and new JSON collection are the same size it returns ok from this method but tries to do an addition to the DB which fails. If the new JSON collection is longer in my case it will try to simple deserialize the object which is where the exception occurs:
if (!value.hasNext()) {

				Class<?> type = componentType == null ? Object.class : componentType.getType();
				collection.add(mapper.treeToValue(jsonNode, type));

				continue;
			}

**Comment by alanhay** [comment]
See: https://jira.spring.io/browse/DATAREST-1041?jql=project%20%3D%20DATAREST%20AND%20status%20%3D%20Open%20ORDER%20BY%20priority%20DESC

**Comment by gregturn** [comment]
This is a Spring Data REST issue. Track outcome in https://jira.spring.io/browse/DATAREST-1041.
