### ISSUE TITLE
Extract @Id fields from @Entities

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-hateoas#55]
I wonder if it might be useful to allow the @Id from JPA @Entities to be used automatically instead of implementing the Identifiable interface.

Here is some existing code that might be useful:

https://github.com/philwebb/springfaces/blob/2fab4ed3e265e4ea19365a4a811af0414f50cc10/springfaces/src/main/java/org/springframework/springfaces/selectitems/ui/SelectItemsJpaSupport.java

**Comment by gregturn** [comment]
Spring HATEOAS has dropped the `Identifiable` interface, so this is no longer relevant.
