### ISSUE TITLE
ResourceProcessor for Resources is not getting called

### ISSUE THREAD

**Issue by FabianWilms** [spring-projects/spring-hateoas#570]
I want to add additional links to some entities I'm persisting by a CrudRepository. I got the following code to work:
```
public class Grunddaten_ResourceProcessor implements ResourceProcessor<Resource<Grunddaten_>>
```
This processor gets called whenever I request a single entity.

But now I want to add the link to a list of entities, too. So I implemented the following:

```
public class Grunddaten_ResourcesProcessor implements ResourceProcessor<Resources<Grunddaten_>>
```

This processor does *not* get called. So I followed some stackoverflow users tip to try and create a processor which has the following signature:

```
public class Grunddaten_ResourcesProcessor implements ResourceProcessor<ResourceSupport>
```

As expected, this processor gets called everytime. By debugging I found out that the entities I want to add the links to are wrappe like this `<Resources<PersistentEntityResource>>`. So I created a processor which uses this type. But it doesn't get called! So currently I'm using a processor for `ResourceSupport` objects and inside I filter out everything I'm not interested in and it works. But that's kind of hacky and I don't understand why it simply won't work, no matter what I do.

**Comment by gregturn** [comment]
Is it possible for you to stage a complete Boot app depicting the problem you are seeing?

**Comment by FabianWilms** [comment]
Sorry, took some time to find the time :wink: 
https://github.com/FabianWilms/SpringRessourceProcessor

Take a look at the test classes. You can see the results on the Travis CI page of the project:
https://travis-ci.org/FabianWilms/SpringRessourceProcessor

As you can see the `ResourceProcessor` for `Resources<Citizen>` never gets called.

**Comment by gregturn** [comment]
Okay, thanks @FabianWilms. I'll take a peek.

**Comment by gregturn** [comment]
@FabianWilms I found time and cracked open your sample project. Check out the linked PR to your sample project for the solution.

**Comment by FabianWilms** [comment]
@gregturn Thank your very much for your help! Kind regards.
