### ISSUE TITLE
Getting  java.lang.IllegalStateException: Could not find current request via RequestContextHolder. 

### ISSUE THREAD

**Issue by umangsingh123** [spring-projects/spring-hateoas#573]
I am using HATEOS with DefferedResult object but it gives me an IllegalStateException . 
 The scenario is that from the controller i need to create a self link . I have extended my resources with the Resource Support API.
Using the below code snapshot in controller

```
Observable<Response> o = service.getresponse();
DeferredResult<response> deffered = new DeferredResult<PlansResponse>();
	
		o.subscribe(response -> deffered.setResult(getresponse(response)), e -> deffered.setErrorResult(e));

return deffered;
}

// the private method code 
getresponse(..){

resp.add(linkTo(methodOn(Controller.class).getABC(payload)).withSelfRel());
}
```
**I understand that the controllerBuilder doesnt work outside the HTTP request but how to overcome this issue.**

**Comment by gregturn** [comment]
Let's try to build up the details of your problem in one issue.

Duplicates #574
