### ISSUE TITLE
target will not release while useing spring-data-jpa

### ISSUE THREAD

**Issue by clw87** [spring-projects/spring-hateoas#576]
I use spring-data-jpa to develop web application, fount that, the line of 232 class 'org.springframework.aop.framework.JdkDynamicAopProxy' has a false condition '!targetSource.isStatic()' while implements 'SingletonTargetSource', then my memery is filled full

**Comment by alfredosc8** [comment]
I've similar issue, returning PagedResource from restController call, it stays in memory after GC. It's looklike the static NO_PAGE used on different classes is blocking the instance to be finalized.

**Comment by gregturn** [comment]
This issue says nothing about Spring HATEOAS.

**Comment by gregturn** [comment]
Closing the issue.
