### ISSUE TITLE
Decimal Formatting with linkTo generated Paths?

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-hateoas#598]
Is there a way to control the format of numbers with decimals that are generated using the typesafe `linkTo` strategy?

For example using the following controller method, note the `Double` type for the second parameter:

```
@GetMapping("/docs/{titleId}/{version:.+}")
DocumentResource getDocument(@PathVariable("titleId") String titleId, 
                             @PathVariable("version") Double version) {
}
```

this code:

```
linkTo(methodOn(DocController.class).getDocument(titleId, version)).withSelfRel();
```

might generated something like:

```
"self": {
            "href": "http://localhost/docs/abc/2.0"
        }
```

Is there a way to format the decimal without the `.0`? For example:

```
"self": {
            "href": "http://localhost/docs/abc/2"
        }
```

**Comment by gregturn** [comment]
There is nothing currently for doing that. Though in the scenario I'd question putting a decimal in a URI.

**Comment by punkstarman** [comment]
@gregturn some APIs need decimals in the URI. Two examples are:

- an API that generates a map surrounding coordinates expressed in latitude and longitude
- an API that tracks resource versions

**Comment by punkstarman** [comment]
@pluttrell, I have come across a similar "problem" but when mapping a request URL to a controller. By default, Spring MVC adds an extension pattern to the request mapping, e.g. `@RequestMapping("/abc")` recognizes `/abc` and `/abc.*`. This allows content negotiation to be based not only on the Accept header, but also on the extension given, e.g. `/abc.json` provokes rendering the resource as JSON, `/abc.xml` renders the resource as XML. This is useful for testing through a simple browser.

To disable this behavior, when you anticipate period characters in your URLs, look at the documentation for [`RequestMappingHandlerMapping#setUseSuffixPatternMatch`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.html#setUseSuffixPatternMatch-boolean-).

I'm not sure if this will fix your problem though.

**Comment by gregturn** [comment]
The only way I can see controlling something like 1/3 being properly managed is to make it a string and then converting inside the controller.

**Comment by gregturn** [comment]
If the REAL issue here is Spring MVC's suffix-based content negotiation, then I'll close this issue given @punkstarman 's [solution](https://github.com/spring-projects/spring-hateoas/issues/598#issuecomment-308047414) should tackle that.
