### ISSUE TITLE
The selector of versioning on hateoas page is not displaying the right information

### ISSUE THREAD

**Issue by ecukalla** [spring-projects/spring-hateoas#607]
The `selector selectpicker`, is not displaying the versions on HATEOAS spring.io project page.

<img width="1280" alt="screen shot 2017-07-03 at 18 54 07" src="https://user-images.githubusercontent.com/775064/27801945-0db640dc-6021-11e7-9af7-c07be5d42707.png">

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/33f35c888d56a1b8e985845293be25dd240e3f07
