### ISSUE TITLE
The link generation is changed between 0.17.0.RELEASE and 0.23.0.RELEASE

### ISSUE THREAD

**Issue by priyapawarrao** [spring-projects/spring-hateoas#609]
Same code gives different links format between different versions of the release. Has something modified? Shouldn't this be backward compatible?

Sample code:

@RequestMapping(value = "/{id}/request/template", method = GET, produces = { MediaType.APPLICATION_JSON_VALUE })
@RestResponse
public String getTemplate(
         @ApiParam(value = "The ID of a item") @PathVariable("id") UUID Id,
         @ApiParam(value = "Optional group Id", required = false) @RequestParam(value = REQUEST_PARAM_BUSINESS_GROUP_ID, required = false) String GroupId,
         @ApiParam(value = "Optional user for whom this request is being made", required = false) @RequestParam(value = REQUEST_PARAM_REQUESTED_FOR, required = false) String requested) {

      return this.requestService.getTemplateCatalogItemProvisioningRequest(Id, GroupId, requested);
   }

org.springframework.hateoas.Link itemLink = linkTo(
            methodOn(ItemController.class)
                  .getTemplate(item.getId(), null, null)).withRel("Get Item");

**Output in 0.17:**

Link: 

"rel": "GET Item",
"href": "https://demo-env/api/9e469693-f8c2-4cb1-9112-797ea151dc64/requests/template"

**Output in 0.23:**

Link: 

"rel": "GET Item",
"href": "https://demo-env/api/9e469693-f8c2-4cb1-9112-797ea151dc64/requests/template{?GroupId, requested}"

**Comment by olivergierke** [comment]
That's correct and expected. If you want to get rid off the template parameters, call `….expand()` (without any parameters) on the `Link` instance created.
