### ISSUE TITLE
Affordances concept

### ISSUE THREAD

**Issue by osvaldopina** [spring-projects/spring-hateoas#610]
I'm taking a look at feature/hal-forms branch because I'm very interested in hal-forms and I saw the Affordance concept implemented there. In this 
implementation a link has a list of affordances. But isn't the link an affordance by itself?

**Comment by gregturn** [comment]
This is highly experimental. I haven't modeled all the concepts. But essentially, a link can have one or more Affordances. In HAL-Forms, a link can be associated with one or more templates.

**Comment by gregturn** [comment]
The real riddle is what is the minimal tweak to defining a HAL-Form above what it takes to currently lay out hypmermedjs.

**Comment by gregturn** [comment]
All things stated, this is an issue tracker not a discussion forum. There is no value opening a ticket against a branch that hasn't even been submitted for peer review because it's being developed.
