### ISSUE TITLE
Including a custom Converter to the HATEOAS link converters

### ISSUE THREAD

**Issue by dshunfen** [spring-projects/spring-hateoas#620]
Having started used the HATEOAS Spring framework, I've found the `ControllerLinkBuilder` _linkTo_ and _methodOn_ methods to be very useful to link resources to one another. 

However, since some controller classes may use an `Enum` as a `PathVariable`, one may want to include those `Enum`'s in links by using their `Enum` _value_ using a custom `Converter`, and not by their _name_. The default Enum -> String `Converter` uses the `Enum`'s _name_ to do this conversion.

Unfortunately, because of this referenced line, the HATEOAS spring framework creates a new `DefaultFormattingConversionService` and doesn't include `Converter`s that are created as Bean's within an `ApplicationContext` or via `DefaultFormattingConversionService.addFormatters`.

**Example**
Creating a simple GET mapping with the following path:
```java
@GetMapping(value = "/{myEnum}")
public ResponseEntity<ConfigPhaseType> get(@PathVariable("myEnum") final MyEnum myEnum) {
      return new ResponseEntity<>(myEnum, HttpStatus.OK);
}
```
And then creating a resource link to that path like this:
```java
@GetMapping(value = "/")
public ResourceSupport getMyEnum() {
      ResourceSupport res = new ResourceSupport();
      res.add(linkTo(methodOn(EnumConverterExample.class).get(MyEnum.EXAMPLE)).withSelfRel());
}
```
Will always give:
```javascript
links: [{
      rel: "self",
      href: "http://localhost:8080/api/EXAMPLE"
}]
```
in the HATEOAS link. As opposed to using the Enum "value", be it an int or String, etc. because of Spring HATEOAS always creating a new `DefaultFormattingConversionService`.

Could we mix in `Converter` classes on the `ApplicationContext` to the list of converters HATEOAS uses for links or at least provide some way to add them to the `ConversionService` explicitly?

https://github.com/spring-projects/spring-hateoas/blob/05f687ef399352214f8c06c96d1f61cdff8c2213/src/main/java/org/springframework/hateoas/mvc/AnnotatedParametersParameterAccessor.java#L133

**Comment by olivergierke** [comment]
Duplicates #118.

**Comment by olivergierke** [comment]
Thanks for reporting this. This is being worked on in the context of #618 (the original ticket being #118). Unsure how to resolve that as the static `ControllerLinkBuilder` limits our ability to pick up Spring MVC configuration.

**Comment by dshunfen** [comment]
Thank you for getting back so quickly Oliver. Makes sense. I'll subscribe to https://github.com/spring-projects/spring-hateoas/issues/118 so I can track what is going on with these static helpers.
