### ISSUE TITLE
ControllerLinkBuilder does not consider a request url and uses the first request mapping value

### ISSUE THREAD

**Issue by peterjurkovic** [spring-projects/spring-hateoas#630]
Consider following controller

```java
@RestController
public class MyController {
   

    @GetMapping(value = {"/resource/{id}", "/beta/audit/resource/{id}"})
    public EventResource getById(@PathVariable String id){
        // ...
    }
}
```

Here is my DTO object

```java
import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;
import static org.springframework.hateoas.mvc.ControllerLinkBuilder.methodOn;

public class MyResource extends ResourceSupport{
    
    public MyResource(Entity entity){
    Link self = linkTo(methodOn(MyController.class).getById(entity.getId())).withSelfRel();
        add(self);  
    }
}

```

If I do a request `http http://localhost:8080/beta/audit/resource/3698977` (using httpie)
a response looks like following

```
{
    "_embedded": {
        "items": [
            {
                "_links": {
                    "self": {
                        "href": "http://locahost:8080/resource/3698977"
                    }
                }, 
                "id": 3698977, 
            }, 
            ]
    }
}
```

**What I would expect is following:**
1. If a request url is `http://locahost:8080/resource/3698977` the `self` value should be `http://locahost:8080/resource/3698977`
2. If a request url is `http://localhost:8080/beta/audit/resource/3698977` the `self` value should be
`http://localhost:8080/beta/audit/resource/3698977` 

Am I doing something wrong?

I am using the latest version `spring-hateoas:0.23.0.RELEASE`

**Comment by gregturn** [comment]
I believe that right now, if there are multiple routes, Spring HATEOAS uses the first to construct a link.

**Comment by olivergierke** [comment]
That's not really a bug by design due to #186. I'm not sure we should implement so sort of guesswork around which one to chose based on the current request.

**Comment by gregturn** [comment]
Additionally, "self" link means "canonical" link, and that should be the same for everyone, regardless of context, because that is what canonical links are. To have a self link change just because of the query URI doesn't add up.

NOTE: This isn't the same as altering the URI/port due to proxy headers. In such circumstances (which Spring HATEOAS supports), changing the hostname but KEEPING the same path is the nature of HTTP and of REST.

**Comment by peterjurkovic** [comment]
OK, thanks for your feedback.
