### ISSUE TITLE
ResourcesMixin ignored with spring boot 1.5.7.RELEASE

### ISSUE THREAD

**Issue by roll57** [spring-projects/spring-hateoas#631]
After migration from spring boot **1.5.6.RELEASE** to **1.5.7.RELEASE**, the mixin defined by spring-hateoas are ignored when serializing a Resources (i.e. `org.springframework.hateoas.hal.ResourcesMixin`).

I notice that this problem is caused by https://jira.spring.io/browse/DATACMNS-1152,

Since the `ProjectingJackson2HttpMessageConverter` is using the `objectMapper` containing the mixin, the method `org.springframework.hateoas.config.HypermediaSupportBeanDefinitionRegistrar.Jackson2ModuleRegisteringBeanPostProcessor#potentiallyRegisterModule` will not register the `TypeConstrainedMappingJackson2HttpMessageConverter` because the method `Jackson2HalModule.isAlreadyRegisteredIn(objectMapper)` will return true.

The method `Jackson2HalModule.isAlreadyRegisteredIn(objectMapper)` was returning false with spring boot 1.5.6.RELEASE

**Comment by gregturn** [comment]
Spring Boot is now up to 1.5.19.RELEASE. Can you verify whether this is still an issue?

**Comment by roll57** [comment]
I am not able to test again my issue, sorry about that.

I guess that you could close the item.
