### ISSUE TITLE
Allow VndError  to have children. 

### ISSUE THREAD

**Issue by douglassparker** [spring-projects/spring-hateoas#651]
The [vnd error specification](https://github.com/blongden/vnd.error) vnd error specification allows multiple errors to be reported as a list or by the use of embedded errors.  If using embedded errors, only the top error will typically have a logref. From the  spec:

## Nested Errors
Nested errors may be represented by embedding multiple errors inside a vnd.error resource.

```JSON
{
    "message": "Validation failed",
    "logref": 42,
    "_links": {
        "describes": {
            "href": "http://path.to/describes"
        },
        "help": {
            "href": "http://path.to/help"
        },
        "about": {
            "href": "http://path.to/user/resource/1"
        }
    },
    "_embedded": {
        "errors": [
            {
                "message": "Username must contain at least three characters",
                "path": "/username",
                "_links": {
                    "about": {
                        "href": "http://path.to/user/resource/1"
                    }
                }
            }
        ]
    }
}
``` 

Add code to allow VndError to contain an array of other VndError. To easily serialize correctly, I recommend as the method signature.

```Java
VndError[] getErrors()
```

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/4f3be119c08a0b5db690fe6727632705baae8e4e.
