### ISSUE TITLE
Adding new HttpMessageConverters does not work

### ISSUE THREAD

**Issue by Oni1** [spring-projects/spring-hateoas#654]
I'm developing a HAL-based REST API with spring-boot and spring-hateoas. I have a bean in my configuration class, which adds a new `ByteArrayHttpMessageConverter`, because my Controller returns a `ByteArrayResource`. When i debug the application and end up in the `AbstractMessageConverterMethodProcessor` class, i can't see my `ByteArrayHttpMessageConverter` in the `messageConverters` list. 
![spring-hateoas](https://user-images.githubusercontent.com/15093237/31674216-8b3f0fbe-b361-11e7-93e7-733f4fbd97a8.png)

My config file looks like this:
```
@Configuration
public class MyConfig{
    private static final String SPRING_HATEOAS_OBJECT_MAPPER = "_halObjectMapper";
    
    @Autowired
    @Qualifier(SPRING_HATEOAS_OBJECT_MAPPER)
    private ObjectMapper springHateoasObjectMapper;
    
    @Autowired
    private Jackson2ObjectMapperBuilder springBootObjectMapperBuilder;

    @Bean(name = "objectMapper")
    @Primary
    ObjectMapper objectMapper()
    {
        this.springBootObjectMapperBuilder.configure(this.springHateoasObjectMapper);
        return springHateoasObjectMapper;
    }
    
    @Bean
    public HttpMessageConverters customConverters() {
        ByteArrayHttpMessageConverter arrayHttpMessageConverter = new ByteArrayHttpMessageConverter();
        arrayHttpMessageConverter.setSupportedMediaTypes(Arrays.asList(MediaType.APPLICATION_OCTET_STREAM));
        return new HttpMessageConverters(arrayHttpMessageConverter);
    }
    
    @Bean
    public Jackson2ObjectMapperBuilderCustomizer objectMapperBuilder() {
        return builder -> builder.configure(springHateoasObjectMapper);
    }
}
´´´       

I'm using version 0.23.0.RELEASE of spring-hateoas.

**Comment by gregturn** [comment]
Duplicates #118, #352, and #149.

**Comment by gregturn** [comment]
Right now, Spring HATEOAS has a static-based configuration that has a BIG side effect of making dynamic updates like this tricky. The linked PR is  _a_ solution, but possibly not the best one. We're looking at tackling this in the new 1.0 branch in a more fluid, Spring fashion.

**Comment by Oni1** [comment]
@gregturn Which linked PR are you talking about? Thank you, for the answer.

**Comment by gregturn** [comment]
Sorry, left out #618

**Comment by Oni1** [comment]
I couldn't solve my problem with the PR. I found a stackoverflow answer, what solved the problem. This should be better handled from spring-hateoas....

My code:

```
@EnableHypermediaSupport(type = HypermediaType.HAL)
@Configuration
public class ServerConfig extends WebMvcConfigurationSupport {
	
	@Autowired
	private RequestMappingHandlerAdapter adapter;
	
	@PostConstruct
	public void initStuff() {
	    List<HttpMessageConverter<?>> messageConverters = adapter.getMessageConverters();
	    ByteArrayHttpMessageConverter arrayHttpMessageConverter = new ByteArrayHttpMessageConverter();
	    ResourceHttpMessageConverter resourceHttpMessageConverter = new ResourceHttpMessageConverter();
	    messageConverters.add(0, arrayHttpMessageConverter);
	    messageConverters.add(0, resourceHttpMessageConverter);
	}
}
```

**Comment by gregturn** [comment]
The issue with using`@EnableHypermediaSupport` is you disable all the things supplied by Spring Boot and take it into yourself. So that isn't an optimal solution for most people. 

It's an issue @olivergierke and I are looking into for a better developer experience.

**Comment by connorwyatt** [comment]
Is there any update on this? I'm currently having to use strings for my endpoints as I'm using value objects for all my ID path variables. Just wondering if there is a plan?

**Comment by gregturn** [comment]
Superseded by https://github.com/spring-projects/spring-hateoas/issues/833
