### ISSUE TITLE
Fully implement HAL specification for Links.

### ISSUE THREAD

**Issue by douglassparker** [spring-projects/spring-hateoas#656]
See https://tools.ietf.org/html/draft-kelly-json-hal-08#section-5 for a list of the HAL Link, paraphrased below. The implementation of Link only complies with sections 5.1 and 5.2 and does not comply with sections 5.3 - 5.8. While I understand you may have philosophical differences with the specification on the inclusion of some of these attributes, I submit that one should not claim to support a standard unless one does so faithfully.

5.1.  href REQUIRED. 
5.2.  templated OPTIONAL. 
5.3.  type OPTIONAL. 
  Its value is a string used as a hint to indicate the media type expected when dereferencing the target resource.
5.4.  deprecation  OPTIONAL. 
   Its presence indicates that the link is to be deprecated (i.e. removed) at a future date.  Its value is a URL that SHOULD provide further information about the deprecation. A client SHOULD provide some notification (for example, by logging a warning message) whenever it traverses over a link that has this property.  The notification SHOULD include the deprecation property's value so that a client maintainer can easily find information about the deprecation.
5.5.  name OPTIONAL. 
   Its value MAY be used as a secondary key for selecting Link Objects which share the same relation type.
5.6.  profile OPTIONAL.
   Its value is a string which is a URI that hints about the profile (as defined by [I-D.wilde-profile-link]) of the target resource.
5.7.  title OPTIONAL.
   Its value is a string and is intended for labeling the link with a human-readable identifier (as defined by [RFC5988]).
5.8.  hreflang OPTIONAL.
   Its value is a string and is intended for indicating the language of the target resource (as defined by [RFC5988]).

**Comment by gregturn** [comment]
Please clarify what is missing in light of https://github.com/spring-projects/spring-hateoas/pull/567.

**Comment by douglassparker** [comment]
Apparently, I have an older version that does not have this change.  This is a duplicate of 567. I will close. Thank you for quick response.

**Comment by gregturn** [comment]
We're close to making a 0.24 release, which should include this. Until then, if you use 0.24.0.BUILD-SNAPSHOT, you'll have access to this.
