### ISSUE TITLE
Hateoas appending optional parameters to the return link

### ISSUE THREAD

**Issue by verznev** [spring-projects/spring-hateoas#675]
Hateoas appending null value parameters to the return link.
Ex.
http://localhost:8080/transactions?startDate=2017-10-01T00:59:00.000Z&endDate=2017-10-21T23:59:00.000Z&offset=0&limit=5{&merchantRefNum,currency,accountGroup}

merchantRefNum, currency, and accountGroup are optional fields.
I use ControllerLinkBuilder methodOn and linkTo methods.
This is only happen after I upgrade spring Brixton.SR1 to Dalston.SR3
The temporary solution I made is to use org.springframework.hateoas:spring-hateoas:0.21.0.RELEASE. 
org.springframework.hateoas:spring-hateoas:0.23.0.RELEASE is use by Dalston.SR3 by default.

**Comment by maganv** [comment]
This looks like the same behaviour as discussed in [541](https://github.com/spring-projects/spring-hateoas/issues/541). If you want the non-templated URI you can call the `expand`-method on the `Link` without any parameters. See Oliver´s comment in #541.

**Comment by olivergierke** [comment]
Correct, works as designed.
