### ISSUE TITLE
Not working with Spring 5.X.X Reactive (Flux/Mono)

### ISSUE THREAD

**Issue by JSlain** [spring-projects/spring-hateoas#677]
Endpoints doesn't seem to work with new Spring Reactive web application type.

Just changing
`application.setWebApplicationType(WebApplicationType.REACTIVE);`
to 
`application.setWebApplicationType(WebApplicationType.SERVLET);`
fix the thing (but my reactive application won't work anymore).

Of course, I don't expect hateoas endpoints to return Flux!
I just expected them to work as before.
Is there a workaround?

**Comment by gregturn** [comment]
"I don't expect HATEOAS endpoints to return Flux"
"I just expected them to work as before."

This sounds contradictory. Simply put Spring HATEOAS has never worked with Spring WebFlux. 

It's on our list of todos to add WebFlux support but it doesn't work today. There is a lot of effort to add this so dont expect it overnight.

**Comment by JSlain** [comment]
Sorry, i may express myself badly (or misunderstand your answer).
By setting my application to REACTIVE, i can add endpoints that returns `Flux<Something>`, but also old fashion `List<Something>` (which isn't reactive).
I thought my hateoas endpoint would just still work.

**Comment by JSlain** [comment]
I think that's more **reactive** related than hateoas specific...

**Comment by MustaphaCh** [comment]
@gregturn the Spring HATEOAS still not work with Spring web flux ?

**Comment by gregturn** [comment]
No. 

We haven’t begun the effort to handle this. The entire Jackson interaction is blocking on top of the APIs to glean a current web request being hip tied to the servlet spec. 

To write WebFlux happy variant would be a huge effort which is why we haven’t taken it on yet.
