### ISSUE TITLE
Move `ResourcesAssembler` to spring-hateoas

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-hateoas#684]
Wouldn't be a good idea to move the https://github.com/spring-projects/spring-hateoas-examples/tree/master/commons/src/main/java/org/springframework/hateoas classes to the spring-hateoas projects? Might be useful for others.

I'm creating some similar interface + base impl to have a 

`Resources<D> toResources(Iterable<? extends T> entities);`

Until now I was simple returning a collection like:

```
val constructors = constructorRepository.findAll(predicate, Sort.by("name"))
val resources = constructorResourceAssembler.toResources(constructors))
return ResponseEntity.ok().body(resources)
```

But this is only returning an array not an HAL collection with `_embedded` object.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/a56392ac7c48b57322c71ef9c2592dcffe2a1354.

**Comment by gregturn** [comment]
Duplicates #591.
