### ISSUE TITLE
Access JPA entity id from within a ResourceProcessor

### ISSUE THREAD

**Issue by gehreleth** [spring-projects/spring-hateoas#688]
Suppose, I've got a JPA repository declared like this:

```
@RepositoryRestResource(path = "storage-node", excerptProjection = IBrief.class)
public interface IStorageNodeRepository extends JpaRepository<StorageNode, Long> {
  @Query("FROM StorageNode sn WHERE sn.parent is null order by sn.uploadTs ASC")
  List<StorageNode> findAllRootNodes();
}
```

Now, I'd like to add a link to method restoring branch structure from a node to a root by doing N consequential SQL queries and supplying each node along the trunk with its non-expanded siblings. I can't do it within a single query, so I  wrote a supplementary Controller which accepts nodeId as a path variable. Now I'd like supple each node in the repository with a link to this method:

```
  @Bean
  public ResourceProcessor<Resource<StorageNode>> storageNodeProcessor() {
    return resource -> {
   resource.add(linkTo(methodOn(StorageBrowser.class).populateBranch(resource.getContent().getId())).withRel("branch"));
      return resource;
    };
 }
```

Alas, it's not working because getId is't accessible because the Proxy isn't providing this method, but, in fact, provides everything else. I don't understand why.

**Comment by olivergierke** [comment]
I am not sure I can follow. `Resource.getContent()` gives you the entity whose design you control.

Also, be advised that you can't use Lambdas for `ResourceProcessor` implementations as Lambdas do not expose the generics information properly at runtime so that Spring HATEOAS won't be able for which resources it is supposed to call your processor. This is unfortunate but a fundamental limitation of Lambdas.

**Comment by olivergierke** [comment]
I know this is a PITA and I've brought this up with the JDK team already but they resort on "works as designed" :(. If we started documenting this, we'd effectively have to do this for every SAM type that might be used as a bean and undergoes generics inspection which is not really maintainable.

**Comment by gehreleth** [comment]
Your generic example looks like this though. It doesn't try to extract and/or analyze some data from embedded entity during new link addition (which may cause problems such as mine), so dealing with this underwater rock comes to clients of this library who have less expert knowledge about java's fragile features.

```
@Bean
public ResourceProcessor<Resource<Person>> personProcessor() {

   return new ResourceProcessor<Resource<Person>>() {

     @Override
     public Resource<Person> process(Resource<Person> resource) {

      resource.add(new Link("http://localhost:8080/people", "added-link"));
      return resource;
     }
   };
}

```
