### ISSUE TITLE
Add toResources to ResourceAssembler

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-hateoas#694]
The `toResources(Iterable<T>)` method on `ResourceAssemblerSupport` is useful, but I am not wanting to extend from the class. The logic of `toResources` is generic enough that I suggest making it a default method on `ResourceAssembler` when this module moves to a Java 8 baseline.

**Comment by gregturn** [comment]
Overlaps #632

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/a5979607117afb54ef477d91e7631b4778f86a7a.
