### ISSUE TITLE
Spring property resolved in @RequestMapping but not in Hateos link

### ISSUE THREAD

**Issue by Rashin46** [spring-projects/spring-hateoas#696]
I wanted to create custom mapping based on some spring property. What I did was adding the spring property to RequestMapping like this:
```java
@RequestMapping(value = "/api/${property.version}", produces = HAL_JSON_VALUE)
```

My application.properties contains only this property:
`property.version=v2`

And if I start the service I can see that the property has been resolved:
`Mapped "{[/api/v2/hello],methods=[GET],produces=[application/hal+json]}" onto public com.test.hateos.testhateos.domain.Message com.test.hateos.testhateos.controller.HomeController.hello()`

However the generated self link for my resource does not resolve this property:

```
"_links": {
    "self": {
        "href": "http://localhost:8080/api/${property.version}/hello"
    }
}
````
I was expecting that the property will be resolved in the self link too.
See my [test project](https://github.com/spring-projects/spring-hateoas/files/1698567/test-hateos.zip) attached.
You can find a failing test regarding this problem.

**Comment by gregturn** [comment]
Duplicates #602.

**Comment by gregturn** [comment]
BTW, I'd vote against versioning your API. It not recommended per Roy Fielding. 

https://www.infoq.com/articles/roy-fielding-on-versioning

As a practical aside, it's unnecessary with Spring HATEOAS. Check out the following example where changes are rolled out without needing versioning:

https://github.com/spring-projects/spring-hateoas-examples/blob/master/api-evolution/README.adoc

**Comment by Rashin46** [comment]
Oh, sorry I didn't find the duplicate. I will close this issue. 
Thanks for the advise but this was only for example.
