### ISSUE TITLE
JAX RS @ApplicationPath linkTo() not working.

### ISSUE THREAD

**Issue by marcuslange** [spring-projects/spring-hateoas#697]
linkTo methods for JAX RS are ignoring the prefix set by @ApplicationPath

**Comment by gregturn** [comment]
The JAX-RS support is presently minimal. I am poking around at increasing its support so we can also support hypermedia on that platform.

**Comment by gregturn** [comment]
JAX-RS support was removed as of #700.

Essentially, if someone else wishes to build an extension of Spring HATEOAS using our abstractions, etc., they can.
