### ISSUE TITLE
ResourceAssemberSupport with no domain object.

### ISSUE THREAD

**Issue by karlnicholas** [spring-projects/spring-hateoas#704]
My Resource is a combination of several DTO, or perhaps several domain entities if you prefer. This is required because of micro-services architecture. All services are returning single table entities but when I want to join them into a complex entity I do so with a new API that calls all the other services. 

So, if I need to make a set of links for this Resource there is no single domain entity and ResourceAssemblerSupport<T, D extends ResourceSupport> is meaningless. There is no &lt;T&gt;.

A little new to this so I may be missing something obvious, but I'm not sure where the domain object is necessary in the world of _links anyway. The ID of the domain entity I can as useful, but other calls I have made so far explicitly require an ID and make no use of the domain entity anyway.

Seems like a poor design issue.

**Comment by gregturn** [comment]
For starters `ResourceAssembler` only makes sense if you have a bare domain object vs. one imbued with links. If your resource-level domain objects are already `ResourceSupport`-powered, then `ResourceAssembler` may not be necessary. It simply provides a place to consolidate link making based on the domain. For example, in a controller that may need to do this conversion multiple times, it can avoid repetition. But the same thing can be accomplished via some static method.

It's perfectly fine if the domain of your resources is different than the domain of your repositories/services.

As long as the return types of your Spring MVC controllers are `ResourceSupport`-based, Spring HATEOAS should properly render them as HAL.

**Comment by karlnicholas** [comment]
Well, I'm not following here. ResourceAssembler requires a DTO that extends ResourceSupport. I would expect the purpose of having my DTO extend ResourceSupport is so that I _can_ use ResourceAssembler. 

It doesn't make sense to me when you say the MVC controllers are ResourceSupport based. It's the DTOs that extends ResourceSupport. What does the MVC controllers have to do with it?

My goal is to generate HAL links for my API, but I haven't gotten there yet because of minimal  documentation and lack of obvious examples and still working at it. I _did_ get HAL links once from Spring by using Spring Data Rest which has the HAL stuff built in, but I'm not able or willing to use Spring Data Rest with this project and haven't exactly sat down to read all that code to see if I can figure out the magic incantations. 

From a preliminary look and via docs I was steering towards the ResourceAssembler and trying to understand that. For a simple domain object ResourceAssembler gives me a _self link but nothing more. Maybe that's all the HAL is supposed to give for a single entity and for collections it adds more. I don't know, still at the learning level.

Anyway, I still think the point is valid, I don't see where the domain entity class is needed for ResourceAssembler.

**Comment by gregturn** [comment]
If your domain object was `Employee`, there are three paths you can go down. 

* You can make `class Employee extends ResourceSupport`. In this scenario, yeah, the assembler doesn't make sense because your object already has link knowledge. No assembly needed.
* You can have an `Employee` class and an `EmployeeResource extends ResourceSupport` class, whereby you may want to concentrate your link building rules into an assembler.
* You can have an `Employee` class and leverage Spring HATEOAS's out-of-the-box `Resource<?>` container. (I tend to favor this one).

Assuming you used the third option, you can easily define a `ResourceAssembler` like this:

```
class EmployeeResourceAssembler implements ResourceAssembler<Employee, Resource<Employee>> {

    Resource<Employee> toResource(Employee e) {
         return new Resource(e,
            // put all your links here
            linkTo(methodOn(EmployeeController.class).findOne(e.getId())).selfLink(),
            // ... more links ..
         );
    }
}
```
. Naturally, you can use the same approach for `Employee`/`EmployeeResource` as well

If you declare a `@Bean` of this type in a `@Configuration` class, then you can inject this assembler into the related `EmployeeController`, and use it to transform fetched objects into their corresponding resources.

```
@RestController
class EmployeeController {

    private EmployeeRepository repository;
    private EmployeeResourceAssembler assembler; // initialize via constructor

    @GetMapping("/employees/{id}")
    Resource<Employee> findOne(@PathVariable String id) {
        return assembler.toResource(repository.findOne(id));
    }
}
```

**Comment by gregturn** [comment]
I've tried to capture several scenarios here => https://github.com/spring-projects/spring-hateoas-examples

There are gaps, and it uses Spring HATEOAS 1.0.0.BUILD-SNAPSHOT to get some of the newer features, but hopefully it can help out.

**Comment by karlnicholas** [comment]
Hi Greg, Yes, this is more or less what I have done, what you show as option 3, _except_ for when the domain object doesn't exist because it is a composite of two or more actual domain objects. In that case, I have no domain object to use as the &lt;T&gt; type for implementing ResourceAssemblerSupport<T,D extends ResourceSupport>. So, I cannot call createResourceWithId because I don't have a domain object.

So, I guess from talking this out what I need is a "pseudo" domain object that holds references to all the actual domain objects I need to construct the DTO. Yea, makes sense. 

I started with the examples as you reference, but the basic example uses SimpleIdentifiableResourceAssembler&lt;T&gt;. So, in addition to the same problem there is no SimpleIdentifiableResourceAssembler in the spring hateoas project at the moment. Anyway, no problem there, I assume I can use the ResourceAssemblerSupport in it's place.

So, let's I vote lets close this issue and I'll work with a composite pseudo domain object. I suppose I was hoping not to need one but never mind that.

Thanks.

**Comment by gregturn** [comment]
:)
