### ISSUE TITLE
When @EnableHypermediaSupport is active with HAL support, former Jackson customizations get lost

### ISSUE THREAD

**Issue by laszlocsontos** [spring-projects/spring-hateoas#705]
Hey Guys,

I think I spot a bug in `HypermediaSupportBeanDefinitionRegistrar` while it's configuring Jackson for supporting HAL.

What do you think, how could this be at least worked around?

Thanks!

Cheers,
László

*************

**Use case**

I'd like to use `java.util.Optional` (and also `java.time.LocalDateTime`) in DTO classes, so that they get serialized properly. For example, in case of an `Optional` field containing the value `"test"`, it should be serailized as `{"field":"test"}` instead of `{"field":{"present":true}}`.

**Environment**

*Spring Boot: * 2.0.0.RELEASE
*Spring HATEOAS:* 0.24.0.RELEASE
*Spring Web:* 5.0.4.RELEASE

**Steps to reproduce**

1) `@EnableHypermediaSupport(type = HAL)`
2) Try to use any functionality provided by Jackson modules (eg. `Jdk8Module` or `JavaTimeModule`)

*Expected behaviour*: HAL infrastructure re-uses that `ObjectMapper` which was pre-initialized either with `JacksonAutoConfiguration` or manually created.

*Actual behaviour*: A custom `ObjectMapper` created by `HypermediaSupportBeanDefinitionRegistrar` is used instead.

**Analyses**

For the aforementioned use case, `Jackson2ObjectMapperBuilder` registers `com.fasterxml.jackson.datatype.jdk8.Jdk8Module`, because it's on the class path for Spring Boot apps by default.

However, when `@EnableHypermediaSupport` is active with `HAL` support, former `Jackson` customizations get lost.

This happens, because `HypermediaSupportBeanDefinitionRegistrar.Jackson2ModuleRegisteringBeanPostProcessor` seems to run earilier than MVC auto-configuration could fully complete initalization.

In method `potentiallyRegisterModule()`, such a `MappingJackson2HttpMessageConverter` which would contain an `ObjectMapper` in a way that it's configured for HAL is never going to be found.

Even if `Jackson2ObjectMapperBuilderCustomizer` is used and `Jackson2HalModule` is installed manually, that change cannot be seen at that time when method `potentiallyRegisterModule()` inspects HTTP message converters.

**Example code**

```
import static org.springframework.hateoas.config.EnableHypermediaSupport.HypermediaType.HAL;

import java.util.Optional;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.hateoas.ResourceSupport;
import org.springframework.hateoas.config.EnableHypermediaSupport;
import org.springframework.hateoas.mvc.ControllerLinkBuilder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@EnableHypermediaSupport(type = HAL)
public class CustomizeJacksonWithHalApplication {

    public static void main(String[] args) {
        SpringApplication.run(CustomizeJacksonWithHalApplication.class, args);
    }

}

@RestController
class Controller {

    @GetMapping
    Response getResponse() {
        Response response = new Response(Optional.of("test"));
        response.add(ControllerLinkBuilder.linkTo(Controller.class).withSelfRel());
        return response;
    }

}

@Data
@NoArgsConstructor
@AllArgsConstructor
class Response extends ResourceSupport {

    Optional<String> field;

}
```

**Comment by gregturn** [comment]
Simply put, if you use `@EnableHypermediaSupport`, then all of Boot's autoconfigured behavior for Spring HATEOAS is disabled.

**Comment by laszlocsontos** [comment]
Yes, correct.

**Comment by gregturn** [comment]
Got a sample app I could poke at?

**Comment by laszlocsontos** [comment]
Sure, here you are. https://github.com/springuni/spring-issues/tree/master/spring-hateoas-705

**Comment by laszlocsontos** [comment]
I was wondering, wouldn't it be simpler to use the standard `WebMvcConfigurer` to register that extra `TypeConstrainedMappingJackson2HttpMessageConverter` Spring HATEOAS needs for HAL?

**Comment by hennejg** [comment]
I can confirm this issue which has caused me quite some grief. Spring-Hateoas seems to configure its own `ObjectMapper` which is registered in `org.springframework.hateoas.config.HypermediaSupportBeanDefinitionRegistrar.registerBeanDefinitions(AnnotationMetadata, BeanDefinitionRegistry)` and set as the mapper to be used by the `TypeConstrainedMappingJackson2HttpMessageConverter` mentioned by @laszlocsontos  above in `org.springframework.hateoas.config.HypermediaSupportBeanDefinitionRegistrar.Jackson2ModuleRegisteringBeanPostProcessor.potentiallyRegisterModule(List<HttpMessageConverter<?>>)`.

My Workaround consists of a `BeanPostProcessor` which applies my modifications to the HAL ObjectMapper like this: 
```@Component
public class SpringHateoasIssue705WorkAround implements BeanPostProcessor {
  @Autowired
  MyJacksonModule m1;
  
  @Override
  public Object postProcessAfterInitialization(final Object bean, final String beanName) throws BeansException {

    if (!"_halObjectMapper".equals(beanName)) {
      return bean;
    }

    ObjectMapper mapper = (ObjectMapper) bean;
    mapper.registerModule(m1);
    mapper.setAnnotationIntrospector(new AnnotationIntrospectorPair(new JacksonAnnotationIntrospector(),
        new JaxbAnnotationIntrospector(TypeFactory.defaultInstance())));
    mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

    return mapper;
  }

  @Override
  public Object postProcessBeforeInitialization(final Object bean, final String beanName) throws BeansException {
    return bean;
  }
}
```

Please note that the Jackson-Module `MyJacksonModule` would otherwise have been picked up and used automatically by the standard Jackson support in Spring-Boot.

**Comment by laszlocsontos** [comment]
Thanks @hennejg for the workaround, I'll also give that a try.

**Comment by vlaurin** [comment]
With the release `0.25.0.RELEASE`, it seems this workaround is not needed anymore. Instead, if an instance of `ObjectMapper` is already defined it's going to be injected and copied before being configured for HAL, so existing configuration is preserved.

See:
* https://github.com/spring-projects/spring-hateoas/blob/0.25.0.RELEASE/src/main/java/org/springframework/hateoas/config/ConverterRegisteringWebMvcConfigurer.java#L99
* https://github.com/spring-projects/spring-hateoas/blob/0.25.0.RELEASE/src/main/java/org/springframework/hateoas/config/ConverterRegisteringWebMvcConfigurer.java#L127

**Comment by gregturn** [comment]
That is true.

As of https://github.com/spring-projects/spring-hateoas/commit/80d13ed80e283bb06ce30873c2acbdef9c9a6ae7, an `ObjectMapper` found in the app context is pulled into Spring HATEOAS where it can be cloned and then have HAL (or whatever mediatypes are enabled) registered.
