### ISSUE TITLE
Extend Link

### ISSUE THREAD

**Issue by jam01** [spring-projects/spring-hateoas#716]
Hello, I've been experimenting with different link serializations and wanted to extend the Link class to include a couple more fields, I've extended the class and overloaded some constructors but the new fields are not serialized. 

I'm guessing somewhere in between the mixins they are ignored but I can't quite figure out where or how to prevent that. Some advise would be appreciated, thank you!

**Comment by gregturn** [comment]
See this => https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/hal/LinkMixin.java

Find out where it's used.

FYI: This is something better suited for stackoverflow.com, not our issue management system.
