### ISSUE TITLE
Links generated on WebFlux/Reactor are sometimes relative and sometimes absolute

### ISSUE THREAD

**Issue by ivansenic** [spring-projects/spring-hateoas#726]
We have a simple web application build with WebFlux/Reactor. We noticed that using generation like `linkTo(methodOn(..`, some links are generated as relative links and some as absolute. This seemed weird to us.

With a little bit of debugging, we concluded that the reason for this is most likely the `ControllerLinkBuilder.getBuilder()` method that uses `RequestContextHolder` to read the current request context. If request attributes are null, the links will be relative (see below):

```
if (RequestContextHolder.getRequestAttributes() == null) {
	return UriComponentsBuilder.fromPath("/");
}
```

However, `RequestContextHolder` stores the attributes in the `ThreadLocal`. So usually requests that call other backends or go to the database, end up with relative links. The one that can "return immediately", like with using `Mono.just(someData)`, always have absolute links. My impression is that request context is most likely not propagated correctly on the reactive stream when one switches between the threads. 

Can this be the case, is there something we missed? Any idea how can this be fixed. Is there anything we should add to the reactive context, is there any support for this?

**Comment by gregturn** [comment]
At this point in time, Spring HATEOAS has no support for Spring WebFlux. Given Reactor's usage of work stealing tactics, we cannot guarantee having the servlet context on hand, thus generating this side effect.

To embrace WebFlux would actually require a lot of more tricky stuff like using Jackson in a non-blocking fashion. This is under evaluation but not development as this point in time.
