### ISSUE TITLE
Add Spring WebFlux support

### ISSUE THREAD

**Issue by daggerok** [spring-projects/spring-hateoas#728]
Hello,

Are there any options for spring-webflux functional routes?

---
Regards,
Maksim

**Comment by gregturn** [comment]
There is no WebFlux support at this point in time.

**Comment by daggerok** [comment]
And it's sad, at the moment I have to do some ugly weird stuff like that:

```kotlin
  @Bean
  fun routes() = router {
    "/".nest {
      // ...
      GET("/**") {
        val url = it.uri().toURL()
        val port = if (url.port == -1) 80 else url.port
        val baseURL = "${url.protocol}://${url.host}:$port"
        ok().body(Mono.just(mapOf(
            "_links" to mapOf(
                "search" to mapOf(
                    "href" to "$baseURL/api/search?query={searchQuery}",
                    "templated" to true
                ),
                "details" to mapOf(
                    "href" to "$baseURL/api/details/{userId}",
                    "templated" to true
                ),
                "_self" to mapOf(
                    "href" to url.toString(),
                    "templated" to false
                )
            )
        )))
      }
    }
  }
```

**Comment by gregturn** [comment]
During S1P back in September, plans were formed to add WebFlux support to Spring HATEOAS. We haven't gotten underway with implementing, though. There was a stack of other stuff in the works that we are fervently hammering on.

Stay tuned!

**Comment by gregturn** [comment]
WebFlux support is now under review.

**Comment by odrotbohm** [comment]
This is now in place with `WebFluxLinkBuilder` API providing a reactive builder for calls to `linkTo(…)`. Feel free to give the latest snapshots a try. Feedback highly appreciated!

**Comment by daggerok** [comment]
Hey, @odrotbohm!
Awesome! Thanks! I will try, for sure

**Comment by RouxAntoine** [comment]
Really big thanks 😃

**Comment by daggerok** [comment]
Hello,

@odrotbohm, or maybe someone else, guys do you have some examples maybe how I can use 
`WebFluxLinkBuilder`? Is it required Spring MVC styled Resources?
wasn't able to find anything here: https://docs.spring.io/spring-hateoas/docs/1.0.0.BUILD-SNAPSHOT/reference/html/
Thanks in advice

---
Regards,
Max

**Comment by odrotbohm** [comment]
It's all in quite a flux (pun intended) right now. The most practical place to look at right now is the [sample controller](https://github.com/spring-projects/spring-hateoas/blob/a89e57eed7e12819b87be7f1b977dddfd432541d/src/test/java/org/springframework/hateoas/support/WebFluxEmployeeController.java#L101-L106) we use in the test cases. Updating the docs is high priority, but I'm not sure we're gonna get it done in time before 1.0 M1.

**Comment by daggerok** [comment]
Thanks a lot!

**Comment by jakubriegel** [comment]
@odrotbohm any news at docs for hateoas with WebFlux?
