### ISSUE TITLE
TypeConstrainedMappingJackson2HttpMessageConverter overrides custom HttpMessageConverter

### ISSUE THREAD

**Issue by rsamant14** [spring-projects/spring-hateoas#734]
I have a custom message convertor that is supposed to convert the following class (EntityResponse ) to application/json

controller returns=> class **EntityResponse extends ResourceSupport**
@produces=>application/json

custom message converter=> 

```java
class EntityResponseJsonMessageConverter<T extends ResourceSupport>
                                 extends AbstractHttpMessageConverter<T>{
    @Override
    public boolean supports(Class<?> clazz) {
        return EntityResponse.class.equals(clazz);
    }
}
```

Unfortunately before my message converter can kick in TypeConstrainedMappingJackson2HttpMessageConverter kicks in

I need EntityResponseJsonMessageConverter to convert any EntityReponse to json, and all other resourcesupport classes to be handled by the default TypeConstrainedMappingJackson2HttpMessageConverter

Can i change the order of the message converters (have my custom message convertor execute before    
  TypeConstrainedMappingJackson2HttpMessageConverter). How do i set the priority on a message converter (TypeConstrainedMappingJackson2HttpMessageConverter). I am using spring boot.

Appreciate the help.

Thank you

**Comment by gregturn** [comment]
Superseded by https://github.com/spring-projects/spring-hateoas/issues/833
