### ISSUE TITLE
@EnableHypermediaSupport triggers Spring Beans Problem in Eclipse STS

### ISSUE THREAD

**Issue by hdohlmann** [spring-projects/spring-hateoas#735]
spring-haetoas-0.25.0-RELEASE (from Spring Boot 2.0.4).
Eclipse STS 3.9.5

@Configuration class with @EnableHypermediaSupport(type = HypermediaType.HAL) annotation.

Upgrading from Spring Boot 2.0.3 to 2.0.4 triggers the following "Spring Beans Problem" error in Eclipse STS:
No constructor with 0 arguments defined in class 'org.springframework.hateoas.config.ConverterRegisteringWebMvcConfigurer'

**Comment by hdohlmann** [comment]
Even worse: My Feign clients no longer deserialize data?
If I enable full debug-logging for the Feign clients, i can see data is received...

**Comment by gregturn** [comment]
What happens if you run your app from the command line using the build system?

**Comment by hdohlmann** [comment]
Same problem with the Feign clients no longer deserializing data.
I have the following annotations on a configuration class:
```
@Configuration
@EnableFeignClients
@EnableDiscoveryClient
@EnableHypermediaSupport(type = HypermediaType.HAL)
```
One of my FeignClients looks like this:
```
@FeignClient(name = "http://somewhere", fallbackFactory = FeignClientFallback.class)
public interface FeignClient {

    @GetMapping("/somewhere/search/custom?country={country}&number={number}")
    ResponseEntity<Resources<Resource<Exclusion>>> get(
        @PathVariable("country") String country,
        @PathVariable("number") String number,
        @RequestHeader Map<String, String> headers);

    @Slf4j
    @Component
    public static class FeignClientFallback implements FallbackFactory<FeignClient> {

        @Override
        public FeignClient create(Throwable cause) {
            return (cc, number, headers) -> {
                log.error("Fallback! Could not fetch somewhere", cause);
                return new ResponseEntity<>(new Resources<>(Collections.emptyList()), HttpStatus.FAILED_DEPENDENCY);
            };
        }

    }

}
```
I enable full debug for the FeignClient with the below, and can see that data IS received. It is just not parsed.
```
feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    my.FeignClient: DEBUG
```

Anything looks weird here?

**Comment by gregturn** [comment]
Spring HATEOAS switched from creating a HAL objectmapper to using one injected into the app context.

**Comment by hdohlmann** [comment]
Yes, thanks :-)
So what do I need to add, besides what I already have, to make my code work again?

**Comment by hdohlmann** [comment]
Using STS 4, the warning in Eclipse is gone.
Unfortunately, I still do not get any data deserialized.
This looks a little like https://stackoverflow.com/questions/38361756/feign-client-in-non-web-environment-to-a-repostoryrestresource-with-hal-is-n.
Can you hint at what beans I need to add to my configuration to enable the deserialization?

**Comment by hdohlmann** [comment]
If anyone else stumbles in here, the solution is to add this bean to a @Configuration annotated class:
```
@Bean
public Module halModule() {
	// Need this so the Feign Client can deserialize the data
	return new Jackson2HalModule();
}
```

This issue can be closed :-)
