### ISSUE TITLE
Disabling templated links

### ISSUE THREAD

**Issue by vruum** [spring-projects/spring-hateoas#736]
I know this is also mentioned in https://github.com/spring-projects/spring-hateoas/issues/543 and https://github.com/spring-projects/spring-hateoas/issues/535 but we're trying to upgrade from a version of spring hateoas version pre templated links. and per https://github.com/spring-projects/spring-hateoas/issues/535 we should be able to just call expand() on the link and get the links without parameters, but this causes an error 
```
Illegal character in path at index 78: http://localhost:6789/v1/tenants/c57bc29a-2d99-43d2-8b6a-db5b0c65ac26/printers{?os,all,embed,network,match,matchVendorModel,apply-group-filter,createdFrom,createdTo,queuesFrom,queuesTo,printerId,apiVersion}

```
this is the controller method signature:

```

@RequestMapping(value = APIV1Defines.TENANT_PRINTER_BASE_PATH, method = GET, params="!page")
    public CacheableResponse getPrinters(
			@PathVariable("tenant") UUID tenantId,
			@RequestParam(value = "os", required = false) OperatingSystem os,
			@RequestParam(value = "all", defaultValue = "false", required=false) Boolean all,
			@RequestParam(value = "embed", required = false) List<String> embed,
			@RequestParam(value = "network", required = false) List<UUID> networks,
			@RequestParam(value = "global",  defaultValue = "false") Boolean global,
			@RequestParam(value = "match", required = false) String match,
			@RequestParam(value = "matchVendorModel", required = false) String matchVendorModel,
			@RequestParam(value = "apply-group-filter", required = false, defaultValue = "false") Boolean filterByGroups,
			@RequestParam(value = "createdFrom", required = false) Instant createdFrom,
			@RequestParam(value = "createdTo", required = false) Instant createdTo,
			@RequestParam(value = "queuesFrom", required = false) Integer queuesFrom,
			@RequestParam(value = "queuesTo", required = false) Integer queuesTo,
			@RequestParam(value = "printerId", required = false) UUID printerId,
			@RequestParam(value = "apiVersion", required = false) Integer apiVersion)

```

and this is the  where we add the link (inside the resource constructor) 

```
add(linkTo(methodOn(PrinterController.class).getPrinters(tenantUuid, null, null, null, null,null,  null, null,  null, null, null, null,  null, null, null)).withRel("printers")
				.expand());
```

Is this way of disabling templated links no longer supported?

**Comment by olivergierke** [comment]
This should work. Would you mind adding the complete stack trace? And the code that's producing the error?

I quickly tried this and the test is green.

```java
@Test
public void testname() {

	Link link = new Link("http://localhost:6789/foobar{?os}", "foo");

	assertThat(link.expand().getHref(), is("http://localhost:6789/foobar"));
}
```

**Comment by vruum** [comment]
Hi Oliver,

**Comment by gregturn** [comment]
What version of Java are you using?

**Comment by vruum** [comment]
Java 10

**Comment by gregturn** [comment]
Can you test against java 8 and see if the same issue arise?

**Comment by vruum** [comment]
I really wish there was an easy way to do this. but unfortunately this project has a way too intricate web of dependencies, and a lot of those using java 10 stuff (var etc.)

Do you have a suspicion that the java version might be the cause?

**Comment by gregturn** [comment]
Turns out, the problem is `apply-group-filter`. This breaks the regex pattern inside `UriTemplate`. I'll have to go re-read the spec on URI Templates to see if this is a valid query parameter. If so, we need to fix `UriTemplate`.

```java
private static final Pattern VARIABLE_REGEX = Pattern.compile("\\{([\\?\\&#/]?)([\\w\\,]+)\\}");
```

**Comment by gregturn** [comment]
Per [RFC 6570](https://tools.ietf.org/html/rfc6570#section-2.3), the grammar rules for variable names is shown below:

```
     variable-list =  varspec *( "," varspec )
     varspec       =  varname [ modifier-level4 ]
     varname       =  varchar *( ["."] varchar )
     varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```

...unreserved characters are NOT listed as a valid `varchar`. Hence, `apply-group-filter` is not a valid variable name per this spec.

The spec refers to "unreserved" values (including "-") to be copied into the final URI as values, but not as variable names.

**Comment by vruum** [comment]
@gregturn , thank you, that's excactly what it was. It's working perfectly now. 

Thankl you for your time, both of you. And you can go ahead and close this issue.

**Comment by olivergierke** [comment]
Lovely, Greg. Thanks for getting on top of this!
