### ISSUE TITLE
RelProvider API should use proper extension relation 

### ISSUE THREAD

**Issue by dschulten** [spring-projects/spring-hateoas#77]
The Web Linking RFC http://tools.ietf.org/html/rfc5988#section-4.2 requires that extension relation types (the custom ones not registered with IANA) should be URIs which may be expressed by curies. Only registered rels may be simple strings.
I.e. we should have some way to specify a base URI which can be prepended to the RelProvider rel and a short curie form of that URI. 

If the base uri is http://www.example.com/rels and the curie form is ex, we could provide a rel http://example.com/rels/orders, or its curie form ex:orders

HAL also supports this kind of curies, they can be embedded  into the document, see http://haltalk.herokuapp.com/

The current automatic implementation of the RelProvider API is not fully compliant with the RFC.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/9eacd07203c244908eebfd4add2654894e0b5843.

You can see how to use the `CurieProvider` API as shown here => https://docs.spring.io/spring-hateoas/docs/1.0.0.M1/reference/html/#mediatypes.hal.curie-provider.
