### ISSUE TITLE
Rename UnitTest classes as ...UnitTests for consistency

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#777]
Since this project seeks to uphold Spring Data formatting, all the unit test classes should be `...UnitTests` instead of `...UnitTest`.

This will require tuning `maven-surefire-plugin`.

Original conversation: #591

**Comment by odrotbohm** [comment]
I'll rather tweak the one `…Tests` class to match `…Test` and avoid the additionally needed Surefire setup if went with `Tests`.
