### ISSUE TITLE
Transform IANA Link Relations into a series of constants

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#778]
Much like Spring has [HttpHeaders](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html) and all spec-defined HTTP header types captured as usable constants, it would make sense to do the same for IANA's listed Link Relation types.

https://www.iana.org/assignments/link-relations/link-relations.xhtml should be the basis, also including a link to each Link Relation's RFC spec definition.

**Comment by rolandKulcsar** [comment]
To solve this, I would suggest an enum e.g.:
```
public enum IanaRelations {

    ABOUT("about"),
    ALTERNATE("alternate"),
    APPENDIX("appendix"),
    ...

    private static final Set<String> RELS;

    private String value;

    static {
        RELS = Arrays.stream(IanaRelations.values())
                .map(rel -> rel.value)
                .collect(Collectors.toSet());
    }

    IanaRelations(String value) {
        this.value = value;
    }

    public static boolean isIanaRel(String rel) {
        return RELS.contains(rel);
    }
}
```
What do you think?

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/2e7eabdc1a37d9f7b32c16d3bbbd92c58dc96c30.
