### ISSUE TITLE
NoClassDefFoundError if @EnableHypermediaSupport is used without adding spring-plugin dependency

### ISSUE THREAD

**Issue by azagorneanu** [spring-projects/spring-hateoas#80]
I started to play with spring-hateoas (0.6.0.RELEASE) and found out that adding @EnableHypermediaSupport will cause a NoClassDefFoundError without explicitly adding spring-plugin as dependency:

```
java.lang.NoClassDefFoundError: org/springframework/plugin/core/support/PluginRegistryFactoryBean
        at org.springframework.hateoas.config.LinkBuilderBeanDefinitionRegistrar.registerBeanDefinitions(LinkBuilderBeanDefinitionRegistrar.java:57)
        at org.springframework.hateoas.config.HypermediaSupportBeanDefinitionRegistrar.registerBeanDefinitions(HypermediaSupportBeanDefinitionRegistrar.java:86)
```

Also spring-hateoas (0.6.0.RELEASE)  depends on spring 3.1.4 and as result fails to process @Configuration classes without adding CGLIB as dependency:

```
java.lang.IllegalStateException: CGLIB is required to process @Configuration classes. Either add CGLIB to the classpath or remove the following @Configuration bean definitions: [springConfig, org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:352)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:246)
```

I was able to make it run without CGLIB by overriding spring dependencies to version 3.2.3.RELEASE.

**Comment by afaulconbridge** [comment]
Still a problem with 0.19.0.RELEASE. Though at least now this issue is the to result in Google for the error message!

**Comment by kpb** [comment]
I had the same issue today - wasted at least an hour tracking this down. Should at least be some mention of this in the docs.

**Comment by jndietz** [comment]
This is still an outstanding issue... would be easily solved by including `spring-plugin-core` in the hateoas stuff.

**Comment by ghilainm** [comment]
@azagorneanu  Why is this issue closed? Did you documented this or changed the code?

**Comment by gregturn** [comment]
It was closed six years ago.

But to answer the bigger question, Spring Plugin was made a full dependency via #760 in version 1.0. We decided the scenarios of using Spring HATEOAS without the feature warranting Spring Plugin weren't sufficient grounds.

**Comment by gregturn** [comment]
Superceded by https://github.com/spring-projects/spring-hateoas/commit/1731b49bc6c0a63d8e63a9576efdf49add1da648.

**Comment by kpb** [comment]
> It was closed six years ago.

But is it documented?

**Comment by gregturn** [comment]
It what documented? 

The original issue was to handle the cryptic error message of someone activating a piece of Spring HATEOAS without including Spring Plugin.

Since Spring Plugin will be ALWAYS brought in, the risk has been eliminated. Nothing to document.
