### ISSUE TITLE
Remove package cycle between ….hateoas and ….hateoas.core

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-hateoas#806]
IntelliJ reports package cycles when creating the dependency matrix for the project (excluding tests).

We should remove the package cycles and add a test that prevents them to happen again.

**Comment by odrotbohm** [comment]
It looks like it's `….hateoas.Affordance` pointing to `….hateoas.core.AffordanceModelFactory`. The latter needs to be moved to the root package.
