### ISSUE TITLE
ControllerLinkBuilder.methodOn surfaces checked exceptions and requires try/catch.

### ISSUE THREAD

**Issue by kmbulebu** [spring-projects/spring-hateoas#82]
If my controller method has a checked exception, for example,  MyController.doSomething() throws MyCheckedException, then referencing that method using ControllerLinkBuilder.methodOn() also exposes that exception.

As a consequence, in my ResourceAssembler class, I'd have to wrap this line in a try block:
resource.add(linkTo(methodOn(MyController.class).doSomething(2L)).withRel("relationship"))

That seems like a useless try/catch block.

As an alternative, I could use unchecked (RuntimeException), but IMHO I don't think they're appropriate for this code. I'd like developers to explicitly handle these events.

Am I looking at this wrong, or am I on to something?

**Comment by gregturn** [comment]
Issue appears fundamental to building links around controller methods that throw checked exceptions.
