### ISSUE TITLE
Make HalFormsConfiguration match HalConfiguration in features

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#832]
Related issue: #811.

**Comment by odrotbohm** [comment]
I don't see anything HAL Forms specific in the configuration class currently. Shall we let the HAL Forms infrastructure simply pick up a `HalConfiguration` instance for now and remove the `HalFormConfiguration`?

**Comment by gregturn** [comment]
I ponder that. I was uncertain if anything related to #619 and our plans to add JSR-303 support to template-based media types.

**Comment by gregturn** [comment]
On a more fundamental level, while I realize this is easier for us to implement, doesn’t it seem awkward to ask users to “mix” media type stuff like this?

In the spec, Mike has stated:

> The HAL-FORMS media type design follows many of the HAL media type conventions. For this reason, HAL-FORMS "looks like HAL." However, it is important to keep in mind that HAL-FORMS is not the same as HAL — the two should not be thought of as interchangeable in any way.

I’m in favor of under the hood reusing stuff if it makes sense, but the public facing API for configuring HalForms seems to me better fitted with a HalFormsConfiguration. 

Care to weigh in @toedter or @vpavic?

**Comment by toedter** [comment]
Actually I don't want mix media types, but would appreciate an easy way to "upgrade" from HAL to HAL-FORMS, without loosing any structure I had configured in HAL.

I agree with Mike's statement, but at least in terms of structuring capabilities related to `_links` and `_embedded`, they should be compatible and the provided Spring HATEOAS APIs should provide the same capabilities. The use case here is: a team is fine with HAL and designs representation models fitting the business cases. Now the team wants to evolve the API and starts using affordances with a HAL-FORMS representation. From the API and rendering level it would be great if the backward-compatible part of HAL-FORMS is not affected when "upgrading" from HAL to HAL-FORMS.

I personally would prefer a seperate Config API for each media type, but in case of HAL and HAL-FORMS it would be great if the backward-compatible part of HAL-FORMS is also reflected in the config.

**Comment by vpavic** [comment]
> I’m in favor of under the hood reusing stuff if it makes sense, but the public facing API for configuring **HAL_FORMS** seems to me better fitted with a `HalFormsConfiguration`.

I agree with this and what @toedter expressed.

**Comment by odrotbohm** [comment]
I've changed that to the following:

- We have an empty `HalFormsConfiguration` class that doesn't contain anything to configure for now. It can be instantiated with a `HalConfiguration` as delegate but will use a default instance of `HalConfiguration` if the default constructor is used. That allows the creation and declaration of `HalFormsConfiguration` and explicit control over whether existing or new `HalConfiguration` is used.
- The automatic configuration will try to find a `HalFormsConfiguration` in the application context. If found, it will use that. If not, it will look for a `HalConfiguration` instance and use that as delegate for the default `HalFormsConfiguration` to be created. If no `HalConfiguration` can be found, we will use a default instance.

This gives users fine-grained control over the configuration for each media type but also allows the transparent pickup of HAL configuration in HAL FORMS.
