### ISSUE TITLE
Reference documentation mentions inexistant "createResource" method in class "ResourceAssemblerSupport"

### ISSUE THREAD

**Issue by Aldian-fr** [spring-projects/spring-hateoas#836]
I am referring to this paragraph: https://docs.spring.io/spring-hateoas/docs/0.25.1.RELEASE/reference/html/#fundamentals.resource-assembler

As mentioned in title, it mentions an inexistant `createResource(T entity)` method in class `ResourceAssemblerSupport`

The problem seems to be kinda related to issue https://github.com/spring-projects/spring-hateoas/issues/153

Note that it would seem that method `createResourceWithId(Object id, T entity)` from same class would seem to be a good replacement, but when looking to the implementation it is really weird:

1. It forces entity not to be null with `Assert.notNull`
2. Then it calls `instantiateResource(entity)`
3. Which executes `return BeanUtils.instantiateClass(resourceType)`
4. ...Making me saying that the `T entity` parameter is never used at all and could simply be removed (or am I missing something?)

I assume it has been left for backward compatibility, but it is very misleading when trying to understand what the code does

**Comment by gregturn** [comment]
I revised the docs to clearly indicate this is user code you write yourself when converting a `Person` to a `PersonModel` object (before adding links).
