### ISSUE TITLE
Remove Identifiable

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-hateoas#842]
`Identifiable` really doesn't naturally fit into the API anymore as its move to `Optional` has made obvious that the optionality really gets in the way of link creation etc. Also, with the rename of `ResourceSupport` to `RepresentationModel`, the idea of a model being identifiable feels rather weird as well.

**Comment by odrotbohm** [comment]
Oh, the usage of `Identifiable`s in code paths currently supporting it seems to be broken anyway as they now handle an `Optional` instead of an object which is unlikely to create the expected results. 😬

**Comment by gregturn** [comment]
The only place `Identifiable` possibly made sense was mapping to a primary key in a database for the domain object. And that's a weak reason for an entire interface.

**Comment by atkawa7** [comment]
@odrotbohm @gregturn Just wondering I am trying to implement Json Api using the new custom types. However Json Api requires identifiable and resource name. Is there another way to get id and resource name from `RepresentationModel` or `EntityModel`
```
{
  "type": "ResourceType",
  "id": "ResourceId",
  "attributes": {
    .....
  },
  "links": {
    "self": "href"
  }
}
``` 

```java
public class EntityModel<T> extends RepresentationModel<EntityModel<T>> {

	private final T content;
```

**Comment by pallab123ban** [comment]
What is the equivalent of Identifiable?

**Comment by odrotbohm** [comment]
You'd manually unfold the entity into it's type and whatever constitutes its. `EntityLinks` now exposes a `….forType(Function<T, ?>)` that effectively takes an extractor function and returns a `TypedEntityLinks` that will automatically apply the given extractor if you hand instances of a certain type:

```java
TypedEntityLinks<Order> links = entityLinks.forType(Order::getId);
links.linkToItemResource(order) // <- will call getId() on the order to extract the identifier
```

For more details, please consult the [reference documentation](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#server.entity-links.api.typed).

**Comment by beardy247** [comment]
Removing this has caused me a fair bit of pain. Other than this GitHub issue it isn't documented (that I could find) and isn't mentioned at all in the migration guide. The removal of the slash(Identifiable<?> identifiable) method from LinkBuilder caused my code to fall back to the slash(Object object) method which then produced bad links without throwing any errors. Luckily my tests saved the day.
Might be worth adding it to the migration guide to save others the trouble of having to figure this out for themselves.

**Comment by mhlmhlmhlmhl** [comment]
I have the same problem.  Just another part of the HATEOAS migration horror story.
