### ISSUE TITLE
Release 1.0 M1

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-hateoas#853]

**Comment by atkawa7** [comment]
@odrotbohm @gregturn  Will new media types be included in this milestone

**Comment by odrotbohm** [comment]
Yes. Plus an open SPI to register custom ones.

**Comment by atkawa7** [comment]
@odrotbohm  Great

**Comment by atkawa7** [comment]
@odrotbohm On a side note I have a new library https://github.com/atkawa7/httpsnippet which is port of the nodejs version https://github.com/Kong/httpsnippet. This library can be used for generating code snippets for  springfox. Do you know how it  can be added to **This Week in Spring**

**Comment by gregturn** [comment]
Contact @starbuxman on twitter for TWIS.

**Comment by atkawa7** [comment]
Thanks @gregturn
