### ISSUE TITLE
Public endpoints for testing

### ISSUE THREAD

**Issue by evert** [spring-projects/spring-hateoas#858]
Hi! I hope this is not an inappropriate question for Github.

I'm working on a [generic hateoas client](https://github.com/evert/ketting), and I would like to make sure it has really good Spring support. Are you aware of any public endpoints that I could use to test it?

**Comment by gregturn** [comment]
Any time I've built a guide up against some public endpoint, the endpoint ultimately dies. So, no, I don't know of any endpoints for any specific forms of hypermedia.

Hence, my suggestion that you build your own for test purposes.

**Comment by evert** [comment]
Makes sense, thank you!
