### ISSUE TITLE
Create a dedicated builder for HAL representations

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#864]
@drdamour I'm experimenting on a fluent API to build `RepresentationModel` objects. What do you think of something like this for building an embedded structure like you depicted up above?

```java
@RestController
static class ProductController {

	LinkRelation favoriteProducts = LinkRelation.of("favorite products");
	LinkRelation purchasedProducts = LinkRelation.of("purchased products");

	@GetMapping("/products")
	public RepresentationModel<?> all() {

		EmbeddedModelBuilder builder = ModelBuilder //
				.embed() //
				.rootLink(linkTo(methodOn(ProductController.class).all()).withSelfRel());

		PRODUCTS.keySet().stream() //
				.map(id -> new EntityModel<>(PRODUCTS.get(id), new Link("http://localhost/products/{id}").expand(id))) //
				.forEach(productEntityModel -> {

					if (productEntityModel.getContent().isFavorite()) {

						builder //
								.embed(favoriteProducts) //
								.entityModel(productEntityModel) //
								.rootLink(productEntityModel.getRequiredLink(SELF).withRel(favoriteProducts));
					}

					if (productEntityModel.getContent().isPurchased()) {

						builder //
								.embed(purchasedProducts) //
								.entityModel(productEntityModel) //
								.rootLink(productEntityModel.getRequiredLink(SELF).withRel(purchasedProducts));
					}
				});

		return builder.build();
	}
}
```

It yields:

```json
{
  "_embedded" : {
    "favorite products" : [ {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/777"
        }
      }
    }, {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/998"
        }
      }
    } ],
    "purchased products" : [ {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/111"
        }
      }
    }, {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/222"
        }
      }
    }, {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/333"
        }
      }
    }, {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/444"
        }
      }
    }, {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/555"
        }
      }
    }, {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/666"
        }
      }
    }, {
      "someProductProperty" : "someValue",
      "_links" : {
        "self" : {
          "href" : "http://localhost/products/998"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost/products"
    },
    "purchased products" : [ {
      "href" : "http://localhost/products/111"
    }, {
      "href" : "http://localhost/products/222"
    }, {
      "href" : "http://localhost/products/333"
    }, {
      "href" : "http://localhost/products/444"
    }, {
      "href" : "http://localhost/products/555"
    }, {
      "href" : "http://localhost/products/666"
    }, {
      "href" : "http://localhost/products/998"
    } ],
    "favorite products" : [ {
      "href" : "http://localhost/products/777"
    }, {
      "href" : "http://localhost/products/998"
    } ]
  }
}
```

A plain old collection where the embedded link relation is a based on the domain type:

```java
@GetMapping("/authors")
RepresentationModel<?> collection() {

	return ModelBuilder //
			.collection() //

			.entity(new Author("Greg L. Turnquist", null, null)) //
			.link(linkTo(methodOn(EmbeddedController.class).authorDetails(1)).withSelfRel())
			.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //

			.entity(new Author("Craig Walls", null, null)) //
			.link(linkTo(methodOn(EmbeddedController.class).authorDetails(2)).withSelfRel())
			.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //

			.entity(new Author("Oliver Drotbhom", null, null)) //
			.link(linkTo(methodOn(EmbeddedController.class).authorDetails(2)).withSelfRel())
			.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //

			.rootLink(linkTo(methodOn(EmbeddedController.class).collection()).withSelfRel()) //

			.build();
}
```

produces

```json
{
  "_embedded" : {
    "authors" : [ {
      "name" : "Greg L. Turnquist",
      "_links" : {
        "self" : {
          "href" : "http://localhost/author/1"
        },
        "authors" : {
          "href" : "http://localhost/authors"
        }
      }
    }, {
      "name" : "Craig Walls",
      "_links" : {
        "self" : {
          "href" : "http://localhost/author/2"
        },
        "authors" : {
          "href" : "http://localhost/authors"
        }
      }
    }, {
      "name" : "Oliver Drotbhom",
      "_links" : {
        "self" : {
          "href" : "http://localhost/author/2"
        },
        "authors" : {
          "href" : "http://localhost/authors"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost/authors"
    }
  }
}
```

And a single item representation:

```java
@GetMapping("/other-author")
RepresentationModel<?> singleItem() {

	return ModelBuilder //
			.entity(new Author("Alan Watts", "January 6, 1915", "November 16, 1973")) //
			.link(new Link("/people/alan-watts")) //
			.build();
}
```

produces

```json
{
  "name" : "Alan Watts",
  "born" : "January 6, 1915",
  "died" : "November 16, 1973",
  "_links" : {
    "self" : {
      "href" : "/people/alan-watts"
    }
  }
}
```

Related issue: #175

**Comment by gregturn** [comment]
per @sam-kruglov (https://github.com/spring-projects/spring-hateoas/issues/270#issuecomment-472420848):

```java
@GetMapping("/author/{id}")
RepresentationModel<?> authorDetails(@PathVariable int id) {

	return ModelBuilder
                      //.root(someObj) possibility to add some fields to the root is missing?
			.embed(
                          LinkRelation.of("author"), // that could be a string
	                  entity(new Author("Alan Watts", "January 6, 1915", "November 16, 1973")), // that could be an Object without call to entity(..)
			  link(new Link("/people/alan-watts")) // this is varargs as it is optional. also could be a Link without calls to link(..)
                        )
			.embed(
                          LinkRelation.of("illustrator")), 
			  entity(new Author("John Smith", null, null)), 
			  link(new Link("/people/john-smith")) 
                        )
			.link(new Link("/books/the-way-of-zen")) 
			.link(new Link("/people/alan-watts", LinkRelation.of("author"))) 
			.link(new Link("/people/john-smith", LinkRelation.of("illustrator"))) 
			.build();
}
```

**Comment by gregturn** [comment]
per @drdamour (https://github.com/spring-projects/spring-hateoas/issues/175#issuecomment-471800473)

overall it seems fine.  some comments pulling from how i've used resources:
* i've learned from past mistakes to avoid nested embeds when possible, but does rootLink go all the way to the root, or the immediate parent...you'll probably want both.  i'd be looking for .parent() and .root() more than rootLink() or parentLink()..especailly that self case on the collection, rootLink is weird there cause wy would i add a self to the root in the context of a subresource except in the case of a literal construction...in which case i'd much rather call link(new SelfLink()) before calling .collection()
* I think of it as a special case of HAL that things are embedded with rel only.  There was a poster on hal forums who asked why we don't embed by url, something that is better for compatibility with http2 and uri templates (you could embed common template completions) that i thought was pretty smart.   fundamentally a sub resource can only be embedded by way of some hypermedia control, a link being the easiest by far, but templated links not far behind.  Maybe it goes against a pattern of builders to have two params, but to me, i must embed a sub resource with a link together in pairs. so i'd have embed take two params, the entity and the link to embed it with (which in hal ONLY cares about the rel...but in others may care about urls or even more).  But i get how that could be a pretty abstract concept, and if someone just wants to build HAL they'd question why they have to have a whole link with href just to output a rel string in the serialization.
* rel's distancing themselves from order has always been weird to me...i get that item doesn't imply order, but is the order those rels appear in the document important? i've always thought so..and in practice it's necessary to work that way (cause order happens to matter to UIs/UX..a lot). As such, i'd be a bit concerned over the way the embed and root are added/removed in pairs in different methods to maintain order.  I'd want that to be less manual and prefer it to be more an option of the builder which would do the linking from self.  but even thinking of what to name that would be awful...  `ModelBuilder.generateLinksForRel("purchased").fromEmbeddedRel(REL_SELF).embed(thingWithSelfRel)`.  what do you do when you do that an the embedding thing has no self rel.  if embed took two params as prev suggested, then this would be much better.   `ModelBuilder.maintainLinksForEmbedded(true).embed(link, embeddedModel)`  or `ModelBuilder.maintainLinksForEmbedded(false).embed(embeddedModel.getLink(REL_SELF).withRel("purchased"), embeddedModel)`  former would keep the _links in hal, latter would ignore them.
* for the collection case, how do you set properties on the collection?  I guess you start with entity() but then how do you get back to the entity?  `entity(e).collection().embed(sub1).embed(sub2).???`
* it's come up a few times where i want to embed an empty set.  `_embedded: { 'x': []}` This indicates to the client that yes i know you wanted this sub resource...but there just isn't any..vs straight up absence which sometimes implies it just couldn't be fulfilled but go ahead and ask for it via a link.  I've tried to get away form this pattern and instead have clients look for the links...but then they crash on NPEs...so i go back to making a service that is weird to help client devs that aren't safe.  I think you might need to support such a case...but maybe not necessary in a builder.  just a ramble about a useful anit-pattern.


that's my immediate feedback.

**Comment by gregturn** [comment]
per @odrotbohm (https://github.com/spring-projects/spring-hateoas/issues/270#issuecomment-472477734)

That still feels like quite a bit of duplication? What if we started with a `Link` and allow users to augment this with a preview?

```java
Link wattsLink = new Link("/people/alan-watts", LinkRelation.of("author"));
Link illustratorLink = new Link("/people/john-smith", LinkRelation.of("illustrator"));

ModelBuilder.entity(…)
  .andLink(wattsLink).withEmbed(new Author(…))
  .andLink(illustratorLink).withEmbed(new Author(…))
  .build();
```

That could still keep the `….embed(…)` methods around if you wanted to add embeds excplitly.

**Comment by gregturn** [comment]
My deep desire is for the API to flow like the HAL document itself, which is why I deliberately put `.embed()` first, followed by `.entity()` and `.link()`. It pushed me into the position of needing `.rootLink()` to discern top level links from lower level ones.

**Comment by odrotbohm** [comment]
That's the tricky bit. We will have to abstract from HAL a bit to make this also usable for other media types. Maybe a HAL specific subtype could add further constraints then.

**Comment by Sam-Kruglov** [comment]
@gregturn I think it should be reflecting the JSON, that is what we are essentially building. So that is why I suggest putting these inside `embed` because in my mind I put them inside `_embedded` section

**Comment by odrotbohm** [comment]
That's deceptive but be reminded that this is not a HAL specific API.

**Comment by Sam-Kruglov** [comment]
@odrotbohm regarding your example, your builder makes it so link is mandatory which it shouldn't be, at least for my use cases I didn't need them inside `_embedded` at all

**Comment by odrotbohm** [comment]
Not necessarily. As I explained, there could be other more general methods on it but *if* you're starting with "Here's a link with a given relation…", it's quite natural to be immediately able to state "Oh, btw. here's the preview for the resource that just mentioned link points to.".

**Comment by Sam-Kruglov** [comment]
@odrotbohm I see. So, in your example, `entity` represents root fields, `andLink` represent the `_links` section and you can add things to `_embedded` by continuing of building the `andLink` and you could even reuse the relation name there. That is pretty cool, although I am not sure if you even need to provide a link to something that is embedded already

**Comment by Sam-Kruglov** [comment]
@odrotbohm and about that being a non-HAL specific API, that would still make sense to put things inside `embed` rather than doing all of that at the root level of the builder since in some other format (not HAL), the embedded part would just be rendered differently but would still mean the same thing, that you are including some resources (like in JSON:API sparse fieldsets, they have `included`; don't know any other format that uses links though)

**Comment by gregturn** [comment]
I prototyped by trying to make things as flat as possible. It A) makes it easier to code a builder pattern and B) reduces the amount of "deep" reading you must undertake.

But I get the point of putting something inside another. It definitely self-groups things.

**Comment by Sam-Kruglov** [comment]
@gregturn it would actually make the user write less code, since you can omit some of the `entity`,`link`, `LinkRelation` (etc) calls by just including their arguments into the `embed`. I would place API user over API developer, IMHO. That of course doesn't make it bad,

**Comment by gregturn** [comment]
Agree on user over developer. 

So I seek maximum readability six months later.

**Comment by drdamour** [comment]
personally, i don't call it embedded....i use the terminology of a subresource in my resource model.  _embedded/embedded is a hal specific concept IMO

**Comment by toedter** [comment]
I like the idea having a builder that also supports the concept of sub resources. While I like @odrotbohm's idea of using this as a preview for a link relation, I would suggest also allowing sub resources bound to their parent resources directly and then contain optional links themselves.

In HAL it is very common to provide `_embedded` resources with a subset of attributes (like Projections in Data REST) that then provide a self link.

**Comment by gregturn** [comment]
I've created an alternative. This one:

* Uses "subModel" instead of "embed" since "embed" is very HAL-ish. (And subResource is very pre-1.0.0.RELEASE-ish)
* Uses an "enclosing" style. This is where `model` and `subModel(...)` contains the ENTIRE thing you're trying to put in there. 
* If you the "thing" you're embedding is not a `RepresentationModel` (yet), then you can use `entity()`, which simply wraps it into a one, and from there, you can apply links.
* This puts `link()` at the same level, and not based on current context. Hence, no need for `rootLink` like the other version.

A single-item model can be done like this:

```java
@GetMapping("/other-author")
RepresentationModel<?> singleItem() {

	return ModelBuilder2 //
			.entity(new Author("Alan Watts", "January 6, 1915", "November 16, 1973")) //
			.link(new Link("/people/alan-watts")) //
			.build();
}
```

With HAL, it will yield:

```
{
  "name" : "Alan Watts",
  "born" : "January 6, 1915",
  "died" : "November 16, 1973",
  "_links" : {
    "self" : {
      "href" : "/people/alan-watts"
    }
  }
}
```

You can do a collection a couple ways. Either this:

```java
return ModelBuilder2 //
		.entity(new Author("Greg L. Turnquist", null, null)) //
		.link(linkTo(methodOn(EmbeddedController.class).authorDetails(1)).withSelfRel()) //
		.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //
		.subModel( //
				ModelBuilder2 //
						.entity(new Author("Craig Walls", null, null)) //
						.link(linkTo(methodOn(EmbeddedController.class).authorDetails(2)).withSelfRel()) //
						.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //
						.build())
		.subModel( //
				ModelBuilder2 //
						.entity(new Author("Oliver Drotbhom", null, null)) //
						.link(linkTo(methodOn(EmbeddedController.class).authorDetails(2)).withSelfRel()) //
						.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //
						.build())
		.build();
```
Or like this:

```java
return ModelBuilder2 //
		.model( //
				ModelBuilder2 //
						.entity(new Author("Greg L. Turnquist", null, null)) //
						.link(linkTo(methodOn(EmbeddedController.class).authorDetails(1)).withSelfRel()) //
						.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //
						.build())
		.subModel( //
				ModelBuilder2 //
						.entity(new Author("Craig Walls", null, null)) //
						.link(linkTo(methodOn(EmbeddedController.class).authorDetails(2)).withSelfRel()) //
						.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //
						.build())
		.subModel( //
				ModelBuilder2 //
						.entity(new Author("Oliver Drotbhom", null, null)) //
						.link(linkTo(methodOn(EmbeddedController.class).authorDetails(2)).withSelfRel()) //
						.link(linkTo(methodOn(EmbeddedController.class).collection()).withRel("authors")) //
						.build())
		.link(linkTo(methodOn(EmbeddedController.class).collection()).withSelfRel()) //
		.build();
```
Both will yield:
```
{
  "_embedded" : {
    "authors" : [ {
      "name" : "Greg L. Turnquist",
      "_links" : {
        "self" : {
          "href" : "http://localhost/author/1"
        },
        "authors" : {
          "href" : "http://localhost/authors"
        }
      }
    }, {
      "name" : "Craig Walls",
      "_links" : {
        "self" : {
          "href" : "http://localhost/author/2"
        },
        "authors" : {
          "href" : "http://localhost/authors"
        }
      }
    }, {
      "name" : "Oliver Drotbhom",
      "_links" : {
        "self" : {
          "href" : "http://localhost/author/2"
        },
        "authors" : {
          "href" : "http://localhost/authors"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost/authors"
    }
  }
}
```

Also, creating a representation based upon sub-modeling, each with a custom link relation, can be done like this:

```java
 return ModelBuilder2 //
		.subModel(LinkRelation.of("author"), ModelBuilder2 //
				.entity(new Author("Alan Watts", "January 6, 1915", "November 16, 1973")) //
				.link(new Link("/people/alan-watts")) //
				.build())
		.subModel(LinkRelation.of("illustrator"), ModelBuilder2 //
				.entity(new Author("John Smith", null, null)) //
				.link(new Link("/people/john-smith")) //
				.build())
		.link(new Link("/books/the-way-of-zen")) //
		.link(new Link("/people/alan-watts", LinkRelation.of("author"))) //
		.link(new Link("/people/john-smith", LinkRelation.of("illustrator"))) //
		.build();
```
This illustrates creating two subresources, each with a different link relation, and having three top-level links. It produces this HAL document (found in the HAL spec):
```
{
  "_embedded" : {
    "author" : {
      "name" : "Alan Watts",
      "born" : "January 6, 1915",
      "died" : "November 16, 1973",
      "_links" : {
        "self" : {
          "href" : "/people/alan-watts"
        }
      }
    },
    "illustrator" : {
      "name" : "John Smith",
      "_links" : {
        "self" : {
          "href" : "/people/john-smith"
        }
      }
    }
  },
  "_links" : {
    "self" : {
      "href" : "/books/the-way-of-zen"
    },
    "author" : {
      "href" : "/people/alan-watts"
    },
    "illustrator" : {
      "href" : "/people/john-smith"
    }
  }
}
```
This is a format, that can only be produced by the current APIs if you KNOW what you're doing.

**Comment by m-van-tilburg** [comment]
Just read a lot of information about the 'subresource' support in 'spring-hateoas'. Currently we use the custom HalResource class to make embedding subresources possible (with 'spring-hateoas' 0.25.2). The HalResource class feels like a hack but I am a bit confused over what to use instead. We try to model resources in the following way

```
{
  "_embedded": {
    "userInterfaces": [
      {
        "name": "angular",
        "_links": {
          "self": {
            "href": "http://localhost:8080/dev/api/v2/userInterfaces/angular"
          },
          "themes": {
            "href": "http://localhost:8080/dev/api/v2/userInterfaces/angular/themes"
          }
        },
        "_embedded": {
          "themes": [
            {
              "name": "material",
              "_links": {
                "self": {
                  "href": "http://localhost:8080/dev/api/v2/userInterfaces/angular/themes/material"
                }
              }
            },
            {
              "name": "myCustomeTheme",
              "_links": {
                "self": {
                  "href": "http://localhost:8080/dev/api/v2/userInterfaces/angular/themes/myCustomeTheme"
                }
              }
            }
          ]
        }
      },
      {
        "name": "mvc",
        "_links": {
          "self": {
            "href": "http://localhost:8080/dev/api/v2/userInterfaces/mvc"
          },
          "themes": {
            "href": "http://localhost:8080/dev/api/v2/userInterfaces/mvc/themes"
          }
        },
        "_embedded": {
          "themes": [
            {
              "name": "bootstrap3",
              "_links": {
                "self": {
                  "href": "http://localhost:8080/dev/api/v2/userInterfaces/mvc/themes/bootstrap3"
                }
              }
            }
          ]
        }
      }
    ]
  }
}
```

We don't want the embedding of subresources to be static, sometimes resources are only embedded when the client passes a certain parameter. Is this possible without using the custom HalResource class or the yet to be released fluent API for RepresentationModel? We like to stay as close as possible to standard 'spring-hateoas' concepts.

**Comment by gregturn** [comment]
@m-van-tilburg This is a prototype that has yet to leave the branch. We are seeking feedback on what's a better form of builder to introduce.

With a builder-based approach, you most definitely could have dynamic content. These examples simply show existing examples applying the `build()` method at the end. If the `build()` has not been applied, then you can control when various clauses are applied.

But all of it is to provide an easier way to assemble complex representations than a bunch of "new" statements.

**Comment by gregturn** [comment]
Experimenting with the use case from #193 has exposed that my original solutions so far only work when confined to a single domain object type.

That's no good. What if you want to capture multiple types into a single representation?

So I took all the lessons learned, and rewrote the `ModelBuilder`. Test cases were updated, and also incorporate the use case from #193 itself as yet another test case.

Also captured tests in both WebMVC and WebFlux, verifying they work in either scenario. (Not surprising given this is REALLY just representation assembly). 

If this is acceptable, I can also update the reference documentation to illustrate using this new `ModelBuilder`.

**Comment by odrotbohm** [comment]
We took a first stab at a HAL specific model builder with 2cab91a33253e6e2e2587b868b871deb872dc168. See the [updated reference documentation](https://docs.spring.io/spring-hateoas/docs/1.1.0.BUILD-SNAPSHOT/reference/html/#mediatypes.hal.models) for details.
