### ISSUE TITLE
Improved support for HttpMessageConverters

### ISSUE THREAD

**Issue by dschulten** [spring-projects/spring-hateoas#87]
Currently we respond with Content-Type: application/json for HAL. That does not seem quite right, but I am not sure how to fix that. 

Normally one would have a HttpMessageConverter for a mime type. But since we tweak Jackson to produce HAL over MappingJacksonXXXHttpMessageConverter, things are more difficult. I am also not sure if that is a good approach in the long run.

It might be more appropriate to have a HalMappingJackson2HttpMessageConverter and a HalMappingJacksonHttpMessageConverter which could be configured like any other message converter if you want HAL support. That MessageConverter should do the Jackson tweaking internally.
If you agreee, I could look into that.

**Comment by gregturn** [comment]
Superseded by #833.
