### ISSUE TITLE
LinkBuilderSupport double encoding URL

### ISSUE THREAD

**Issue by jeffaiau** [spring-projects/spring-hateoas#96]
If the url passed into a LinkBuilderSupport class (e.g. ControllerLinkBuilder), the url is encoded twice. 

e.g. 
https://xxxxxxxxx/yyyapi/something/SPACE%2520HERE?somepara=ABC123" 

note that **SPACE%2520HERE** should be 
SPACE%20HERE the % has been encoded as %25

**Comment by ksagon** [comment]
This is still an issue in v0.19 when using ControllerLinkBuilder in conjunction with path variables.

e.g.

`linkTo(SomeAPIController.class, SomeAPIController.class.getMethod("getResource", String.class), resource.getId())`

**Comment by dk2k** [comment]
Hi guys, 
I can suggest a workaround, I use it against HalLinkDiscoverer. Brief: use a marker (a string which can be never occur in the link) and subst it with a real string - causes only one event of url encoding.

// String login; - contains the actual parameter potentially with url encoded characters
public static final String CONST_MARKER = "__MARKER__"; // assume this string can never occur in my link

Map<String, Object> params = new HashMap<>();
params.put("login", CONST_MARKER); // I found that the string passed in login param gets double url encoded. Say "kim " becomes "kim%2520"

HalLinkDiscoverer linkDiscoverer = new HalLinkDiscoverer();
Link link = linkDiscoverer.findLinkWithRel(FIND_BY_LOGIN_REL, getSearchLinks()).expand(params);
// now we have http://localhost:8080/abon-server/api/employees/search/findByLogin?login=__MARKER__

String url = link.getHref();
url = url.replace(CONST_MARKER, login); // magic happens here!
// now the link is safe and can be utilized in REST operations!
result = restOperations.getForObject(url, Employee.class);
