### ISSUE TITLE
Double <links> tag with Jackson XML

### ISSUE THREAD

**Issue by cniesen** [spring-projects/spring-hateoas#967]
I have a Spring Boot rest application that can serve both JSON and XML.  The JSON looks good but the XML returns two layers of <links>.
```
<result>
	<mydata>
	    ...
	</mydata>
	<links>
		<links>
			<rel>self</rel>
			<href>http://localhost...</href>
			<hreflang/>
			<media/>
			<title/>
			<type/>
			<deprecation/>
		</links>
		<links>
			<rel>next</rel>
			<href>http://localhost...</href>
			<hreflang/>
			<media/>
			<title/>
			<type/>
			<deprecation/>
		</links>
	</links>
</result>
```
Is that behavior the proper for HATEOAS in XML format or is there a way to suppress the double nested <links>?

BTW, I'm a bit confused by this comment (https://github.com/spring-projects/spring-hateoas/issues/275#issuecomment-469876631) that Spring HATEOAS no longer supports XML while the official documentation hints that XML should work (https://docs.spring.io/spring-hateoas/docs/current/reference/html/#fundamentals.jaxb-json).

**Comment by gregturn** [comment]
The link you provided is for `0.25.1.RELEASE`. In `1.0.0` (aka `master` branch) we've removed ALL XML support.

And to be clear, XML support that existed NEVER supported HAL. It was in there before HAL even existed.

**Comment by cniesen** [comment]
So is the above generated XML supported by Spring HATEOAS or is that just a coincidental side effect that is not supported by this project?

**Comment by gregturn** [comment]
No it’s not supported. It’s the side effect of JAXB annotations existing in the 0.25.x branch, which won’t be removed for compatibility reasons. 

It certainly is NOT HAL (let alone any other spec format or XML). 

If/when you upgrade to Boot 2.2, you’ll have to upgrade to Spring HATEOAS 1.0. Check out https://docs.spring.io/spring-hateoas/docs/1.0.0.M1/reference/html/#migrate-to-1.0 for details on now to ease your migration. 

You can also find us on gitter on the Spring-hateoas room (https://gitter.im/spring-projects/spring-hateoas).

**Comment by cniesen** [comment]
Thanks! 
Closing since this request isn't applicable.
