### ISSUE TITLE
Traverson to templated Link fails

### ISSUE THREAD

**Issue by michael-wirth** [spring-projects/spring-hateoas#971]
`Traverson.traverseToLink(false)` failes at Line 379 as it tries to resolve an expanded final URL friom an templated Link even if the boolean is set to false

proposed fix: resolve the `expandedFinalUrl` only if the boolean is set to true

```
private Link traverseToLink(boolean expandFinalUrl) {
    Assert.isTrue(rels.size() > 0, "At least one rel needs to be provided!");
    return new Link(expandFinalUrl ? traverseToExpandedFinalUrl().getUri().toString() : traverseToFinalUrl().getUri(), rels.get(rels.size() - 1).getRel());
}
```

https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/client/Traverson.java#L379

**Comment by gregturn** [comment]
I see the patch you are suggesting.

However, we have a unit test that verifies the behavior at hand => https://github.com/spring-projects/spring-hateoas/blob/master/src/test/java/org/springframework/hateoas/client/TraversonTest.java#L234-L248

Do you have a particular URI or hypermedia JSON fragment that actually makes the code blow up? That would be handy to avoid regressions.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/bee02810f696477adaa92d23c7fab5058abf15f1 and https://github.com/spring-projects/spring-hateoas/commit/f9a0c0fb13433882de8786bc0c293326640bd253.

Thanks @michael-wirth!
