### ISSUE TITLE
UriTemplate does not allow spinal-case/kebab-case

### ISSUE THREAD

**Issue by aaiezza** [spring-projects/spring-hateoas#972]
The [UriTemplate](https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/UriTemplate.java#L46) cannot successfully identify a query parameter with hyphens in it.

Example: `https://api.app.com/user{?send-verification-email}`
[RFC 6570](https://tools.ietf.org/html/rfc6570#section-3.2.2) does not discourage this type of syntax, though sadly does not give an example of it. However, I think it should be made allowed.

I would propose that the new regex for identifying templated uris be:
```regex
\{([\?\&#/]?)([\w\-\,*]+)\}
```

**Comment by odrotbohm** [comment]
According [to the RFC](https://tools.ietf.org/html/rfc6570#section-2.3), dashes are not allowed in variable names.

**Comment by gregturn** [comment]
Duplicates #799.

**Comment by aaiezza** [comment]
@gregturn you're raining on my parade here 😂
Thank you for pointing it out. As it happens, I now have comments for the "Request for Comments" RFC.

On another note, should longer variable names use underscores then or camel case?
