### ISSUE TITLE
Provide linkRelationBasedPolicy for HAL Forms

### ISSUE THREAD

**Issue by toedter** [spring-projects/spring-hateoas#981]
While it is easily possible to define that a specific link relation is always rendered as an array, even if there is only one single element, this is currently not working for HAL Forms.

For HAL, the following code snippets works well:

```
 Bean
 public HalConfiguration linkRelationBasedPolicy() {
    return new HalConfiguration()
        .withRenderSingleLinksFor(
             LinkRelation.of("directors"), HalConfiguration.RenderSingleLinks.AS_ARRAY)
         .withRenderSingleLinksFor(
             LinkRelation.of("movies"), HalConfiguration.RenderSingleLinks.AS_ARRAY);
    }
```

For HAL Forms there is no such mechanismn and this bean is ignored when settting

`@EnableHypermediaSupport(type = { HAL_FORMS })`

**Comment by gregturn** [comment]
Duplicates #832.

**Comment by odrotbohm** [comment]
With the changes made for #832, this configuration should automatically be picked up for HAL-FORMS. Would you mind giving the latest snapshots a try?
