### ISSUE TITLE
Question: JAX-RS support in 1.0

### ISSUE THREAD

**Issue by reta** [spring-projects/spring-hateoas#991]
Hey guys!

The `JaxRsLinkBuilder` & supporting classes are not present in the `1.0.0` milestones anymore. I am wondering if the support is being planned for 1.0.0 final release or dropped altogether? If latter is the case, would the independent contribution be accepted? Thank you.

Best Regards,
    Andriy Redko

**Comment by gregturn** [comment]
JAX-RS support was dropped in #700 (1.0 M1). 

As stated in #697, if anyone wants to build a 3rd party extension of Spring HATEOAS using our APIs for another stack, have at it!

**Comment by reta** [comment]
Thank you for response, @gregturn, closing the question as answered.
