### ISSUE TITLE
HAL-FORMS implementation prevents mediatype usage as intended by the specification

### ISSUE THREAD

**Issue by jadengis** [spring-projects/spring-hateoas#992]
I've been experimenting with the 1.0.0M1 release of Spring Hateoas and I find that the implementation of hal-forms in this release does not actually match the specification outlined in [https://rwcbook.github.io/hal-forms/].

In particular, the above specification indicates that hal-forms templates are to be retrieved from URI that is the link relation (e.g. `http://api.example.com/rels/create`) and then the requests described by those templates are to be sent to the href of the link that link relation refers to (e.g `http://api.example.com/task-list`).

However, this library's implementation attaches templates to the HAL document itself, and makes it impossible to implement the flow for using hal-forms described in the specification by guarding against affordances for one URI being attached to a document for another URI. That is if i had a link:
```
_links: {
    http://api.example.com/rels/create: {
        href: http://api.example.com/task-list
    }
}
```
I can't attach an affordance for `http://api.example.com/task-list` to the hal-forms document for the rel `http://api.example.com/rels/create`.

I was wondering if anything could be done to support method of using hal-forms as described in the specification.

**Comment by toedter** [comment]
As I understand the HAL-FORMS spec, the _template part of HAL-FORMS always applies to the self link of the very same REST resource.

**Comment by jadengis** [comment]
If you read the spec [here](https://rwcbook.github.io/hal-forms/), and in particular these 2 sections https://rwcbook.github.io/hal-forms/#_the_hal_forms_media_type and https://rwcbook.github.io/hal-forms/#_suggested_process_flow_for_hal_forms_documents, it is clear that the author is suggesting that the HAL-FORMs `_template` should be requested from the relation url. 

In particular, the author writes:

    After parsing the HAL response, a HAL-FORMS compliant client app MAY use the rel URLs to make
    requests for HAL-FORMS documents. In the case of this example, the http://api.example.org/rels/create
    is used to see if there is a HAL-FORMS document available.

The current implementation of HAL-FORMs in spring hateoas doesn't allow for this kind of behaviour, as their are checks in the serializer that block template links from being rendered on a document whose self link doesn't match the template link.

**Comment by odrotbohm** [comment]
I agree with @jadengis that the spec seems to be written with the assumption that HAL-FORMS documents are primarily served from dedicated resource. That is very much in line with HALs attitude to be very non-invasive to the actual JSON document's structure and serve metadata from different resources. The primary advantage of that approach is that the metadata documents can be cached independently of the actual resources and the former are usually valid much longer than the latter.

As far as I understand, the primary obstacle is that we currently insist on the affordance links being equivalent to the ones the affordances points to. I'll have to investigate with @gregturn why we have that in place. I know there was a reason, I just don't remember the details. Possible that we misunderstood something back in the days.

**Comment by odrotbohm** [comment]
After a quick glance I can only see the test fail that explicitly check for the rejection of the mismatch in URIs. I'd go ahead and remove the restriction for now. It would be cool if you could give the tweaked variant a try later on before we ship the release candidates.

**Comment by odrotbohm** [comment]
The fix is in place. Please give the snapshots a try!

**Comment by jadengis** [comment]
@odrotbohm I've tested out the snapshot and can verify that I was able to download the forms from the relation urls as I described in my original post. Thanks a lot!
